#!/usr/bin/env python3
"""terminal_census.py -- Gate-G4 bookkeeping: classify EVERY lib-undefined
symbol into its terminal state (RESOLVED-REAL / RESOLVED-LIBC / WEAK-STUBBED
with sub-class), cross-referenced against the thunkwire artifacts.

Emits docs/TERMINAL_STATES.md.  The companion docs/UNREACHABLE_LEDGER.md is
hand-curated (verdicts need proof lines); this tool prints candidate rows.

Usage: python3 tools/terminal_census.py [--lib build_modern/libviceroy_rules.a]
"""
import argparse, json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def nm(args):
    return subprocess.run(['nm'] + args, capture_output=True, text=True).stdout

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--lib', default='build_modern/libviceroy_rules.a')
    ap.add_argument('--bin', default='build_modern/viceroy_modern')
    a = ap.parse_args()
    os.chdir(ROOT)

    undef = set(re.findall(r'^\s+U (\w+)$', nm([a.lib]), re.M))
    defined_bin = set(m.group(2) for m in re.finditer(
        r'^[0-9a-f]+ ([TWDBVRtwdbvr]) (\w+)$', nm([a.bin]), re.M))
    dyn_imports = set(re.findall(r'U (\w+)',
        nm(['-D', '--undefined-only', a.bin])))
    stubs = set(re.findall(r'\)\) \w+ (\w+)\(',
        open('tools/generated/linkfloor_stubs.c').read()))

    # thunkwire knowledge
    arity_blocked = {}
    p = 'tools/generated/thunk_arity_blocked.json'
    if os.path.exists(p):
        arity_blocked = json.load(open(p))
    wiring_doc = open('docs/THUNK_WIRING.md').read() if os.path.exists('docs/THUNK_WIRING.md') else ''
    entry_split = set(re.findall(r'- `(\w+)` \|[^|]*\| .*mid-function',
                                 wiring_doc))
    if not entry_split:
        # fall back: the doc's section listing
        sec = re.search(r'### mid-function entry.*?(?=\n### |\Z)', wiring_doc, re.S)
        if sec:
            entry_split = set(re.findall(r'- `(\w+)`', sec.group(0)))

    resolved_real = sorted(s for s in undef if s in defined_bin and s not in stubs)
    resolved_libc = sorted(s for s in undef if s in dyn_imports and s not in defined_bin)
    stubbed       = sorted(s for s in undef if s in stubs)

    def subclass(s):
        if s in arity_blocked:
            return 'ARITY-PENDING (target %s, arity %d)' % (
                arity_blocked[s]['target'], arity_blocked[s]['arity'])
        if s in entry_split:
            return 'ENTRY-SPLIT-PENDING'
        if re.match(r'overlay_call_[0-9A-F]{4}_[0-9A-F]{4}$', s):
            return 'THUNK-UNRESOLVED'
        if re.match(r'func_0[0-9A-F]{5}', s):
            return 'BODY-MISSING'
        return 'NAMED-GAP'

    cats = {}
    for s in stubbed:
        cats.setdefault(subclass(s).split(' ')[0], []).append(s)

    out = []
    out.append('# Terminal-state census (auto-generated by tools/terminal_census.py)\n')
    out.append('Gate-G4 bookkeeping over every externally-undefined symbol in `%s`.\n' % a.lib)
    out.append('| state | count | meaning |')
    out.append('|---|--:|---|')
    out.append('| RESOLVED-REAL | %d | strong definition at final link (PROVIDE alias, platform direct object, archive member) |' % len(resolved_real))
    out.append('| RESOLVED-LIBC | %d | host C library provides it (dynamic import) |' % len(resolved_libc))
    out.append('| WEAK-STUBBED | %d | hit-counting no-op floor (the remaining worklist) |' % len(stubbed))
    out.append('')
    out.append('## WEAK-STUBBED breakdown\n')
    out.append('| sub-class | count | how it closes |')
    out.append('|---|--:|---|')
    rowmeans = {
        'ARITY-PENDING':  'target ported; fix each C call site to pass the measured args, then PROVIDE',
        'ENTRY-SPLIT-PENDING': 'thunk lands mid-body of a ported function; split a callable sub-entry',
        'THUNK-UNRESOLVED': 'no resolved target yet; whois + port/wire',
        'BODY-MISSING':   'port the original func_0XXXXX body',
        'NAMED-GAP':      'implement, map to ported rtl, or record UNREACHABLE(proof)',
    }
    for k in sorted(cats, key=lambda k: -len(cats[k])):
        out.append('| %s | %d | %s |' % (k, len(cats[k]), rowmeans.get(k, '')))
    out.append('')
    out.append('## RESOLVED-LIBC (host C runtime satisfies these by design)\n')
    for s in resolved_libc:
        out.append('- `%s`' % s)
    out.append('')
    out.append('## WEAK-STUBBED detail\n')
    for k in sorted(cats):
        out.append('### %s — %d\n' % (k, len(cats[k])))
        for s in cats[k]:
            out.append('- `%s`%s' % (s, '' if k != 'ARITY-PENDING' else
                       ' -> `%s` @%d' % (arity_blocked[s]['target'], arity_blocked[s]['arity'])))
        out.append('')

    open('docs/TERMINAL_STATES.md', 'w').write('\n'.join(out) + '\n')
    print('RESOLVED-REAL %d | RESOLVED-LIBC %d | WEAK-STUBBED %d' % (
        len(resolved_real), len(resolved_libc), len(stubbed)))
    for k in sorted(cats, key=lambda k: -len(cats[k])):
        print('  %-22s %d' % (k, len(cats[k])))
    print('wrote docs/TERMINAL_STATES.md')

if __name__ == '__main__':
    main()
