#!/usr/bin/env python3
"""Symbol registry for the manual's mechanics chapters.

Friendly, engine-agnostic names for the binary's functions, globals, and
record fields. The mechanics chapters use ONLY these names; the binding back
to the binary (function file offsets, DGROUP addresses, record offsets) is
emitted as Appendix C, so provenance survives the de-hexing.
"""

# friendly function names -> binary location (func_XXXXXX label)
FUNCS = {
    # production / colony
    "func_009B9C": "compute_tile_yield",
    "func_009FFC": "run_colonist_production",
    "func_009AAA": "resource_bonus",
    "func_009974": "resolve_worked_good",
    "func_008956": "worker_at_tile",
    "func_008524": "sons_of_liberty_percent",
    "func_02D658": "update_colony",
    "func_02F052": "production_phase",
    "func_009318": "grow_population",
    "func_008FB4": "starve_population",
    # market
    "func_036574": "new_game_power_init",
    "func_0305A8": "drift_prices",
    "func_032914": "sell_goods",
    "func_0324F2": "buy_goods",
    "func_030590": "sell_price",
    "func_030566": "buy_price",
    "func_07561C": "seed_market",
    "func_0322D0": "record_purchase",
    "func_03234A": "record_sale",
    "func_030B38": "is_boycotted",
    # immigration / congress
    "func_035D9A": "immigration_threshold",
    "func_0363A2": "check_immigration",
    "func_034C24": "next_immigrant_class",
    "func_030C68": "place_immigrant",
    "func_03C282": "father_cost",
    "func_03C322": "update_congress",
    "func_03BC42": "acquire_father",
    "func_03BFD2": "pick_father_candidates",
    "func_03B95A": "current_era",
    # combat
    "func_05CA7E": "resolve_attack",
    "func_05B2C2": "apply_combat_result",
    "func_05BE30": "combat_result_wrapper",
    "func_007C2A": "base_strength",
    "func_007D3E": "defence_bonus",
    "func_05E9B0": "combat_analysis_dialog",
    "func_05E714": "next_rank",
    "func_02D3C6": "shore_bombardment",
    "func_03FDDE": "move_ship",
    "func_03FA9C": "classify_ship_move",
    # exploration / natives
    "func_061454": "lost_city_rumor",
    "func_006188": "rumor_at_tile",
    "func_04A7CA": "raze_settlement",
    "func_05C878": "cash_in_treasure",
    "func_045DF2": "adjust_tension",
    "func_05BE84": "native_raid",
    "func_0572E6": "attempt_conversion",
    "func_065D26": "place_native_settlements",
    "func_04AC00": "demand_tribute",
    "func_047320": "scan_raid_targets",
    "func_046500": "native_attitude",
    "func_04891A": "native_turn_driver",
    "func_0485F6": "tribe_turn",
    "func_04830E": "settlement_tick",
    "func_046FFA": "brave_ai",
    "func_0460F8": "colony_pressure",
    "func_0427D6": "tally_tribes",
    "func_056C3E": "native_events",
    "func_04B308": "enter_village",
    "func_048F34": "village_supply_demand",
    "func_049600": "haggle_trade",
    "func_0082A0": "get_tension",
    "func_046EC0": "remove_settlement",
    "func_046E18": "create_settlement",
    "func_046FC2": "destroy_tribe_villages",
    "func_048A3A": "establish_mission",
    "func_048CA4": "denounce_heresy",
    "func_04A426": "live_among_natives",
    "func_04AF5E": "incite_natives",
    "func_046DE0": "settlement_target_size",
    "func_06BE92": "pick_native_portrait",
    "func_0081C6": "set_active_tribe",
    "func_045D00": "burn_missions",
    # king / revolution
    "func_03E664": "king_phase",
    "func_03E442": "offer_wartime_mercenaries",
    "func_03D510": "land_intervention_force",
    "func_03D948": "declare_intervention",
    "func_03E2EA": "mobilize_continentals",
    "func_03E162": "grow_royal_fund",
    "func_034AE0": "tax_petition",
    "func_034318": "apply_tax_change",
    "func_0349F4": "tax_level_warning",
    "func_036138": "schedule_king_demand",
    "func_03C638": "spanish_succession",
    "func_03CAC6": "tory_uprising",
    "func_03DE46": "declare_independence",
    "func_03E844": "update_sol",
    "func_0235D6": "menu_command_dispatch",
    "func_03334E": "pay_back_taxes",
    "func_037A10": "draw_ref_panel",
    "func_03E984": "declaration_gate",
    "func_057F4E": "run_diplomacy_meeting",
    "func_057DC0": "ai_treaty_ticker",
    "func_059B90": "evaluate_contact",
    "func_03ECF0": "ai_war_planner",
    # scoring
    "func_039EE2": "score_components",
    "func_03A9C0": "compute_score",
    "func_03ADA6": "hall_of_fame",
    "func_03B36A": "score_base",
    # turn flow
    "func_005760": "turn_loop",
    "func_0755CC": "new_game_setup",
    "func_024A48": "orders_phase",
    "func_052F7E": "diplomacy_phase",
    "func_02F3A2": "periodic_phase",
    "func_004EE6": "rotate_music",
    "func_004DF8": "tune_id",
    "func_035D9A_x": None,  # guard duplicate
    # movement / improvements
    "func_061F02": "find_path_step",
    "func_040656": "work_clear_plow",
    "func_0409D6": "work_road",
    "func_040608": "spend_tools",
    "func_040E22": "run_goto",
    "func_041080": "run_trade_route",
    "func_04101C": "complete_fortify",
    # RNG
    "func_00C322": "random_int",
    "func_009726": "placement_seed",
    "func_025D34": "shuffle_building_plots",
    "func_00738E": "set_unit_owner",
    "func_006D24": "spawn_unit",
    "func_0082DC": "select_colony",
    "func_074EC3": "load_unit_stats",
    "func_0745F0": "load_terrain_table",
}
FUNCS = {k: v for k, v in FUNCS.items() if v}

# DGROUP globals -> scoped names
GLOBALS = {
    "0x53D0": "game.revolution_meter",
    "0x53A6": "game.difficulty",
    "0x538A": "game.year",
    "0x538C": "game.season",
    "0x538E": "game.turn",
    "0x5382": "game.flags",
    "0x53D2": "game.king_power",
    "0x5398": "game.rebel_power",
    "0x5394": "game.current_power",
    "0x9E12": "game.active_player",
    "0x84FC": "power",
    "0x8542": "colony",
    "0x539C": "game.unit_count",
    "0x539E": "game.colony_count",
    "0x539A": "game.settlement_count",
    "0x53DA": "ref.regulars",
    "0x53DC": "ref.cavalry",
    "0x53DE": "ref.man_o_war",
    "0x53E0": "ref.artillery",
    "0x543F": "ai.controller",
    "0x543E": "ai.once_flags",
    "0x28EE": "rng.seed_lo",
    "0x28F0": "rng.seed_hi",
    "0x853A": "map.width",
    "0x853C": "map.height",
    "0x190": "map.seed",
    "0x0190": "map.seed",
    "0x894": "game.debug_flags",
    "0x53C8": "power.parley_stamp",
    "0x5386": "game.tutorial_seen",
    "0x53E6": "game.pending_intervention",
    "0x1DC6": "game.rumor_attempts",
    "0x1DC7": "game.rumor_treasures",
    "0x826": "game.suppress_flag",
    "0x828": "game.abort_flag",
    "0x82B": "game.forced_end",
    "0x5384": "game.colony_report_options",
    "0x53D4": "game.intervening_power",
    "0x53D6": "game.offering_power",
    "0x53D8": "game.sentiment_band",
    "0x8D4E": "tribe (active record)",
    "0x8D4A": "settlement (active record)",
    "0x8D52": "tribe (active index)",
    "0x8D50": "tribe.power_id",
    "0x1F5C": "ui.speaker_tribe",
    "0x540A": "game.woodcut_seen_mask",
    "0x9E46": "offer.count",
    "0x9E48": "offer.category_a",
    "0x9E4C": "offer.category_c",
}

# (record, offset) -> field name; scope prefix applied
FIELD_SCOPES = {
    "UnitRecord": "unit", "ColonyRecord": "colony", "PowerRecord": "power",
    "NativeSettlement": "settlement", "TerrainRecord": "terrain",
    "RouteRecord": "route", "StopRecord": "stop", "AIPersonality": "ai",
    "TribeData": "tribe",
}
FIELDS = {
    ("PowerRecord", "0x01"): "tax_rate",
    ("PowerRecord", "0x02"): "rebel_sentiment",
    ("PowerRecord", "0x0C"): "bells_pool",
    ("PowerRecord", "0x0E"): "bells_per_turn",
    ("PowerRecord", "0x10"): "crosses_per_turn",
    ("PowerRecord", "0x12"): "father_in_progress",
    ("PowerRecord", "0x14"): "father_count",
    ("PowerRecord", "0x18"): "razed_count",
    ("PowerRecord", "0x19"): "sol_percent",
    ("PowerRecord", "0x1E"): "artillery_bought",
    ("PowerRecord", "0x20"): "boycotts",
    ("PowerRecord", "0x22"): "royal_fund",
    ("PowerRecord", "0x26"): "sales_tally",
    ("PowerRecord", "0x2A"): "gold",
    ("PowerRecord", "0x2E"): "crosses",
    ("PowerRecord", "0x30"): "crosses_needed",
    ("PowerRecord", "0x32"): "home_x",
    ("PowerRecord", "0x33"): "home_y",
    ("PowerRecord", "0x34"): "relations",
    ("PowerRecord", "0x40"): "treaty_respect",
    ("PowerRecord", "0x4C"): "back_tax",
    ("PowerRecord", "0x5C"): "market_pool",
    ("PowerRecord", "0x7C"): "market_traded",
    ("PowerRecord", "0xBC"): "market_supply",
    ("PowerRecord", "0xFC"): "market_base",
    ("ColonyRecord", "0x1A"): "owner",
    ("ColonyRecord", "0x1C"): "status_bits",
    ("ColonyRecord", "0x1F"): "population",
    ("ColonyRecord", "0x40"): "professions",
    ("ColonyRecord", "0x70"): "tile_workers",
    ("ColonyRecord", "0x84"): "buildings",
    ("ColonyRecord", "0x92"): "hammers",
    ("ColonyRecord", "0x95"): "warehouse_level",
    ("ColonyRecord", "0x9A"): "stockpile",
    ("ColonyRecord", "0xC2"): "sol_pool",
    ("ColonyRecord", "0xC6"): "sol_cap",
    ("UnitRecord", "0x02"): "kind",
    ("UnitRecord", "0x03"): "owner",
    ("UnitRecord", "0x04"): "flags",
    ("UnitRecord", "0x05"): "moves_spent",
    ("UnitRecord", "0x08"): "orders",
    ("UnitRecord", "0x15"): "tools",
    ("UnitRecord", "0x16"): "work_done",
    ("UnitRecord", "0x17"): "profession",
    ("NativeSettlement", "0x02"): "owner",
    ("NativeSettlement", "0x03"): "flags",
    ("NativeSettlement", "0x04"): "population",
    ("NativeSettlement", "0x05"): "mission",
    ("NativeSettlement", "0x06"): "growth_counter",
    ("NativeSettlement", "0x07"): "trade_marker",
    ("NativeSettlement", "0x08"): "last_sold",
    ("NativeSettlement", "0x09"): "last_bought",
    ("NativeSettlement", "0x0A"): "alarm",
    ("TribeData", "0x02"): "level",
    ("TribeData", "0x03"): "status",
    ("TribeData", "0x07"): "muskets_known",
    ("TribeData", "0x08"): "horses_known",
    ("TribeData", "0x0A"): "horses_stock",
    ("TribeData", "0x36"): "tension_frac",
    ("TribeData", "0x46"): "tension",
}
