/* ============================================================================
 * load_image_008C70_00AAB9.c -- load_image functions in file range 0x008C70..0x00AAB9
 * Auto-generated by tools/full_pipeline.py for VICEROY.
 *
 * 30 functions in this file. Each carries a citation block plus
 * an auto-traced control-flow body.  Functions marked SKELETON have body
 * content derived from control-flow but their semantics still need hand-port.
 * ============================================================================ */
#include "viceroy.h"
#include "dgroup.h"
#include "overlay_externs.h"

/* ----------------------------------------------------------------------------
 * File-local overlay LCALL targets that are NOT (yet) declared in
 * overlay_externs.h.  Declared here so the ports below compile; addresses are
 * the RTLink seg:off of the far CALL as seen in the disassembly.
 * (TODO: promote these to include/overlay_externs.h.)
 * -------------------------------------------------------------------------- */
/* overlay_call_05B3_0004 and overlay_call_05B3_01E0 now declared in overlay_externs.h */
extern int overlay_call_0981_0000(uint16_t power, uint16_t flag);  /* @ref seg 0x0981 off 0x0000 */
extern int overlay_call_037F_02F8();  /* @ref seg 0x037F off 0x02F8 (func_00A6A2) */
extern int overlay_call_037F_0598();  /* @ref seg 0x037F off 0x0598 (func_00A6A2) */
extern int overlay_call_0427_0992();  /* @ref seg 0x0427 off 0x0992 (func_00A6A2) */

/* Cross-file strong ports used by the 0x90C8/0x9102/0x91CC colonist-resolver
 * chain (a bare func_XXXX name in this file otherwise binds to the linkfloor
 * weak stub, which returns 0). */
extern int func_008BD4_op_sz_73(uint16_t arg0);      /* file 0x8BD4: nth owned unit on the colony tile
                                                      * (load_image_008262_008C6F.c) */
extern int func_008BB2_logic_sz_20(uint16_t arg0);   /* file 0x8BB2: per-unit-type attribute, table 0x30E
                                                      * (load_image_008262_008C6F.c) */
extern int func_0036B2_type_sprite_id(uint16_t r_ax);/* file 0x36B2 = resident 0x012B:0x0002 (arg in AX):
                                                      * type id -> ICONS sprite (load_image_0033F2_004E76.c) */
extern int menu_run_boxed(uint16_t key_off);         /* PORTED 0x181F:0x3FE runner (src/ui/menu_runner.c) */

/* @asm        0x008C70..0x008CFF  (144 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_008C70_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 2
 * @args_seen  []
 * @lcalls     3
 * @near_calls 1
 * @callers    0
 * @touches_8542 True
 *
 * LCALL targets:
 *   - 0x0427:0x005C  (unit-at-tile iterator init)
 *   - 0x0427:0x004A  (unit-at-tile iterator next)
 *
 * Near CALL targets:
 *   - 0x008B96
 * @inferred_role  tally units on the colony tile: count owned (0x8D72), total
 *                 (0x8D74) and "no-class" (0x8D76); clamp owned to 50; clear 0x8D7A
 * @status     BYTE_VERIFIED 2026-06-09 (full body decompiled from VICEROY.EXE)
 * @note   Auto-tracer reported 66 bytes / @inferred_role MISSING_ASM, a FALSE cut at
 *         0x8CB2.  The disassembly (func_008C70.asm) IS present: true function is
 *         0x8C70..0x8CFF (144 bytes), ending leave/retf @0x8CFE; the loop body and
 *         post-loop clamp truncated by the tracer are decompiled here.
 */
int func_008C70_logic_sz_66(void)
{
    /* @asm 0x8C74 zero counters [0x8D72]=[0x8D74]=[0x8D76]=0; bx=ctx; ax=(u8)ctx[0]
     *      (map_x), dx=(u8)ctx[1] (map_y); lcall 0427:005C(map_x,map_y) -> first
     *      unit index, stored at [0x8D78]; jmp test.
     *      loop body 0x8C96: push idx; call 0x8B96(idx); or ax,ax; jne -> inc [0x8D72]
     *      (owned tally); bx=idx*0x1C; bl=(u8)UnitRecord[idx][+2] (0x3146); bx=bl*14
     *      (shl1;add;shl1;add;shl1); cmp byte[bx+0x5237],0; je -> inc [0x8D76]
     *      (no-class tally); inc [0x8D74] (total); ax=idx; lcall 0427:004A(idx)->next.
     *      test 0x8CD3: [bp-2]=idx; or ax,ax; jge 0x8C96 (continue while idx>=0).
     *      0x8CDA ax=[0x8D72]; if ax>0x32 ax=0x32; [0x8D72]=ax (clamp owned to 50).
     *      0x8CE8 if [0x8D76]!=0 && [0x8D7A]>=[0x8D76]: [0x8D7A]=0.
     * Iterates the units standing on the current colony's map tile (ctx@0x8542,
     * map_x/map_y at +0/+1) via the 0427:005C/004A iterator, building three running
     * tallies at DGROUP 0x8D72 (owned, by func_008B96), 0x8D74 (total) and 0x8D76
     * ("no-class": UnitRecord +2 maps to a zero byte in the 14-stride table at
     * 0x5237). Clamps the owned tally to 50 and, when there were no-class units and
     * 0x8D7A has reached/exceeded their count, resets 0x8D7A to 0. */
    unsigned char near *ctx_local = (unsigned char near *)ctx;
    int idx;
    int16_t owned;
    DG16(0x8D72) = 0;
    DG16(0x8D74) = 0;
    DG16(0x8D76) = 0;
    /* lcall 0427:005C(map_x, map_y) -> first unit index (args in AX/DX); ret in AX */
    idx = overlay_call_0427_005C(ctx[0], ctx[1]);
    DG16(0x8D78) = (uint16_t)idx;
    while (idx >= 0) {
        if (func_008B96((uint16_t)idx) != 0)               /* unit owned by current power */
            DG16(0x8D72)++;
        {
            uint8_t cls = (uint8_t)DG8(0x3146 + (unsigned)idx * 0x1C);  /* UnitRecord[idx] +2 */
            if (DG8(0x5237 + (unsigned)cls * 14) == 0)
                DG16(0x8D76)++;                            /* no-class tally */
        }
        DG16(0x8D74)++;                                    /* total tally */
        idx = overlay_call_0427_004A((uint16_t)idx);       /* next unit on tile */
    }
    owned = (int16_t)DG16(0x8D72);
    if (owned > 0x32) owned = 0x32;                        /* clamp owned to 50 */
    DG16(0x8D72) = (uint16_t)owned;
    if (DG16(0x8D76) != 0 && (int16_t)DG16(0x8D7A) >= (int16_t)DG16(0x8D76))
        DG16(0x8D7A) = 0;
    (void)ctx_local;
    return 0;
}

/* @asm        0x008D26..0x008D9B  (118 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_008D26_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 4
 * @args_seen  [6, 8]
 * @lcalls     3
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x037F:0x000A  (tile in-bounds predicate)
 *   - 0x037F:0x0358  (tile-has-colony predicate)
 *   - 0x181F:0x03FE  (assert/error with message ptr 0x0350)
 * @inferred_role  colony index at tile (arg0,arg1): scan colony_table @0x5D46 for
 *                 the colony whose map_x/map_y match; -1 (+ assert) if none
 * @status     BYTE_VERIFIED 2026-06-09 (full body decompiled from VICEROY.EXE)
 * @note   Auto-tracer reported 69 bytes ending 0x8D6B: a FALSE cut.  Disassembly
 *         (func_008D26.asm) IS present: true function is 0x8D26..0x8D9B (118 bytes),
 *         the colony-table scan and the assert tail were truncated.
 */
int func_008D26_op_sz_69(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x8D2A result[bp-4]=-1; push arg1,arg0; lcall 037F:000A(arg0,arg1);
     *      or ax,ax; je 0x8D97 (tile out of bounds -> -1);
     *      push arg1,arg0; lcall 037F:0358(arg0,arg1); or ax,ax; jl 0x8D97
     *      (no colony on tile -> -1); i[bp-2]=0; jmp test.
     *      loop 0x8D5A: ax=[0x539E] (colony count); cmp i,ax; jge 0x8D88;
     *      al=(u8)arg0; bx=i*0xCA; cmp byte[bx+0x5D46],al; jne next; al=(u8)arg1;
     *      cmp byte[bx+0x5D47],al; jne next; result=i (match). next: i++.
     *      test 0x8D82: cmp result,0; jl 0x8D5A (keep scanning while result<0).
     *      0x8D88 if result>=0 -> 0x8D97; else lea bx,[0x0350]; lcall 181F:03FE
     *      (assert/error). 0x8D97 return result.
     * Returns the index of the colony occupying map tile (arg0,arg1) by matching
     * map_x (+0) / map_y (+1) across the colony_table at 0x5D46 (stride 0xCA, count
     * 0x539E). Guards on the in-bounds (037F:000A) and tile-has-colony (037F:0358)
     * overlay predicates and, if those pass yet no table row matches, fires the
     * 181F:03FE assert (message ptr 0x0350) before returning -1. */
    int16_t result = -1;
    int i;
    if (overlay_call_037F_000A(arg0_bp_06, arg1_bp_08) == 0)     /* tile in bounds? */
        return -1;
    if (overlay_call_037F_0358(arg0_bp_06, arg1_bp_08) < 0)      /* colony on tile? */
        return -1;
    for (i = 0; result < 0 && i < (int16_t)DG16(0x539E); i++) {
        if (DG8(0x5D46 + (unsigned)i * 0xCA) == (uint8_t)arg0_bp_06 &&
            DG8(0x5D47 + (unsigned)i * 0xCA) == (uint8_t)arg1_bp_08)
            result = (int16_t)i;
    }
    if (result < 0)
        (void)menu_run_boxed(0x0350);     /* @asm 0x008D8E lea bx,[0x350] "COLONYFLAG";
                                           * 0x008D92 lcall 0x181F:0x3FE (PORTED runner;
                                           * assert: colony expected) */
    return result;
}

/* @asm        0x008D9C..0x008DBB  (31 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_008D9C_lookup_table_2F4_signed.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 2
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  signed-byte lookup into table 0x2F4 for arg0<0x13, else -1
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_008D9C_lookup_table_2F4_signed(uint16_t arg0_bp_06)
{
    /* @asm 0x008DA0 mov [bp-2],0xffff (result=-1); 0x008DA5 cmp [bp+6],0x13;
     *      jge 0x8db6; 0x008DAB mov bx,[bp+6]; mov al,[bx+0x2f4]; cwde;
     *      mov [bp-2],ax; 0x008DB6 mov ax,[bp-2]; ret.
     * Returns the signed byte at DGROUP table 0x02F4 indexed by arg0 when
     * arg0 < 0x13, otherwise -1. Sits beside the per-good tables 0x2AA/0x2F5/0x2FD
     * (cf. func_008BC6 reading 0x02F5). */
    if ((int16_t)arg0_bp_06 >= 0x13)
        return -1;
    return (int8_t)DG8(0x02F4 + (unsigned)arg0_bp_06);
}

/* @asm        0x008DBC..0x008E01  (69 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_008DBC_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 2
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  Europe-market spread: g_global_amount[g]-g_band_base[g], minus chained good
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_008DBC_logic_sz_69(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x008DC0 mov bx,[bp+6]; shl bx,1; mov ax,[bx-0x7238];
     *      sub ax,[bx-0x71f6]; mov [bp-2],ax  (diff = g_global_amount[g]
     *      - g_band_base[g]);  -0x7238==0x8DC8, -0x71f6==0x8E0A.
     *      0x008DD0 mov bx,[bp+6]; cmp byte[bx+0x2a2],0; jl 0x8dfc (skip if the
     *      good has no chained good); 0x008DDA mov al,[bx+0x2a2]; cwde; bx=ax*2;
     *      ax=[bp-2]-[bx-0x71a6]; mov [bp-2],ax  (-0x71a6==0x8E5A=g_over_high;
     *      subtract the chained good's over-high value);
     *      0x008DED cmp [bp+8],0; je 0x8dfc; mov ax,[bx-0x71a6]; mov bx,[bp+8];
     *      mov [bx],ax  (when arg1!=0, write that chained over-high to *arg1);
     *      0x008DFC mov ax,[bp-2]; ret.
     * Computes the Europe-market spread for good arg0: g_global_amount[arg0]
     * (0x8DC8) minus g_band_base[arg0] (0x8E0A); if good arg0 maps to a chained
     * good via the per-good byte table at 0x02A2, subtracts that chained good's
     * g_over_high[] entry (0x8E5A) and (when arg1!=0) writes it back through arg1.
     * Returns the resulting spread. (Market arrays: globals.h §0x8DC8 block.) */
    int16_t diff = (int16_t)(DG16(0x8DC8 + (unsigned)arg0_bp_06 * 2)
                             - DG16(0x8E0A + (unsigned)arg0_bp_06 * 2));
    int8_t chained = (int8_t)DG8(0x02A2 + (unsigned)arg0_bp_06);
    if (chained >= 0) {
        uint16_t over_high = DG16(0x8E5A + (unsigned)(uint16_t)chained * 2);
        diff = (int16_t)(diff - over_high);
        if (arg1_bp_08 != 0)
            *(uint16_t near *)arg1_bp_08 = over_high;
    }
    return diff;
}

/* @asm        0x008E84..0x008EFC  (120 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_008E84_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   ENTER 6
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 3
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x008D9C
 *   - 0x00864E
 *   - 0x008E46
 * @inferred_role  market adjust: dispatch g_global_amount[arg1] to arg0, then re-scale g_over_high[arg0]
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_008E84_logic_sz_120(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x008E88 bx=[bp+8]*2; ax=[bx-0x7238] (g_global_amount[arg1]);
     *      mov [bp-6],ax; mov [bp-4],ax  (orig = amount = g_global_amount[arg1]).
     *      0x008E97 push [bp+8]; call 0x8d9c (chained=func_008D9C(arg1));
     *      push chained; call 0x864e (cnt=func_00864E(chained));
     *      0x008EA9 cmp ax,2; jle 0x8ebc; (if cnt>2) ax=[bp-4]; shl ax,1; cx=3;
     *      cdq; idiv cx; mov [bp-4],ax  (amount = amount*2/3).
     *      0x008EBC push [bp-4]; push [bp+6]; call 0x8e46 (func_008E46(arg0,amount)).
     *      0x008EC9 bx=[bp+6]*2; cmp [bx-0x71a6],0; je 0x8f00 (g_over_high[arg0]==0:
     *      no rescale); 0x008ED5 ax=[bp-4]; cmp [bp-6],ax; je 0x8f00 (unchanged:
     *      done); cmp [bx-0x71a6],ax; jne 0x8ee8; (==amount) ax=[bp-6];
     *      jmp store (restore original); 0x008EE8 bx=[bp+6]*2; ax=[bx-0x71a6];
     *      cx=ax; ax<<=1; ax+=cx (3*go); cdq; ax-=dx; sar ax,1 (floor(3*go/2));
     *      0x008EFC mov [bx-0x71a6],ax  (g_over_high[arg0]=ax).
     * Posts the amount g_global_amount[arg1] (0x8DC8) into commodity arg0 via
     * func_008E46, scaled to 2/3 when arg1's chain (func_008D9C/func_00864E) has
     * more than 2 members, then re-scales the over-high marker g_over_high[arg0]
     * (0x8E5A): restore the original on an exact-match, otherwise raise it to
     * floor(3*over_high/2). Returns the (rescaled) over-high value left in ax. */
    int16_t amount = (int16_t)DG16(0x8DC8 + (unsigned)arg1_bp_08 * 2);
    int16_t orig = amount;
    int chained = func_008D9C(arg1_bp_08);            /* func_008D9C_lookup_table_2F4_signed */
    if (func_00864E((uint16_t)chained) > 2)           /* func_00864E_logic_sz_31 */
        amount = (int16_t)((int32_t)(int16_t)(amount << 1) / 3);  /* (amount*2)/3, 16-bit shl */
    func_008E46(arg0_bp_06, (uint16_t)amount);        /* @asm 0x8E46 (61B): set commodity arg0's market value */
    {
        uint16_t near *over_high = (uint16_t near *)(0x8E5A + (unsigned)arg0_bp_06 * 2);
        if (*over_high != 0 && orig != amount) {
            if ((int16_t)*over_high == amount)
                *over_high = (uint16_t)orig;
            else {
                int16_t go = (int16_t)*over_high;
                int16_t triple = (int16_t)((go << 1) + go);   /* 3*go in 16-bit */
                *over_high = (uint16_t)(int16_t)((int32_t)triple / 2);  /* floor toward 0 */
            }
        }
        return (int16_t)*over_high;
    }
}

/* @asm        0x008FB4..0x00903E  (138 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_008FB4_unknown.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 4
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 2
 * @callers    0
 * @touches_8542 True
 *
 * Near CALL targets:
 *   - 0x008F2A
 *   - 0x008F6C
 * @inferred_role  remove colonist #arg0 from current colony (compact arrays, renumber tiles, dec pop/bells)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_008FB4_colony_sz_138(uint16_t arg0_bp_06)
{
    /* @asm 0x008FB9 mov [bp-4],[bp+6] (i=arg0); jmp test.
     *   loop body 0x008FC2: bx=ctx+i; byte[bx+0x20]=byte[bx+0x21] (job[i]=job[i+1]);
     *     byte[bx+0x40]=byte[bx+0x41] (unit_type[i]=unit_type[i+1]); push i+1;
     *     call 0x8f2a (e=func_008F2A(i+1) reads packed expertise[i+1]); push e;
     *     push i; call 0x8f6c (func_008F6C(i,e) writes packed expertise[i]); i++.
     *   test 0x008FEB: bx=[0x8542]; ax=(int8)ctx->pop(+0x1f); ax--; cmp ax,i;
     *     jg 0x8fc2  (continue while ctx->pop-1 > i).
     *   0x008FF9 mov [bp-2],0 (j=0); tile_state renumber loop:
     *     0x00900E cmp j,0x14; jge done; 0x009014 al=arg0; bx=[0x8542]; si=j;
     *     cmp byte[bx+si+0x70],arg0; jne 0x9000 (decrement scan):
     *       0x009000 cmp byte[bx+si+0x70],arg0; jle 0x900b; dec byte[bx+si+0x70];
     *     match: 0x009023 mov byte[bx+si+0x70],0xff; j++.
     *   0x00902A bx=[0x8542]; dec byte[bx+0x1f] (pop--); sub word[bx+0xc6],0x64;
     *     sbb word[bx+0xc8],0  (32-bit bells numerator -= 100).
     * Removes colonist #arg0 from the current colony (ctx@0x8542): shifts the
     * per-colonist job (+0x20), unit_type (+0x40) and packed-nibble expertise
     * (+0x60, via func_008F2A/func_008F6C) arrays down one slot, renumbers the
     * tile_state[20] array at +0x70 (entries > arg0 decremented, the matching
     * one set to 0xFF), then decrements population (+0x1f) and the 32-bit bells
     * numerator (+0xC6) by 100. ColonyRecord fields per DGROUP_MEMORY_MAP §3.4. */
    int i;
    unsigned char near *ctx_local = (unsigned char near *)ctx;
    for (i = arg0_bp_06; ; i++) {
        if (!(((int8_t)ctx_local[0x1F] - 1) > i))
            break;
        ctx_local[i + 0x20] = ctx_local[i + 0x21];    /* job[i]      = job[i+1]      */
        ctx_local[i + 0x40] = ctx_local[i + 0x41];    /* unit_type[i]= unit_type[i+1]*/
        func_008F6C((uint16_t)i,                       /* expertise[i]= expertise[i+1]*/
                    (uint16_t)func_008F2A((uint16_t)(i + 1)));
    }
    {
        int j;
        for (j = 0; j < 0x14; j++) {
            if (ctx_local[j + 0x70] == (uint8_t)arg0_bp_06)
                ctx_local[j + 0x70] = 0xFF;
            else if ((int8_t)ctx_local[j + 0x70] > (int8_t)(uint8_t)arg0_bp_06)
                ctx_local[j + 0x70]--;
        }
        ctx_local[0x1F]--;                             /* population-- */
        *(uint32_t near *)(ctx_local + 0xC6) -= 0x64; /* bells numerator -= 100 */
    }
    return 0;
}

/* @asm        0x00903E..0x0090C7  (138 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00903E.asm
 * @pattern    JUMP_TABLE
 * @prologue   ENTER 2
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  emit the building-class word list for category arg1 into arg0[]; return count
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 * @note   Auto-tracer reported 37 bytes / TINY_ACCESSOR: a FALSE cut at 0x9063
 *         (before the jump table). True function is 0x903E..0x90C7 (138 bytes), a
 *         switch on arg1 via `jmp cs:[bx+0xE06]`; span/role corrected here.
 */
int func_00903E_logic_sz_138(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x009043 mov [bp-2],0 (i=0); ax=[bp+8] (arg1); jmp 0x90a6.
     *      dispatch 0x0090A6: sub ax,0x13; cmp ax,5; ja 0x90c2 (default);
     *      shl ax,1; xchg bx,ax; jmp cs:[bx+0xe06]  (6-entry table at CS:0x0E06).
     *      table -> case arg1=0x14 -> 0x9064; 0x15 -> 0x904e; 0x16 -> 0x9072;
     *      0x17 -> 0x9080; 0x13 & 0x18 -> 0x90c2 (default).
     *      Each writer uses bx=i*2, si=arg0 (bp+6): mov word[bx+si],VAL; inc i.
     *      0x00904E (0x15): out[i]=0xf; i++; return i.
     *      0x009064 (0x14): out[i]=0xe; jmp 0x905a (i++; return i).
     *      0x009072 (0x16): out[i]=8;   jmp 0x905a (i++; return i).
     *      0x009080 (0x17): out[i]=0xf; i++; out[i]=8; i++; return i.
     *      0x0090C2 default: return i (0).
     * For the colony building/feature category arg1, appends the matching tile
     * IDs to the caller's word array arg0[] and returns how many were written:
     * 0x14->{0xE}, 0x15->{0xF}, 0x16->{8}, 0x17->{0xF,8}, else {} (0). */
    uint16_t near *out = (uint16_t near *)arg0_bp_06;
    int i = 0;
    switch (arg1_bp_08) {
    case 0x14:  out[i++] = 0x0E; break;
    case 0x15:  out[i++] = 0x0F; break;
    case 0x16:  out[i++] = 0x08; break;
    case 0x17:  out[i++] = 0x0F; out[i++] = 0x08; break;
    default:    break;                                  /* 0x13, 0x18, others -> none */
    }
    return i;
}

/* @asm        0x0090C8..0x009101  (58 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0090C8.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 2
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 2
 * @callers    3+ (near 0x91D4 func_0091CC, 0x9994 func_009974; thunk 0x181F:0x0C0E)
 * @touches_8542 True
 *
 * Near CALL targets:
 *   - 0x008BD4  (resolve out-of-colony unit index)
 *   - 0x008BB2  (per-unit-type attribute, table 0x30E)
 * @inferred_role  job/class byte for colony slot arg0 (+0x20 array; slots past
 *                 the population map through func_008BD4 to the tile units)
 * @status     BYTE_VERIFIED 2026-06-12 (full body decompiled from VICEROY.EXE)
 * @note   Strong port under the BARE name so it overrides the linkfloor weak
 *         stub: the bare-name call sites (func_0091CC @0x91D4, func_009974
 *         @0x9994, and the rewired 0x181F:0x0C0E painter sites in
 *         overlay_024342_027B62.c) all bind here.  The in-colony half was
 *         previously ported as current_unit_field_at_20 (src/colony/
 *         accessors.c); this is the FULL function including the out-of-colony
 *         tail that accessors.c approximates with a sentinel return.
 */
int func_0090C8(uint16_t arg0_bp_06)
{
    /* @asm 0x90CD bx=[0x8542] (ctx); al=(int8)ctx->pop(+0x1F); cbw;
     *      cmp ax,[bp+6]; jle 0x90E6 (slot >= population: external unit).
     *      in-colony 0x90DA: si=[bp+6]; al=byte[bx+si+0x20]; sub ah,ah
     *      (ZERO-extend) -> return ctx->job[slot].
     *      external 0x90E6: al=(int8)ctx->pop; cbw; sub ax,[bp+6]; neg ax
     *      (= slot - pop); push ax; call 0x8BD4 (u = func_008BD4(slot-pop));
     *      0x90F7 push ax; call 0x8BB2 -> return func_008BB2(u).
     * Job/class byte for colony slot arg0.  Colonists (slot < population,
     * ctx@0x8542 pop@+0x1F) read the per-colonist job array at +0x20; slots at/
     * past the population denote the units standing on the colony's map tile,
     * resolved via func_008BD4(slot - pop) and classed through func_008BB2
     * (the signed per-unit-type attribute byte at table 0x30E). */
    unsigned char near *ctx_local = (unsigned char near *)ctx;
    if ((int16_t)(int8_t)ctx_local[0x1F] > (int16_t)arg0_bp_06)
        return ctx_local[arg0_bp_06 + 0x20];             /* @asm 0x90DD..0x90E0 */
    {
        int16_t u = (int16_t)func_008BD4_op_sz_73(       /* @asm 0x90F1 call 0x8BD4 */
            (uint16_t)((int16_t)arg0_bp_06 - (int8_t)ctx_local[0x1F]));
        return func_008BB2_logic_sz_20((uint16_t)u);     /* @asm 0x90F9 call 0x8BB2 */
    }
}

/* @asm        0x009102..0x00913B  (58 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009102.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 2
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 1
 * @callers    3+ (near 0x91E1 func_0091CC, 0x99A1 func_009974; thunk 0x181F:0x0C54)
 * @touches_8542 True
 *
 * Near CALL targets:
 *   - 0x008BD4  (resolve out-of-colony unit index)
 * @inferred_role  unit-type/profession byte for colony slot arg0 (+0x40 array;
 *                 out-of-colony slots read UnitRecord vet_type +0x17 @0x315B)
 * @status     BYTE_VERIFIED 2026-06-12 (full body decompiled from VICEROY.EXE)
 * @note   Strong port under the BARE name (overrides the linkfloor weak stub);
 *         sister of func_0090C8, and the getter counterpart of func_00913C
 *         below (which writes the same two locations).  In-colony half
 *         previously ported as current_unit_field_at_40 (src/colony/
 *         accessors.c) without the out-of-colony tail.
 */
int func_009102(uint16_t arg0_bp_06)
{
    /* @asm 0x9107 bx=[0x8542]; al=(int8)ctx->pop(+0x1F); cbw; cmp ax,[bp+6];
     *      jle 0x9120 (slot >= population: external unit).
     *      in-colony 0x9114: si=[bp+6]; al=byte[bx+si+0x40]; sub ah,ah
     *      (ZERO-extend) -> return ctx->unit_type[slot].
     *      external 0x9120: ax=(int8)ctx->pop; sub ax,[bp+6]; neg ax
     *      (= slot - pop); push ax; call 0x8BD4 (u); 0x9131 imul bx,ax,0x1C;
     *      al=byte[bx+0x315B]; cbw (SIGN-extend) -> UnitRecord[u].vet_type.
     * Unit-type/profession byte for colony slot arg0: colonists read the
     * per-colonist unit_type array at +0x40; slots past the population resolve
     * the tile unit via func_008BD4(slot - pop) and return its UnitRecord
     * vet_type (+0x17 == 0x315B, stride 0x1C, DGROUP_MEMORY_MAP §3.1). */
    unsigned char near *ctx_local = (unsigned char near *)ctx;
    if ((int16_t)(int8_t)ctx_local[0x1F] > (int16_t)arg0_bp_06)
        return ctx_local[arg0_bp_06 + 0x40];             /* @asm 0x9117..0x911A */
    {
        int16_t u = (int16_t)func_008BD4_op_sz_73(       /* @asm 0x912B call 0x8BD4 */
            (uint16_t)((int16_t)arg0_bp_06 - (int8_t)ctx_local[0x1F]));
        return (int8_t)DG8(0x315B + (unsigned)(uint16_t)u * 0x1C); /* @asm 0x9131..0x9138 */
    }
}

/* @asm        0x00913C..0x009165  (41 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00913C_unknown.asm
 * @pattern    WRAPPER_NEARCALL
 * @prologue   ENTER 2
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 True
 *
 * Near CALL targets:
 *   - 0x008BD4
 * @inferred_role  set unit_type for colony slot arg0 (in-colony +0x40 array, else UnitRecord vet +0x17)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 * @note   Auto-tracer reported 41 bytes / pure wrapper: a FALSE cut at 0x9165.
 *         True function is 0x913C..0x9183 (72 bytes); the in-colony store branch
 *         that precedes the func_008BD4 path was truncated and is decompiled here.
 */
int func_00913C_logic_sz_72(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x009141 cmp [bp+8],0x17; jne 0x914c; mov [bp+8],0x15 (fold type
     *      0x17 -> 0x15).  0x00914C mov bx,[0x8542]; al=(int8)ctx->pop(+0x1f);
     *      cwde; cmp ax,[bp+6]; jle 0x9166 (slot >= population: external unit).
     *      in-colony 0x009159: al=(uint8)[bp+8]; si=[bp+6];
     *      mov byte[bx+si+0x40],al (ctx->unit_type[slot] = type); ret.
     *      external 0x009166: al=(int8)ctx->pop(+0x1f); cwde; sub ax,[bp+6];
     *      neg ax (= slot - pop); push ax; call 0x8bd4
     *      (u = func_008BD4(slot - pop)); imul bx,u,0x1c; al=(uint8)[bp+8];
     *      mov byte[bx+0x315b],al (UnitRecord[u].vet_type +0x17 = type); ret.
     * Sets the unit-type for colony slot arg0 to arg1 (folding 0x17->0x15). When
     * arg0 is within the current colony's population (ctx@0x8542, +0x1F) it writes
     * the per-colonist unit_type array at +0x40; otherwise arg0 indexes a unit
     * outside the colony, resolved via func_008BD4(arg0 - pop), whose UnitRecord
     * vet_type (+0x17 == 0x315B, DGROUP_MEMORY_MAP §3.1) is set instead. */
    unsigned char near *ctx_local = (unsigned char near *)ctx;
    if (arg1_bp_08 == 0x17)
        arg1_bp_08 = 0x15;                              /* fold type 0x17 -> 0x15 */
    if ((int16_t)(int8_t)ctx_local[0x1F] > (int16_t)arg0_bp_06) {
        ctx_local[arg0_bp_06 + 0x40] = (uint8_t)arg1_bp_08; /* in-colony unit_type[slot] */
    } else {
        int16_t u = (int16_t)func_008BD4_op_sz_73(      /* real port (was weak-stub bare name) */
            (uint16_t)(arg0_bp_06 - (int8_t)ctx_local[0x1F]));
        DG8(0x3144 + (unsigned)u * 0x1C + 0x17) = (uint8_t)arg1_bp_08;
    }
    return 0;
}

/* @asm        0x0091CC..0x009281  (181 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0091CC_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   ENTER 8
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 3
 * @callers    0
 * @touches_8542 True
 *
 * Near CALL targets:
 *   - 0x0090C8  (current_unit_field_at_20 -> "job/class" byte)
 *   - 0x009102  (current_unit_field_at_40 -> "profession" byte)
 *   - 0x008BD4  (resolve out-of-colony unit index)
 * @inferred_role COLONY_TOUCHED — display/sprite id for colony slot arg0
 * @status     BYTE_VERIFIED 2026-06-09 (full body decompiled from VICEROY.EXE)
 * @note   Auto-tracer reported 181 bytes ending 0x9281: a FALSE cut.  Disassembly
 *         (func_0091CC.asm) IS present: true function is 0x91CC..0x9298 (205 bytes);
 *         the whole field20>0x13 branch and its UnitRecord lookup were truncated.
 *         LCALL 0x012B:0x0002 (arg in AX, not on the stack) is the resident
 *         type->sprite table-map leaf at file 0x36B2, ported 2026-06-12 as
 *         func_0036B2_type_sprite_id (load_image_0033F2_004E76.c) and called
 *         directly below; the whole resolver chain (func_0090C8/func_009102/
 *         func_008BD4/func_008BB2/0x36B2) is now real.
 */
int func_0091CC_colony_sz_181(uint16_t arg0_bp_06)
{
    /* @asm 0x91D0 field20[bp-8]=func_0090C8(arg0); field40[bp-6]=func_009102(arg0);
     *      cmp field20,0x13; jg 0x9206 (else branch when field20>0x13).
     *   small-id path (field20<=0x13): if field40==0x1c -> field40=0x13;
     *      result[bp-4]=lcall 012B:0002(field40); jmp 0x9291; return result.
     *   big-id path 0x9206: result=field20+0x52; flag[bp-2]=(field40==field20);
     *      if field40==0x15 && field20==0x17 -> flag=1; if !flag -> result=field20+0x36;
     *      if field20==0x15 || field20==0x17:
     *        u=func_008BD4(arg0 - (i8)ctx->pop);     (out-of-colony unit index)
     *        cls=UnitRecord[u][+2] (0x3146); if cls==9 || cls==7:
     *           result = (u8)table_5232[cls*14];
     *      0x9294 return result.
     * Computes the colony-panel display id for slot arg0.  Low classes (field20<=
     * 0x13) map straight through overlay 012B:0002 (folding profession 0x1c->0x13);
     * higher classes get a base of field20+0x52, bumped to field20+0x36 when the
     * profession does NOT match the class (with the 0x15/0x17 special-case), and
     * overridden to a 14-stride table_5232 entry when slot arg0 is an out-of-colony
     * soldier/dragoon (UnitRecord +2 == 9 or 7).  ctx@0x8542, pop@+0x1F. */
    unsigned char near *ctx_local = (unsigned char near *)ctx;
    int16_t field20 = (int16_t)func_0090C8(arg0_bp_06);    /* @0x91D4 (real port above) */
    int16_t field40 = (int16_t)func_009102(arg0_bp_06);    /* @0x91E1 (real port above) */
    int16_t result;
    if (field20 <= 0x13) {
        if (field40 == 0x1C)
            field40 = 0x13;                                /* fold profession 0x1c -> 0x13 */
        result = (int16_t)func_0036B2_type_sprite_id(      /* @0x91FD lcall 0x012B:0x0002, arg in AX */
            (uint16_t)field40);
        return result;
    }
    result = (int16_t)(field20 + 0x52);                    /* default big-id base */
    {
        int flag = (field40 == field20) ? 1 : 0;
        if (field40 == 0x15 && field20 == 0x17)
            flag = 1;
        if (!flag)
            result = (int16_t)(field20 + 0x36);            /* profession-mismatch base */
    }
    if (field20 == 0x15 || field20 == 0x17) {
        int16_t u = (int16_t)func_008BD4_op_sz_73(      /* real port (was weak-stub bare name) */
            (uint16_t)((int16_t)arg0_bp_06 - (int8_t)ctx_local[0x1F]));
        uint8_t cls = (uint8_t)DG8(0x3146 + (unsigned)(uint16_t)u * 0x1C);  /* UnitRecord +2 */
        if (cls == 9 || cls == 7)
            result = (uint8_t)DG8(0x5232 + (unsigned)cls * 14);
    }
    return result;
}

/* @asm        0x009626..0x00965B  (53 bytes)  region=load_image
 * @asm_file   re_work/disasm/func_009626.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 4
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 1  (0x0090C8)
 * @callers    func_009818 (this file), sol_tory.c (colony_misc_b82 thunk)
 * @touches_8542 True
 *
 * @inferred_role  count colonists in current colony whose job (func_0090C8(i)) == arg0
 * @status     BYTE_VERIFIED 2026-06-12 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-12 from func_009626.asm — count colony slots with job == arg0 */
int func_009626(uint16_t arg0_bp_06)
{
    /* @asm 0x00962A count[bp-2]=0; i[bp-4]=0; jmp test.
     *   loop 0x009634: push i; call 0x90C8 (func_0090C8(i)); cmp ax,[bp+6];
     *     jne skip; inc count.  skip: inc i.
     *   test 0x009649: bx=[0x8542] (ctx); al=(int8)ctx[+0x1F] (pop); cbw;
     *     cmp ax,i; jg loop.
     *   return count.
     * Walks every colonist slot 0..pop-1 in the current colony (ctx@0x8542,
     * pop@+0x1F) and returns the count where func_0090C8(i) == arg0. */
    unsigned char near *ctx_local = (unsigned char near *)ctx;
    int count = 0;
    int i = 0;
    while ((int16_t)(int8_t)ctx_local[0x1F] > i) {
        if ((uint16_t)func_0090C8((uint16_t)i) == arg0_bp_06)
            count++;
        i++;
    }
    return count;
}

/* @asm        0x009726..0x00975A  (52 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009726_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 4
 * @args_seen  []
 * @lcalls     2
 * @near_calls 0
 * @callers    0
 * @touches_8542 True
 *
 * LCALL targets:
 *   - 0x09EF:0x002C
 *   - 0x09EF:0x001A
 * @inferred_role  feed the colony tile id ((map_y<<8)+map_x)+*0x8D80 to overlay
 *                 09EF:001A, after notifying 09EF:002C([0x917A])
 * @status     BYTE_VERIFIED 2026-06-09 (full body decompiled from VICEROY.EXE)
 * @note   Auto-tracer @inferred_role MISSING_ASM, but func_009726.asm IS present.
 *         True function is 0x9726..0x9759 (52 bytes); the 32-bit tile-id formed
 *         between the two overlay calls is decompiled here.
 */
int func_009726_logic_sz_52(void)
{
    /* @asm 0x972A push [0x917A]; lcall 09EF:002C([0x917A]) (result discarded).
     *      0x9736 bx=ctx; ax=(ctx[1]<<8) (ah=ctx[+1] map_y, al=0); cdq;
     *      cx=(u8)ctx[0] (map_x); ax+=cx; dx+=adc 0 (sign-extended (map_y<<8)+map_x);
     *      add ax,[0x8D80]; adc dx,[0x8D82] (+= 32-bit base at 0x8D80);
     *      push dx; push ax; lcall 09EF:001A(tile_id32).
     * Builds the packed tile coordinate ((ctx->map_y<<8) | ctx->map_x) as a signed
     * 32-bit value, adds the 32-bit base at DGROUP 0x8D80, and hands the result to
     * overlay 09EF:001A -- after first signalling overlay 09EF:002C with the word at
     * 0x917A. ctx@0x8542 map_x/map_y at +0/+1. */
    unsigned char near *ctx_local = (unsigned char near *)ctx;
    int32_t tile_id;
    overlay_call_09EF_002C(/* DG16(0x917A) */);
    tile_id = (int32_t)(((int32_t)ctx_local[1] << 8) + (int32_t)ctx_local[0]);
    tile_id += (int32_t)DG32(0x8D80);
    overlay_call_09EF_001A(tile_id);
    return 0;
}

/* @asm        0x00975A..0x009773  (25 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00975A_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  walks chain 0x8f85 (stride 12) to its root, returns root index
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_00975A_logic_sz_25(uint16_t arg0_bp_06)
{
    /* @asm 0x00975D cmp [bp+6],0; jl 0x9781 (return arg0 when arg0<0);
     *      jmp 0x976e; loop 0x9766: mov al,[bx-0x707b]; cwde; mov [bp+6],ax;
     *      0x00976e mov bx,[bp+6]; mov ax,bx; shl bx,1; add bx,ax; shl bx,2
     *      (bx=arg0*12); cmp byte[bx-0x707b],0; jge 0x9766; 0x009781 ret arg0.
     * Follows the signed-byte chain at 0x8f85 (-0x707b, pitch 12) while the next
     * link is non-negative and returns the root index; arg0<0 is returned as-is.
     * (Sister of func_0086C0 which uses the adjacent 0x8f86 chain.) */
    if ((int16_t)arg0_bp_06 < 0)
        return arg0_bp_06;
    while ((int8_t)DG8(0x8F85 + (unsigned)arg0_bp_06 * 12) >= 0)
        arg0_bp_06 = (uint16_t)(int16_t)(int8_t)
            DG8(0x8F85 + (unsigned)arg0_bp_06 * 12);
    return arg0_bp_06;
}

/* @asm        0x009786..0x009792  (12 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009786_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 2
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  signed per-good byte lookup at table 0x2CA
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_009786_logic_sz_12(uint16_t arg0_bp_06)
{
    /* @asm 0x00978A mov bx,[bp+6]; 0x00978D mov al,[bx+0x2ca]; 0x009791 cwde.
     * Signed-byte lookup into the DGROUP table at 0x02CA indexed by arg0 (a
     * good/commodity id), in the per-good static-table band near 0x2AA/0x2F4/0x2FD
     * (cf. func_008BC6 @0x2F5, func_008D9C @0x2F4). */
    return (int8_t)DG8(0x02CA + (unsigned)arg0_bp_06);
}

/* @asm        0x009794..0x0097D5  (66 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009794.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 2
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 2
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x00975A
 *   - 0x00863E
 * @inferred_role  if the colony-bit for root(arg0) is set, return table_8E92[table_8F88[root]]; else -1
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 * @note   Auto-tracer reported 39 bytes ending 0x97BB: a FALSE cut. True function
 *         is 0x9794..0x97D5 (66 bytes); the table walk after the bit-test was
 *         truncated and is decompiled here.
 */
int func_009794_logic_sz_66(uint16_t arg0_bp_06)
{
    /* @asm 0x009798 mov [bp-2],0xffff (result=-1); push [bp+6]; call 0x975a
     *      (r=func_00975A(arg0)=chain root on the 0x8F85 chain); mov [bp+6],ax;
     *      push ax; call 0x863e (func_00863E(r) colony bit-test); or ax,ax;
     *      je 0x97d1 (bit clear -> return -1);
     *      0x0097B6 bx=r*12 (shl1; add r; shl2); al=(int8)byte[bx-0x7078]; cwde
     *      (b = table_8F88[r], the +2 field of the stride-12 chain record);
     *      bx=b; al=(int8)byte[bx-0x716e]; cwde; mov [bp-2],ax
     *      (result = table_8E92[b]); 0x0097D1 mov ax,[bp-2]; ret.
     * Resolves arg0 to its chain root r (func_00975A on the 0x8F85 chain) and, if
     * the colony bit func_00863E(r) is set, returns table_8E92[ table_8F88[r] ]
     * (signed bytes). -0x7078==0x8F88 (chain record +2, stride 12 @0x8F86),
     * -0x716e==0x8E92. Returns -1 when the bit is clear. */
    int16_t r = (int16_t)func_00975A(arg0_bp_06);       /* chain root (func_00975A) */
    int8_t b;
    if (func_00863E((uint16_t)r) == 0)                  /* func_00863E colony bit-test */
        return -1;
    b = (int8_t)DG8(0x8F88 + (unsigned)(uint16_t)r * 12);  /* chain +2 */
    return (int8_t)DG8(0x8E92 + (unsigned)(uint16_t)b);
}

/* @asm        0x0097D6..0x009817  (66 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0097D6.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 4
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x00863E
 * @inferred_role  reverse lookup: chain index c with table_8E82[c]==arg0 (gated by func_00863E); else -1
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 * @note   Auto-tracer reported 28 bytes ending 0x97F2: a FALSE cut. True function
 *         is 0x97D6..0x9817 (66 bytes); the table walk and match test after the
 *         bit-test were truncated and are decompiled here.
 */
int func_0097D6_logic_sz_66(uint16_t arg0_bp_06)
{
    /* @asm 0x0097DA mov [bp-4],0xffff (result=-1); push [bp+6]; call 0x863e
     *      (func_00863E(arg0) colony bit-test); or ax,ax; je 0x9813 (clear -> -1);
     *      0x0097ED bx=arg0*12 (shl1; add; shl2); al=(int8)byte[bx-0x7078]; cwde
     *      (b = table_8F88[arg0]); bx=b; al=(int8)byte[bx-0x716e]; cwde
     *      (c = table_8E92[b]); bx=c; al=(uint8)arg0;
     *      cmp byte[bx-0x717e],al; jne 0x9813 (table_8E82[c] != arg0 -> -1);
     *      mov [bp-4],bx (result=c); 0x009813 mov ax,[bp-4]; ret.
     * If the colony bit func_00863E(arg0) is set, follows the parallel tables
     * table_8F88[arg0] -> b, table_8E92[b] -> c, and returns c when
     * table_8E82[c] equals arg0 (i.e. c is the chain index that maps back to
     * arg0); otherwise -1. -0x7078==0x8F88, -0x716e==0x8E92, -0x717e==0x8E82. */
    int8_t b, c;
    if (func_00863E(arg0_bp_06) == 0)                   /* func_00863E colony bit-test */
        return -1;
    b = (int8_t)DG8(0x8F88 + (unsigned)arg0_bp_06 * 12);
    c = (int8_t)DG8(0x8E92 + (unsigned)(uint16_t)b);
    if (DG8(0x8E82 + (unsigned)(uint16_t)c) != (uint8_t)arg0_bp_06)
        return -1;
    return (uint16_t)c;
}

/* @asm        0x009818..0x009874  (93 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009818_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 6
 * @args_seen  [6]
 * @lcalls     1
 * @near_calls 4
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0427:0x004A  (unit-at-tile iterator next)
 *
 * Near CALL targets:
 *   - 0x00975A  (chain root on 0x8F85)
 *   - 0x008B96  (unit owned by current power?)
 *   - 0x009786  (per-good signed lookup @0x2CA)
 *   - 0x009626  (helper, overlay-resident)
 * @inferred_role  if arg0 is a chain root -> count owned units on the colony tile,
 *                 negated; else map arg0 via 0x9786 -> func_009626
 * @status     BYTE_VERIFIED 2026-06-09 (full body decompiled from VICEROY.EXE)
 * @note   Auto-tracer reported 66 bytes ending 0x985A: a FALSE cut.  Disassembly
 *         (func_009818.asm) IS present: true function is 0x9818..0x9874 (93 bytes);
 *         the func_00975A!=0 branch (0x985A..0x9874) was truncated.
 */
int func_009818_op_sz_66(uint16_t arg0_bp_06)
{
    /* @asm 0x981C count[bp-2]=0; root=func_00975A(arg0); or ax,ax; jne 0x985A.
     *   root==0 path: it[bp-6]=[0x8D78]; jmp test; loop 0x9834: push it;
     *     call 0x8B96(it); or ax,ax; jne -> inc count; it=lcall 0427:004A(it);
     *     test 0x984B: it=ax; or ax,ax; jge 0x9834.  0x9852 neg count; return count.
     *   root!=0 path 0x985A: s=func_009786(arg0); or ax,ax; jl 0x9870 (return count=0);
     *     [bp-2]=func_009626(s); 0x9870 return [bp-2].
     * When func_00975A(arg0) resolves arg0 to chain-root 0 (the "current colony"
     * chain), counts how many units along the 0427:004A iterator (seeded from
     * 0x8D78) are owned by the current power (func_008B96) and returns the NEGATED
     * count.  Otherwise resolves arg0 through the per-good table at 0x2CA
     * (func_009786) and, if non-negative, returns func_009626 of it (else 0). */
    int16_t count = 0;
    if (func_00975A(arg0_bp_06) == 0) {
        int it = (int16_t)DG16(0x8D78);
        while (it >= 0) {
            if (func_008B96((uint16_t)it) != 0)
                count++;
            it = overlay_call_0427_004A((uint16_t)it);     /* next unit on tile */
        }
        return -count;
    } else {
        int16_t s = (int16_t)func_009786(arg0_bp_06);      /* per-good lookup @0x2CA */
        if (s < 0)
            return count;                                  /* count==0 */
        return (int16_t)func_009626((uint16_t)s);
    }
}

/* @asm        0x009876..0x0098B4  (62 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009876_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 4
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x008D9C
 * @inferred_role  classify good arg0 -> 0 (none) / 1 (chain leaf) / 2 (chain has successor)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_009876_logic_sz_62(uint16_t arg0_bp_06)
{
    /* @asm 0x00987A mov [bp-4],0 (result=0); cmp [bp+6],0; jl 0x98af (arg0<0 ->0);
     *      0x009885 push [bp+6]; call 0x8d9c (c=func_008D9C(arg0)); or ax,ax;
     *      jl 0x98af (c<0 -> 0); 0x009893 mov [bp-4],1 (result=1);
     *      bx=c*12 (shl1; add c; shl2); al=(int8)byte[bx-0x707a]; cwde; or ax,ax;
     *      jl 0x98af (chain[c]<0 -> result stays 1);
     *      0x0098aa mov [bp-4],2 (result=2); 0x0098af mov ax,[bp-4]; ret.
     * Classifies good arg0 by resolving it (func_008D9C, table 0x2F4) to a chain
     * index c and inspecting the stride-12 chain table at 0x8F86 (-0x707a):
     * 0 if arg0<0 or unresolved, 1 if c is a chain leaf (chain[c]<0), 2 if c has
     * a non-negative successor. Chain table per DGROUP_MEMORY_MAP §2 (0x8F86). */
    int c;
    if ((int16_t)arg0_bp_06 < 0)
        return 0;
    c = func_008D9C(arg0_bp_06);                       /* func_008D9C_lookup_table_2F4_signed */
    if (c < 0)
        return 0;
    if ((int8_t)DG8(0x8F86 + (unsigned)(uint16_t)c * 12) < 0)
        return 1;
    return 2;
}

/* @asm        0x0098B4..0x0098F5  (65 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0098B4_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 6
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  return 200; *arg1=20; *arg0=clamp((farptr[0x83E]->+0x152 +1)*20 -1, 118)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_0098B4_logic_sz_65(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x0098B8 mov [bp-4],0x14 (=20); mov [bp-6],0xc8 (=200);
     *      0x0098C2 cmp [bp+8],0; je 0x98cf; mov bx,[bp+8]; mov word[bx],0x14
     *      (when arg1!=0, *arg1 = 20);
     *      0x0098CF cmp [bp+6],0; je 0x98f0; les bx,[0x83e];
     *      mov ax,es:[bx+0x152]; inc ax; imul [bp-4] (ax=(field+1)*20); dec ax;
     *      cmp ax,0x76; jle 0x98eb; mov ax,0x76 (clamp to 118);
     *      0x0098eb mov bx,[bp+6]; mov [bx],ax (*arg0 = clamped);
     *      0x0098f0 mov ax,[bp-6]; ret  (return 200).
     * Always returns 200. When arg1!=0 writes 20 to *arg1. When arg0!=0 writes
     * clamp((far[0x83E]->word[+0x152] + 1) * 20 - 1, max 118) to *arg0 -- the
     * same (val+1)*N stage/threshold idiom noted in DGROUP_MEMORY_MAP §5.2, here
     * with N=20 and an upper bound of 0x76. far ptr at DGROUP 0x083E. */
    if (arg1_bp_08 != 0)
        *(uint16_t near *)arg1_bp_08 = 0x14;            /* 20 */
    if (arg0_bp_06 != 0) {
        uint16_t field = *(uint16_t far *)((uint8_t far *)(*(void far * near *)0x083E)
                                           + 0x152);
        int16_t v = (int16_t)((uint16_t)((field + 1) * 0x14) - 1); /* low-16 of (field+1)*20, -1 */
        if (v > 0x76)
            v = 0x76;                                   /* clamp to 118 (signed jle) */
        *(uint16_t near *)arg0_bp_06 = (uint16_t)v;
    }
    return 0xC8;                                        /* 200 */
}

/* @asm        0x0098F6..0x00994B  (85 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0098F6_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 6
 * @args_seen  [6, 8, 10]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x008956
 * @inferred_role  scan 5x5 grid for func_008956(i,j)==arg0; write j->*arg1, i->*arg2; ret 1 if found
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_0098F6_logic_sz_85(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    /* @asm 0x0098FA sub ax,ax; mov [bp-6],ax (found=0); mov [bp-4],ax (i=0);
     *      jmp 0x9939.  outer test 0x009939: cmp [bp-4],5; jge 0x9946 (done);
     *      0x00993F mov [bp-2],0 (j=0); jmp 0x9907.
     *      inner test 0x009907: cmp [bp-2],5; jge 0x9936 (i++ at 0x9936);
     *      body 0x00990D: push [bp-4]; push [bp-2]; call 0x8956
     *      (func_008956(i,j)); cmp al,[bp+6]; jne 0x9904 (j++);
     *      match: mov ax,[bp-2]; mov bx,[bp+8]; mov [bx],ax (*arg1=j);
     *      mov ax,[bp-4]; mov bx,[bp+0xa]; mov [bx],ax (*arg2=i); mov [bp-6],1;
     *      0x009904 inc [bp-2] (j++); jmp 0x9907.  0x009946 mov ax,[bp-6]; ret.
     * Scans the 5x5 grid (i,j in 0..4) calling func_008956(i,j); on each match
     * with the low byte of arg0 it writes j to *arg1 and i to *arg2 and sets the
     * found flag (the loop keeps going, so the LAST match wins). Returns 1 if any
     * cell matched, else 0. */
    int found = 0;
    int i, j;
    for (i = 0; i < 5; i++) {
        for (j = 0; j < 5; j++) {
            if ((uint8_t)func_008956((uint16_t)i, (uint16_t)j) == (uint8_t)arg0_bp_06) {
                *(uint16_t near *)arg1_bp_08 = (uint16_t)j;
                *(uint16_t near *)arg2_bp_0A = (uint16_t)i;
                found = 1;
            }
        }
    }
    return found;
}

/* @asm        0x00994C..0x009974  (40 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00994C_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 4
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 2
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x0098F6
 *   - 0x008982
 * @inferred_role  if func_0098F6 resolves a pair, forwards it to func_008982
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
void func_00994C_logic_sz_40(uint16_t arg0_bp_06)
{
    /* @asm 0x009950 lea ax,[bp-4]; push ax; lea cx,[bp-2]; push cx;
     *      push [bp+6]; call 0x98f6 (func_0098F6(arg0, &a, &b) fills two locals);
     *      0x009962 or ax,ax; je 0x9972 (do nothing on 0);
     *      0x009966 push -1; push [bp-4]; push [bp-2];
     *      call 0x8982 (func_008982(a, b, -1)).
     * Resolves a coordinate/index pair via func_0098F6 and, on success, hands
     * it (with sentinel -1) to func_008982. */
    uint16_t a = 0, b = 0;
    if (func_0098F6(arg0_bp_06, &a, &b) != 0)
        func_008982(a, b, (uint16_t)-1);
}

/* @asm        0x009974..0x009986  (18 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009974_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  resolves func_008956(arg0,arg1); maps via func_0090C8/func_009102
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_009974_logic_sz_18(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t *arg2_bp_0A)
{
    /* @asm 0x009978 mov [bp-2],0xffff (result=-1); push [bp+8]; push [bp+6];
     *      call 0x8956 (func_008956(arg0,arg1)); cwde; mov [bp-4],ax (r, signed);
     *      or ax,ax; jl 0x99a9 (return -1 if r<0);
     *      0x009992 push ax; call 0x90c8 (result=func_0090C8(r));
     *      0x00999d push [bp-4]; call 0x9102; mov bx,[bp+0xa]; mov [bx],ax
     *      (*arg2 = func_009102(r)); 0x0099a9 return result.
     * Maps a resolved index r=func_008956(arg0,arg1) through func_0090C8 (return
     * value) and func_009102 (written to the out-pointer arg2); -1 when r<0.
     * NOTE: the auto-trace under-counted args; the real function reads [bp+0xa]. */
    int16_t r = (int16_t)func_008956(arg0_bp_06, arg1_bp_08);
    int result;
    if (r < 0)
        return -1;
    result = (int)func_0090C8(r);                       /* @0x009994 (first) */
    *arg2_bp_0A = (uint16_t)func_009102(r);             /* @0x0099a1 (second) */
    return result;
}

/* @asm        0x0099AE..0x0099ED  (63 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0099AE_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 4
 * @args_seen  [6, 8, 10, 12]
 * @lcalls     2
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x037F:0x000A  (tile in-bounds predicate)
 *   - 0x037F:0x010E  (tile terrain/feature byte)
 * @inferred_role  predicate: in-bounds AND (010E(arg0,arg1)&0x1F) in [arg2,arg3]
 * @status     BYTE_VERIFIED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
int func_0099AE_op_sz_63(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    /* @asm 0x99B2 result[bp-2]=0; push arg1,arg0; lcall 037F:000A(arg0,arg1);
     *      or ax,ax; je 0x99E8 (out of bounds -> 0);
     *      push arg1,arg0; lcall 037F:010E(arg0,arg1); and al,0x1F;
     *      cmp al,(u8)arg2; jb 0x99E8 (terrain < arg2 -> 0);
     *      cmp al,(u8)arg3; ja 0x99E8 (terrain > arg3 -> 0); result=1; return result.
     * Returns 1 iff tile (arg0,arg1) is in bounds (037F:000A) and its low-5-bit
     * terrain/feature code (037F:010E & 0x1F) lies within the inclusive band
     * [arg2, arg3] (unsigned byte compares); otherwise 0.  Overlay calls shown
     * 0-arg to match overlay_externs.h; real args in comment. */
    if (overlay_call_037F_000A(arg0_bp_06, arg1_bp_08) != 0) {
        unsigned terrain = (unsigned)(overlay_call_037F_010E(arg0_bp_06, arg1_bp_08) & 0x1F);
        if (terrain >= (uint8_t)arg2_bp_0A && terrain <= (uint8_t)arg3_bp_0C)
            return 1;
    }
    return 0;
}

/* @asm        0x0099EE..0x009A31  (67 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0099EE_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 4
 * @args_seen  [6, 8, 10, 12]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x0099AE
 * @inferred_role  sum func_0099AE(x+dx[i], y+dy[i], arg2, arg3) over the 8 neighbours
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_0099EE_logic_sz_67(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    /* @asm 0x0099F2 sub ax,ax; mov [bp-2],ax (sum=0); mov [bp-4],ax (i=0);
     *      jmp 0x9a26.  test 0x009A26: cmp [bp-4],8; jl 0x99fc.
     *      body 0x0099FC: push (byte)[bp+0xc] (arg3); push (byte)[bp+0xa] (arg2);
     *      bx=i; ax=(int8)byte[bx+0xbe](dy[i]) + [bp+8](y); push ax;
     *      ax=(int8)byte[bx+0xb4](dx[i]) + [bp+6](x); push ax;
     *      call 0x99ae (func_0099AE(x+dx[i], y+dy[i], arg2, arg3));
     *      add [bp-2],ax (sum += result); inc [bp-4] (i++).
     *      0x009A2C mov ax,[bp-2]; ret.
     * Accumulates func_0099AE over the eight neighbouring tiles of (arg0,arg1),
     * using the 8-direction delta tables dx@0x00B4 {0,1,1,1,0,-1,-1,-1} and
     * dy@0x00BE {-1,-1,0,1,1,1,0,-1}. arg2/arg3 pass through (as bytes). */
    static const signed char dx[8] = { 0, 1, 1, 1, 0, -1, -1, -1 };  /* DGROUP 0x00B4 */
    static const signed char dy[8] = { -1, -1, 0, 1, 1, 1, 0, -1 };  /* DGROUP 0x00BE */
    int sum = 0;
    int i;
    for (i = 0; i < 8; i++)
        sum += func_0099AE((uint16_t)(arg0_bp_06 + dx[i]),  /* func_0099AE_op_sz_63 */
                           (uint16_t)(arg1_bp_08 + dy[i]),
                           (uint8_t)arg2_bp_0A, (uint8_t)arg3_bp_0C);
    return sum;
}

/* @asm        0x009A32..0x009A6A  (56 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009A32_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 2
 * @args_seen  [6, 8, 10]
 * @lcalls     2
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x037F:0x000A
 *   - 0x037F:0x0142
 * @inferred_role  predicate: overlay 0x000A(arg0,arg1) AND (0x0142(arg0,arg1)&arg2)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_009A32_op_sz_56(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    /* @asm 0x009A3B push [bp+8]; push [bp+6]; lcall 0x37f:0xa; or ax,ax;
     *      je 0x9a65 (result stays 0 when overlay 0x000A returns 0);
     *      0x009A4D push [bp+8]; push [bp+6]; lcall 0x37f:0x142; 0x009A5B
     *      test [bp+0xa],al; je 0x9a65; 0x009A60 mov [bp-2],1; 0x009A65 ret.
     * Returns 1 iff overlay 0x037F:0x000A(arg0,arg1) is non-zero AND the low byte
     * of overlay 0x037F:0x0142(arg0,arg1) shares a set bit with arg2's low byte.
     * Overlay calls shown 0-arg to match overlay_externs.h; real args in comment. */
    if (overlay_call_037F_000A(arg0_bp_06, arg1_bp_08) != 0) {
        int mask = overlay_call_037F_0142(arg0_bp_06, arg1_bp_08);
        if ((arg2_bp_0A & mask & 0xFF) != 0)
            return 1;
    }
    return 0;
}

/* @asm        0x009A6A..0x009AA9  (63 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009A6A_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 4
 * @args_seen  [6, 8, 10]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x009A32
 * @inferred_role  count func_009A32(x+dx[i], y+dy[i], arg2) over the 8 neighbours
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_009A6A_logic_sz_63(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    /* @asm 0x009A6E sub ax,ax; mov [bp-2],ax (sum=0); mov [bp-4],ax (i=0);
     *      jmp 0x9a9e.  test 0x009A9E: cmp [bp-4],8; jl 0x9a78.
     *      body 0x009A78: push (byte)[bp+0xa] (arg2); bx=i;
     *      ax=(int8)byte[bx+0xbe](dy[i]) + [bp+8](y); push ax;
     *      ax=(int8)byte[bx+0xb4](dx[i]) + [bp+6](x); push ax;
     *      call 0x9a32 (func_009A32(x+dx[i], y+dy[i], arg2));
     *      add [bp-2],ax (sum += result); inc [bp-4] (i++).
     *      0x009AA4 mov ax,[bp-2]; ret.
     * Accumulates the tile predicate func_009A32 (returns 0/1) over the eight
     * neighbours of (arg0,arg1) using dx@0x00B4 / dy@0x00BE; effectively counts
     * how many of the 8 surrounding tiles satisfy func_009A32(.,.,arg2). */
    static const signed char dx[8] = { 0, 1, 1, 1, 0, -1, -1, -1 };  /* DGROUP 0x00B4 */
    static const signed char dy[8] = { -1, -1, 0, 1, 1, 1, 0, -1 };  /* DGROUP 0x00BE */
    int sum = 0;
    int i;
    for (i = 0; i < 8; i++)
        sum += func_009A32((uint16_t)(arg0_bp_06 + dx[i]),  /* func_009A32_op_sz_56 */
                           (uint16_t)(arg1_bp_08 + dy[i]),
                           (uint8_t)arg2_bp_0A);
    return sum;
}

/* @asm        0x009AAA..0x009B9B  (241 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009AAA_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 2
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  (arg0,arg1) matchup score table: sums per-pair bonuses/penalties
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_009AAA_logic_sz_241(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x009AAE mov [bp-2],0 (score=0); then a flat sequence of
     *      `cmp [bp+6],A; jne .; cmp [bp+8],B; jne .; <op> [bp-2]` tests, each
     *      adjusting the score when (arg0==A && arg1==B), evaluated in order:
     *        (9,0): mov  [bp-2],2     (set 2)
     *        (1,0): add  [bp-2],2
     *        (2,0): add  [bp-2],2
     *        (9,4): add  [bp-2],2
     *        (8,4): add  [bp-2],3
     *        (3,3): mov  [bp-2],0xffff (set -1)
     *        (4,2): mov  [bp-2],0xffff (set -1)
     *        (5,1): mov  [bp-2],0xffff (set -1)
     *        (10,5):add  [bp-2],2
     *        (6,6): add  [bp-2],3
     *        (13,6):add  [bp-2],2
     *        (6,7): inc  [bp-2]
     *        (12,7):add  [bp-2],2
     *        (7,8): add  [bp-2],3
     *      0x009B96 mov ax,[bp-2]; ret.
     * Maps an ordered pair (arg0,arg1) -- two small category ids -- to a matchup
     * score, accumulating the listed per-pair bonuses and applying the -1/2 SET
     * overrides for the (3,3)/(4,2)/(5,1) pairs. The checks run sequentially (not
     * a switch), so the exact order and set-vs-add semantics are preserved. */
    int16_t score = 0;
    if (arg0_bp_06 == 9  && arg1_bp_08 == 0) score = 2;
    if (arg0_bp_06 == 1  && arg1_bp_08 == 0) score += 2;
    if (arg0_bp_06 == 2  && arg1_bp_08 == 0) score += 2;
    if (arg0_bp_06 == 9  && arg1_bp_08 == 4) score += 2;
    if (arg0_bp_06 == 8  && arg1_bp_08 == 4) score += 3;
    if (arg0_bp_06 == 3  && arg1_bp_08 == 3) score = -1;
    if (arg0_bp_06 == 4  && arg1_bp_08 == 2) score = -1;
    if (arg0_bp_06 == 5  && arg1_bp_08 == 1) score = -1;
    if (arg0_bp_06 == 10 && arg1_bp_08 == 5) score += 2;
    if (arg0_bp_06 == 6  && arg1_bp_08 == 6) score += 3;
    if (arg0_bp_06 == 13 && arg1_bp_08 == 6) score += 2;
    if (arg0_bp_06 == 6  && arg1_bp_08 == 7) score += 1;
    if (arg0_bp_06 == 12 && arg1_bp_08 == 7) score += 2;
    if (arg0_bp_06 == 7  && arg1_bp_08 == 8) score += 3;
    return score;
}

/* @asm        0x009B9C..0x009FFC  (1120 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009B9C_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 0x2a
 * @args_seen  [6, 8, 10, 12]
 * @lcalls     9
 * @near_calls 7
 * @callers    0
 * @touches_8542 True
 *
 * LCALL targets:
 *   - 0x037F:0x010E
 *   - 0x03E4:0x000E
 *   - 0x037F:0x04B0
 *   - 0x037F:0x0142  (6x)
 *
 * Near CALL targets:
 *   - 0x009974
 *   - 0x0099EE
 *   - 0x008956
 *   - 0x009102
 *   - 0x008524
 *   - 0x009AAA
 *   - 0x00863E
 * @inferred_role  per-(tile, worked-good) terrain-yield engine
 * @status     FORWARDER 2026-06-09 (canonical body lives in colony/turn_update.c)
 * @note   This is the same function as compute_terrain_yield(ring_a, ring_b, out,
 *         flag) which is fully decompiled (byte-verified) in
 *         src/colony/turn_update.c (0x9B9C..0x9FFB).  The auto-skeleton here was a
 *         broken duplicate (and mislabelled MISSING_ASM); to avoid a second
 *         definition of the same logic this is a thin forwarder to the canonical
 *         implementation.  Arg map (cdecl): arg0=ring_a [bp+6], arg1=ring_b [bp+8],
 *         arg2=out-ptr [bp+0xA], arg3=flag [bp+0xC].
 */
extern int compute_terrain_yield(int ring_a, int ring_b, int *out, int flag);

int func_009B9C_logic_sz_1120(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    return compute_terrain_yield((int16_t)arg0_bp_06, (int16_t)arg1_bp_08,
                                 (int *)arg2_bp_0A, (int16_t)arg3_bp_0C);
}

/* @asm        0x009FFC..0x00A222  (550 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_009FFC_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 0x1c
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 8
 * @callers    0
 * @touches_8542 True
 *
 * Near CALL targets:
 *   - 0x0090C8
 *   - 0x009102
 *   - 0x008524
 *   - 0x008D9C
 *   - 0x0086E4
 *   - 0x00863E  (2x)
 *   - 0x00864E
 * @inferred_role COLONY_TOUCHED — per-colonist building-output engine
 * @status     FORWARDER 2026-06-09 (canonical body lives in colony/colonist_handler.c)
 * @note   This is the same function as unit_individual_handler_9FFC(colonist_idx,
 *         meta), fully decompiled (byte-verified) in src/colony/colonist_handler.c
 *         (0x9FFC..0xA221).  The auto-skeleton here was a broken duplicate; to
 *         avoid a second definition this is a thin forwarder.  Arg map (cdecl):
 *         arg0=colonist_idx [bp+6], arg1=meta out-ptr [bp+8].
 */
extern int unit_individual_handler_9FFC(int colonist_idx, int *meta);

int func_009FFC_colony_sz_550(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    return unit_individual_handler_9FFC((int16_t)arg0_bp_06, (int *)arg1_bp_08);
}

/* @asm        0x00A6A2..0x00A93D  (668 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00A6A2_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 0x1e / PUSH SI
 * @args_seen  [6, 8]
 * @lcalls     9
 * @near_calls 2
 * @callers    0
 * @touches_8542 True
 *
 * LCALL targets:
 *   - 0x037F:0x000A  (tile in-bounds)            0x037F:0x02F8 (tile owner-mask)
 *   - 0x037F:0x003C  (radius/ownership predicate) 0x037F:0x0314 (tile owner id)
 *   - 0x037F:0x0598  (tile blocked?)             0x03E4:0x0074 (tile water?)
 *   - 0x0427:0x005C / 0x004A (unit iterator)     0x0427:0x0992 (mark unit)
 *
 * Near CALL targets:
 *   - 0x008720  (current-power id)   0x008892  (colony-relative tile resolve)
 * @inferred_role COLONY_TOUCHED — compute the candidate-tile flag byte for the 5x5
 *                colony work grid cell (arg0,arg1): bit 0x10 unusable, 0x80 enemy
 *                unit, 0x02 special, 0x04 wonder, 0x40 adj other-colony territory,
 *                0x20 sits under another colony, 0x08 colony centre.
 * @status     BYTE_VERIFIED 2026-06-09 (full body decompiled from VICEROY.EXE)
 * @note   functions.json / auto-tracer split this at the early `retf` @0x00A723,
 *         reporting only 130 bytes.  The TRUE function (objdump 0xA6A2..0xA93D,
 *         668 bytes, single ENTER/leave-retf @0xA93C) continues through the whole
 *         flag-building scan and is decompiled in full here.  Bit values are the
 *         literal `or byte[bp-6],<imm>` constants.
 */
int func_00A6A2_colony_sz_130(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    unsigned char near *ctx_local = (unsigned char near *)ctx;
    int flags = 0;                                          /* [bp-6] */
    int16_t px   = (int16_t)((uint8_t)ctx_local[0] + (int16_t)arg0_bp_06 - 2);  /* [bp-2] */
    int16_t py   = (int16_t)((uint8_t)ctx_local[1] + (int16_t)arg1_bp_08 - 2);  /* [bp-4] */
    int16_t adx;                                            /* [bp-0x10] = abs(arg0-2) */
    int16_t ady;                                            /* [bp-0x14] = abs(arg1-2) */
    int16_t owner_here;                                     /* [bp-0x16] */
    int j;                                                  /* [bp-0xc] */

    /* @asm 0xA6C9..0xA6DA  adx = arg0-2; if adx<=0 adx = -(arg0-2) */
    adx = (int16_t)((int16_t)arg0_bp_06 - 2);
    if (adx <= 0) adx = (int16_t)(-adx);
    /* @asm 0xA6DD..0xA6EE  ady = arg1-2; if ady<=0 ady = -(arg1-2) */
    ady = (int16_t)((int16_t)arg1_bp_08 - 2);
    if (ady <= 0) ady = (int16_t)(-ady);

    /* @asm 0xA6F1..0xA723  if tile out of bounds, OR the (adx,ady,power) radius
     *      predicate fails -> mark 0x10 (unusable) and return early. */
    if (overlay_call_037F_000A(px, py) == 0 ||
        overlay_call_037F_003C(adx, ady, func_008720()) == 0) {
        (void)func_008720();   /* @0xA704 CALL 0x8720 (current-power id) */
        flags |= 0x10;
        return flags;
    }

    /* @asm 0xA724..0xA74C  if ctx->owner(+0x1A) < 4 and the tile's owner-mask
     *      (037F:02F8) lacks bit (0x10<<owner) -> mark 0x10 and return. */
    if ((uint8_t)ctx_local[0x1A] < 4) {
        int mask = overlay_call_037F_02F8(px, py) & 0xFF;
        if ((mask & (0x10 << (uint8_t)ctx_local[0x1A])) == 0) {
            flags |= 0x10;
            return flags;
        }
    }

    /* @asm 0xA74E..0xA763  owner_here = 037F:0314(px,py); if <0 skip to block I. */
    owner_here = (int16_t)overlay_call_037F_0314(px, py);
    if (owner_here >= 0 &&
        /* @asm 0xA766 owner_here != ctx->owner */
        owner_here != (uint8_t)ctx_local[0x1A] &&
        /* @asm 0xA776 03E4:0074(px,py) (water?) == 0 */
        overlay_call_03E4_0074(px, py) == 0 &&
        /* @asm 0xA78B owner_here < 4 */
        owner_here < 4) {
        /* @asm 0xA794..0xA817  scan units on tile (px,py): for a soldier-class
         *      (UnitRecord +8 == 5 or 6) that also passes the class/profession
         *      gate, mark 0x80 (enemy unit) and tag it via 0427:0992. */
        int idx = overlay_call_0427_005C(px, py);
        while (idx >= 0) {
            uint8_t cls    = (uint8_t)DG8(0x3146 + (unsigned)idx * 0x1C);  /* +2 */
            int gate_ok = 0;
            if ((uint8_t)DG8(0x5236 + (unsigned)cls * 14) > 1) {
                gate_ok = 1;                                /* @asm 0xA7C1 ja 0xA7DF */
            } else if (cls == 2) {
                uint8_t f3 = (uint8_t)(DG8(0x3147 + (unsigned)idx * 0x1C) & 0x0F); /* +3 */
                if (f3 < 4 && DG8(0x543F + (unsigned)f3 * 0x34) == 0)
                    gate_ok = 1;
            }
            if (gate_ok) {
                uint8_t f8 = (uint8_t)DG8(0x314C + (unsigned)idx * 0x1C);  /* +8 */
                if (f8 == 5 || f8 == 6) {
                    flags |= 0x80;
                    overlay_call_0427_0992(/* idx, ctx->owner */);
                }
            }
            idx = overlay_call_0427_004A((uint16_t)idx);    /* next unit on tile */
        }
    }

    /* @asm 0xA819..0xA82F  if tile is "blocked" (037F:0598) -> mark 0x02. */
    if (overlay_call_037F_0598(px, py) != 0)
        flags |= 0x02;

    /* @asm 0xA82F..0xA859  if (px,py) matches a wonder/landmark in table_54EC
     *      (stride 0x12, count 0x539A) -> mark 0x04. */
    for (j = 0; j < (int16_t)DG16(0x539A); j++) {
        if (DG8(0x54EC + (unsigned)j * 0x12) == (uint8_t)px &&
            DG8(0x54ED + (unsigned)j * 0x12) == (uint8_t)py) {
            flags |= 0x04;
        }
    }

    /* @asm 0xA85B..0xA927  scan all OTHER colonies (table 0x5D46, stride 0xCA,
     *      count 0x539E; skip the current colony index at 0x8DC6):
     *        - exact (px,py) under a colony centre  -> mark 0x20;
     *        - within +/-2 of a colony AND its claimed tile (func_008892 +
     *          per-colony ring table 0x5DB6) is owned -> mark 0x40.
     * The asm reaches the |abs(dx)|<=2 test via two entry points (0xA864/0xA875)
     * that compute (px-cx) or (cx-px); both reduce to abs(cx-px)<=2. */
    for (j = 0; j < (int16_t)DG16(0x539E); j++) {
        int16_t cx, cy;
        if (j == (int16_t)DG16(0x8DC6))                     /* @asm 0xA8ED skip self */
            continue;
        cx = (int16_t)(uint8_t)DG8(0x5D46 + (unsigned)j * 0xCA);   /* colony[j].map_x */
        cy = (int16_t)(uint8_t)DG8(0x5D47 + (unsigned)j * 0xCA);   /* colony[j].map_y */
        if (cx == (uint8_t)px && cy == (uint8_t)py)         /* @asm 0xA8F5 */
            flags |= 0x20;
        {
        int16_t ddx = (int16_t)(cx - px);  if (ddx < 0) ddx = (int16_t)(-ddx);
        int16_t ddy = (int16_t)(cy - py);  if (ddy < 0) ddy = (int16_t)(-ddy);
        if (ddx <= 2 && ddy <= 2) {
            /* @asm 0xA8A2..0xA8C5  resolve the tile in colony[j]'s local frame */
            int16_t nx = (int16_t)((uint8_t)ctx_local[0] - cx + (int16_t)arg0_bp_06);
            int16_t ny = (int16_t)((uint8_t)ctx_local[1] - cy + (int16_t)arg1_bp_08);
            int r = (int16_t)func_008892((uint16_t)nx, (uint16_t)ny);
            if (r >= 0 &&
                (int8_t)DG8(0x5DB6 + (unsigned)(uint16_t)r + (unsigned)j * 0xCA) >= 0)
                flags |= 0x40;
        }
        }
    }

    /* @asm 0xA928..0xA934  if this is the colony centre tile (adx==0 && ady==0)
     *      -> mark 0x08. */
    if (adx == 0 && ady == 0)
        flags |= 0x08;

    return flags;
}

/* @asm        0x00A93E..0x00A994  (86 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00A93E_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 4
 * @args_seen  []
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x00A6A2
 * @inferred_role  lazily fill the 5x5 byte grid at 0x8DF0 with func_00A6A2(row,col); latch flag 0x34C
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_00A93E_logic_sz_86(void)
{
    /* @asm 0x00A943 cmp byte[0x34c],0; jne 0xa98c (already initialised: done).
     *      0x00A94A mov [bp-4],0 (row=0); outer test 0x00A97F: cmp [bp-4],5;
     *      jge 0xa98c; mov [bp-2],0 (col=0); inner test 0x00A955: cmp [bp-2],5;
     *      jge 0xa97c (row++); body 0x00A95B: push [bp-4](row); push [bp-2](col);
     *      call 0xa6a2 (al=func_00A6A2(row,col)); si=[bp-2](col); cx=si;
     *      shl si,2; add si,cx (si=col*5); bx=[bp-4](row);
     *      mov byte[bx+si-0x7210],al (grid_8DF0[row + col*5] = result);
     *      0x00A952 inc [bp-2] (col++).  0x00A98C mov byte[0x34c],1 (latch done).
     * One-shot initialiser: when the latch at 0x034C is clear, fills the 5x5 byte
     * grid based at 0x8DF0 (-0x7210), storing func_00A6A2(row,col) at index
     * (row + col*5) for row,col in 0..4, then sets 0x034C=1 so it runs once.
     * func_00A6A2 is a sibling helper. */
    if (DG8(0x034C) == 0) {
        int row, col;
        for (row = 0; row < 5; row++)
            for (col = 0; col < 5; col++)
                DG8(0x8DF0 + (unsigned)row + (unsigned)col * 5) =
                    (uint8_t)func_00A6A2((uint16_t)row, (uint16_t)col);  /* func_00A6A2 */
    }
    DG8(0x034C) = 1;                          /* latch: initialised */
    return 0;
}

/* @asm        0x00A994..0x00AB2D  (410 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00A994_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 0x10
 * @args_seen  []
 * @lcalls     10
 * @near_calls 3
 * @callers    0
 * @touches_8542 True
 *
 * LCALL targets:
 *   - 0x037F:0x02A0 (begin frame)   0x037F:0x000A (in-bounds)  0x181F:0x0D84 (resolve)
 *   - 0x05DC:0x006A (range scale)   0x03E4:0x0074 (water?)     0x037F:0x0314 (owner)
 *   - 0x05B3:0x0004 (relation bits) 0x0981:0x0000 (power flag) 0x037F:0x03E4 (claim?)
 *   - 0x037F:0x0228 (commit work assignment)
 *
 * Near CALL targets:
 *   - 0x00A93E  (lazy-fill the 5x5 base grid)
 *   - 0x008956  (tile->good id)
 *   - 0x0088D0  (tile occupied by friendly unit?)
 * @inferred_role COLONY_TOUCHED — recompute the 5x5 colony work-tile candidacy
 *                grids (0x8D9E and 0x8D84), then commit (037F:0228) each usable
 *                tile that survives the ownership/terrain/relation gauntlet.
 * @status     BYTE_VERIFIED 2026-06-09 (full body decompiled from VICEROY.EXE)
 * @note   Auto-tracer reported 293 bytes ending 0x00AAB9 (also the nominal file
 *         range); the TRUE function is 0xA994..0xAB2D (410 bytes per functions.json,
 *         single ENTER/leave-retf @0xAB2C) — the inner-loop tail (0xAAB9..0xAB2D)
 *         was truncated and is decompiled here.  Two overlay LCALLs (05B3:0004,
 *         0981:0000) declared file-locally above.
 */
int func_00A994_colony_sz_293(void)
{
    /* Loop nest (asm): outer col=[bp-0xE] 0..4, inner row=[bp-0xC] 0..4.
     * For each cell: result[bp-6] starts -1; px=ctx_map_x+row-2, py=ctx_map_y+col-2.
     * A chain of predicates can either set result (a real good id) or force it to
     * -1; the result is then written to grids 0x8D9E and 0x8D84 at index row*5+col,
     * and (when the cell remains valid and its base grid 0x8DF0 slot is non-zero
     * and the tile passes the owner/claim checks) the work assignment is committed
     * via overlay 037F:0228. */
    unsigned char near *ctx_local = (unsigned char near *)ctx;
    int frame;                                              /* [bp-8] */
    int col, row;

    /* @asm 0xA998..0xA9AD  frame = 037F:02A0(ctx_map_x, ctx_map_y) */
    frame = overlay_call_037F_02A0((uint16_t)ctx_local[0], (uint16_t)ctx_local[1]);
    /* @asm 0xA9B1  lazily fill the 5x5 base grid (0x8DF0) */
    func_00A93E();

    for (col = 0; col < 5; col++) {                         /* [bp-0xE] outer */
        for (row = 0; row < 5; row++) {                    /* [bp-0xC] inner */
            int16_t result = -1;                            /* [bp-6] */
            int16_t px = (int16_t)((uint8_t)ctx_local[0] + row - 2);  /* [bp-2] */
            int16_t py = (int16_t)((uint8_t)ctx_local[1] + col - 2);  /* [bp-4] */
            unsigned idx = (unsigned)row * 5 + (unsigned)col;        /* row*5+col */

            /* @asm 0xA9EA..0xAA2C  if in bounds, resolvable (181F:0D84) and within
             *      the scaled range, take the good byte from *(0x8D4A)+2. */
            if (overlay_call_037F_000A(px, py) != 0) {
                int resolved = overlay_call_181F_0D84((uint16_t)px, (uint16_t)py, -1, (uint16_t)frame);
                if (resolved >= 0) {
                    int scaled = overlay_call_05DC_006A(DG16(0x8D52));
                    if ((int16_t)DG16(0x8DB8) <= scaled) {
                        uint8_t near *p = (uint8_t near *)DG_PTR(DG16(0x8D4A));
                        result = (int16_t)p[2];
                    }
                }
            }

            /* @asm 0xAA2D..0xAA42  if func_008956(row,col) >= 0 -> invalidate. */
            if ((int8_t)func_008956((uint16_t)row, (uint16_t)col) >= 0)
                result = -1;
            /* @asm 0xAA43..0xAA59  if tile is water (03E4:0074) -> invalidate. */
            if (overlay_call_03E4_0074(px, py) != 0)
                result = -1;
            /* @asm 0xAA5A..0xAA6F  if friendly unit occupies (func_0088D0) -> invalidate. */
            if (func_0088D0((uint16_t)row, (uint16_t)col) != 0)
                result = -1;
            /* @asm 0xAA70..0xAA93  if still valid but relation bits (05B3:0004)
             *      lack 0x20 -> invalidate. */
            if (result >= 0) {
                int rel = overlay_call_05B3_0004((uint16_t)ctx_local[0x1A], (uint16_t)result);
                if ((rel & 0x20) == 0)
                    result = -1;
            }
            /* @asm 0xAA94..0xAAB0  if power-flag (0981:0000(owner,2)) set -> invalidate. */
            if (overlay_call_0981_0000((uint16_t)ctx_local[0x1A], 2) != 0)
                result = -1;

            /* @asm 0xAAB1..0xAAC8  store result into both grids at index row*5+col. */
            DG8(0x8D9E + idx) = (uint8_t)result;
            DG8(0x8D84 + idx) = (uint8_t)result;

            /* @asm 0xAAC9..0xAB17  commit phase, only for surviving cells whose
             *      base-grid (0x8DF0) slot is ZERO (@asm 0xAAD2 je continues) and
             *      that pass the owner (037F:0314) / claim (037F:03E4) overlays;
             *      otherwise fall through to the next cell. */
            if (result >= 0 &&
                DG8(0x8DF0 + idx) == 0 &&
                overlay_call_037F_0314(px, py) >= 0 &&
                overlay_call_037F_03E4(px, py) >= 0) {
                overlay_call_037F_0228(px, py, result);  /* commit work tile */
            }
        }
    }
    return 0;
}

