/* ============================================================================
 * load_image_00E454_00FAA9.c -- load_image functions in file range 0x00E454..0x00FAA9
 * Auto-generated by tools/full_pipeline.py for VICEROY.
 *
 * 30 functions in this file. Each carries a citation block plus
 * an auto-traced control-flow body.  Functions marked SKELETON have body
 * content derived from control-flow but their semantics still need hand-port.
 * ============================================================================ */
#include "viceroy.h"
#include "dgroup.h"
#include "overlay_externs.h"

/* @asm        0x00E454..0x00E46B  (23 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00E454_normalize_far_pointer.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  normalize_far_pointer (segment += offset>>4, offset &= 0xF)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
uint32_t func_00E454_logic_sz_23(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x00E457 mov ax,[bp+6] (offset); 0x00E45A mov dx,[bp+8] (segment);
     *      0x00E45D mov bx,ax; 0x00E45F shr bx,4; 0x00E462 add dx,bx;
     *      0x00E464 and ax,0xF; leave; retf 4  -> returns the normalised far
     *      pointer in DX:AX.
     * Canonical real-mode far-pointer normalisation: fold the high 12 bits of
     * the offset into the segment (segment += offset>>4) and reduce the offset
     * to its low nibble (offset &= 0xF).  Returns segment:offset as a dword
     * (DX=segment, AX=offset). */
    uint16_t offset  = arg0_bp_06;
    uint16_t segment = arg1_bp_08;
    segment += (uint16_t)(offset >> 4);
    offset  &= 0x000F;
    return ((uint32_t)segment << 16) | offset;
}

/* @asm        0x00E46C..0x00E49C  (48 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00E46C_unknown.asm
 * @pattern    WRAPPER_LCALL
 * @prologue   ENTER 2
 * @args_seen  []
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x109A:0x000A
 * @inferred_role  WRAPPER_LCALL (48 bytes). 0x109A:0x000A
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00E46C_op_sz_48(void)
{
    /* @auto: wrapper forwards to LCALL 0x109A:0x000A. */
    return overlay_call_109A_000A();
}

/* @asm        0x00E4C6..0x00E4D2  (12 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00E4C6_read_far_dword_via_267A.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   OTHER
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00E4C6_read_far_dword_via_267A(void)
{
    /* @asm 0x00E4C6 les bx,[0x267A]; ax=es:[bx]; dx=es:[bx+2] — reads the far
     * dword through the redirectable pointer at DGROUP:0x267A.  The init image
     * sets that pointer to 0040:006C (bytes 6C 00 40 00 @file 0x1D9A0+0x267A),
     * i.e. the BIOS 18.2 Hz tick count: this entry (0x0C0C:0x0006) IS the tick
     * read.  Modern model: platform/timer.c synthetic tick (deterministic). */
    extern uint32_t viceroy_bios_ticks(void);
    return (int)viceroy_bios_ticks();
}

/* @asm        0x00E508..0x00E51C  (20 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00E508_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PIT channel-0 reload (set system-timer divisor)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_00E508_logic_sz_20(uint16_t arg0_bp_06)
{
    /* @asm 0x00E50B cli; 0x00E50C mov al,0x36 / 0x00E50E out 0x43,al
     *      (8253/8254 command: channel 0, lo/hi byte, mode 3, binary);
     *      0x00E510 mov ax,[bp+6]; 0x00E513 out 0x40,al (divisor low byte);
     *      0x00E515 mov al,ah; 0x00E517 out 0x40,al (divisor high byte);
     *      0x00E519 sti; leave; retf.
     * Reprograms PIT channel 0 (port 0x40) with the 16-bit reload value in the
     * argument, i.e. sets the system tick rate.  Pure hardware op; no return. */
    /* cli — interrupts disabled around the reload (@asm 0x00E50B) */
    outp(0x43, 0x36);                       /* @asm 0x00E50C/0x00E50E command word */
    outp(0x40, (uint8_t)arg0_bp_06);        /* @asm 0x00E513 low  byte */
    outp(0x40, (uint8_t)(arg0_bp_06 >> 8)); /* @asm 0x00E517 high byte */
    /* sti — interrupts re-enabled (@asm 0x00E519) */
    return 0;
}

/* @asm        0x00E51C..0x00E534  (24 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00E51C_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0x66
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (24 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00E51C_logic_sz_24(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00E68A..0x00E699  (15 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00E68A_set_global_269E_byte_pair.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00E68A_set_global_269E_byte_pair(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00E6A6..0x00E6EE  (72 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00E6A6_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 2
 * @args_seen  [6, 10, 12]  (plus far-ptr seg half [bp+8] and register arg ax)
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  measure the pixel width of a counted/NUL-terminated string via a
 *                 per-glyph width table; adds inter-character spacing between glyphs
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * Args: [bp+6]:[bp+8] = far pointer to the string (ds:si); [bp+0xA] = glyph-table
 *       base index; [bp+0xC] = glyph-table segment (es); ax (register) = per-glyph
 *       inter-character spacing, saved to [bp-4].  Each glyph's advance width is
 *       the byte at table_seg:[(glyph-1) + base + 2]; spacing is added after every
 *       glyph except the last.  Returns the accumulated width (retf 8 pops the four
 *       stack words; the prototype is widened to model the far ptr + register arg).
 */
int func_00E6A6_logic_sz_72(void far *str /*bp+6:bp+8*/, uint16_t tbl_base_bp_0A,
                            uint16_t tbl_seg_bp_0C, uint16_t spacing /*ax*/)
{
    /* @asm 0x00E6AD lds si,[bp+6] (ds:si = string); 0x00E6B0 mov [bp-2],0 (total=0);
     *      0x00E6B5 cmp byte [si],0; je 0xE6E0 (empty string).
     *      Loop @0x00E6BD: mov es,[bp+0xC]; al=*si; cwde; di=al; dec di; inc si;
     *      0x00E6C4 add di,[bp+0xA] (di = glyph-1 + base); mov cl,es:[di+2]; sub ch,ch
     *      (cx = width byte); 0x00E6CD or cx,cx; jle 0xE6D8 (skip non-positive);
     *      0x00E6D1 cmp byte [si],ch(=0); je 0xE6D8 (last glyph -> no spacing);
     *      0x00E6D5 add cx,[bp-4] (+ spacing).  0x00E6D8 add [bp-2],cx (total += width);
     *      0x00E6DB cmp byte [si],0; jne 0xE6BD (next glyph).
     *      0x00E6E0 mov ax,0x1B5A; mov ds,ax (restore DGROUP); mov ax,[bp-2];
     *      pop si; pop di; leave; retf 8. */
    const uint8_t far *s = (const uint8_t far *)str;
    uint16_t total = 0;
    while (*s != 0) {
        uint8_t glyph = *s++;
        uint8_t far *tbl = (uint8_t far *)
            (((uint32_t)tbl_seg_bp_0C << 16) | (uint16_t)((glyph - 1) + tbl_base_bp_0A));
        int16_t width = (int16_t)(uint8_t)tbl[2];   /* es:[di+2], zero-extended */
        if (width > 0 && *s != 0)                   /* spacing between glyphs only */
            width += (int16_t)spacing;
        total += (uint16_t)width;                   /* @asm 0x00E6D8: always added */
    }
    return total;
}

/* @asm        0x00E6EE..0x00E702  (20 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00E6EE_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  wait_for_vertical_retrace (poll CGA status port 0x3DA bit 3)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_00E6EE_logic_sz_20(void)
{
    /* @asm 0x00E6F1 mov dx,0x3DA; 0x00E6F4 mov ah,8;
     *      0x00E6F6 in al,dx / 0x00E6F7 and al,ah / 0x00E6F9 jne 0x00E6F6
     *        -> spin while the vertical-retrace bit (0x08) is SET (wait for it
     *           to fall, i.e. wait out any retrace already in progress);
     *      0x00E6FB in al,dx / 0x00E6FC and al,ah / 0x00E6FE je 0x00E6FB
     *        -> then spin until the bit goes SET (wait for the next retrace to
     *           begin).  Classic CGA vsync-sync.  Pure hardware poll; no return. */
    while (inp(0x3DA) & 0x08) { }   /* @asm 0x00E6F6..0x00E6F9 wait for retrace end   */
    while (!(inp(0x3DA) & 0x08)) { }/* @asm 0x00E6FB..0x00E6FE wait for retrace start */
    return 0;
}

/* @asm        0x00E702..0x00E769  (103 bytes)  region=load_image
 * @asm_file   re_work/disasm/func_00E702.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 4  ; then push dx,ax,di,si (register args + saves)
 * @args_seen  []  (stack arg [bp+6]:[bp+8] far ptr) PLUS register args ax, dx
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  upload a VGA DAC palette block (DAC ports 0x3C8/0x3C9), in
 *                 retrace-synced bursts capped by [0x806]; sets busy flag 0x808
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: auto-banner "21 bytes" truncated at the prologue; real body 0xE702..0xE769
 * (103 B, `retf 4`; 0xE769 NOP pad, next func 0xE76A).  Args: ax = first DAC color
 * index, dx = color count, [bp+6]:[bp+8] = far ptr to packed RGB (3 bytes/color).
 * Writes color index to 0x3C8 then streams `count*3` component bytes to 0x3C9 in
 * bursts of at most [0x806] bytes, each burst preceded by a vertical-retrace sync
 * (port 0x3DA bit 3) with interrupts disabled during the burst.  DGROUP word 0x808
 * is set to 1 for the duration (palette-busy) and cleared to 0 on exit.  The port
 * I/O is a pure platform op, modelled with inp()/outp() per project convention
 * (cf. func_00E6EE).  `retf 4` pops the one stack far-ptr; no return value. */
int func_00E702_logic_sz_21(const void far *rgb /*bp+6:bp+8*/,
                            uint16_t first_index /*ax*/, uint16_t count /*dx*/)
{
    /* @asm 0x00E70A cx=ax; ax=ax*3; mov [bp-2],ax (start byte offset = first*3);
     *      0x00E713 ax=dx; dx=dx*3; mov [bp-4],dx (total bytes = count*3).
     *      0x00E71C mov [0x808],1 (busy); 0x00E722 bx=[0x806] (burst cap);
     *      0x00E726 di=[bp-4] (bytes remaining); push ds; lds si,[bp+6];
     *      0x00E72D add si,[bp-2] (si -> first color's bytes); 0x00E730 dx=0x3C8;
     *      ax=[bp-8](first_index); out dx,al (DAC write index); inc dx (0x3C9).
     *      Burst @0x00E738 push dx; vsync wait on 0x3DA bit 8 (wait end, then start);
     *      0x00E748 cli; pop dx(=0x3C9); cx=di; cmp cx,bx; jbe 0xE752 else cx=bx
     *      (burst = min(remaining, [0x806])); push cx; 0x00E753 outsb / loop
     *      (stream cx bytes ds:[si]->0x3C9); 0x00E756 sti; pop cx; sub di,cx;
     *      jne 0xE738 (more bursts).  0x00E75C pop ds; mov [0x808],0 (clear busy);
     *      pop si; pop di; leave; retf 4. */
    const uint8_t far *src = (const uint8_t far *)rgb + (uint16_t)(first_index * 3);
    uint16_t remaining = (uint16_t)(count * 3);
    uint16_t burst_cap = DG16(0x806);

    DG16(0x808) = 1;                 /* @asm 0x00E71C palette-busy flag */
    /* @asm 0x00E730 outp(0x3C8, (uint8_t)first_index)  -- DAC write index */
    outp(0x3C8, (uint8_t)first_index);
    while (remaining != 0) {
        uint16_t burst = (remaining <= burst_cap) ? remaining : burst_cap;
        uint16_t i;
        /* @asm 0x00E738..0x00E746 vertical-retrace sync on port 0x3DA bit 3 */
        while (inp(0x3DA) & 0x08) { }            /* wait for any retrace to end   */
        while (!(inp(0x3DA) & 0x08)) { }         /* wait for next retrace to start */
        /* @asm 0x00E748 cli; 0x00E753 outsb x burst to 0x3C9; 0x00E756 sti */
        for (i = 0; i < burst; i++)
            outp(0x3C9, *src++);                 /* stream component bytes to DAC data */
        remaining -= burst;                      /* @asm 0x00E758 sub di,cx */
    }
    DG16(0x808) = 0;                 /* @asm 0x00E75D clear busy flag */
    return 0;
}

/* @asm        0x00E76A..0x00E963  (505 bytes)  region=load_image
 * @asm_file   re_work/disasm/func_00E76A.asm
 * @pattern    VIDEO_SPRITE_BLIT
 * @prologue   ENTER 0x28  ; then push dx,bx,ax,di,si (register args + saves)
 * @args_seen  []  (register args ax,dx,bx PLUS stack glyph-table far ptr [bp+8]:[bp+0xa])
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  opaque RLE-sprite rasterizer into a caller-supplied far framebuffer
 * @status     PLATFORM_LAYER / SDL milestone-3 swap-point (VGA sprite blit; honest stub)
 *
 * NOTE: auto-banner "49 bytes / 0x00E79B" was truncated at the JNS at the mirror-flag
 * setup; the true body runs 0x00E76A..0x00E962 (505 B, `retf 6`; 0x00E963 NOP pad,
 * next func 0x00E964 per functions.json).  Register args: ax = signed glyph index
 * (sign bit selects the horizontal mirror step ±1 stored at [bp-0x10], low 15 bits =
 * record index, stride 12 into the glyph table at [bp+8]:[bp+0xa], record base +0x36),
 * dx = far ptr to the destination descriptor {+2 = dst_stride, +4:+6 = dst far base},
 * bx = far ptr to a clip record {[bx] = clip_w, [bx+2] = clip_h}.  The glyph record's
 * +0/+2 = packed-RLE data far ptr, +8/+0xA = glyph w/h.  The body clips the glyph to
 * the clip rect, then walks the run-length stream (control bytes 0xFF = row/blit end,
 * 0xFE = run, 0xFD = transparent run) writing opaque pixels with `mov es:[bx],al` into
 * the framebuffer, advancing dst by ±dst_stride per pixel with 0x7000/0x700 segment
 * wrap at 64K.  `retf 6` pops the one stack far ptr (3 words).  No return value, no
 * DGROUP state written (all writes target the framebuffer).
 *
 * PLATFORM_LAYER: this is the VGA software rasterizer — exactly the milestone-3 SDL
 * swap-point.  The pixel raster is the hardware/video path, so it is kept as an
 * honest stub (no framebuffer is owned by the rules layer); the cited @asm above is
 * the faithful description of the byte-exact decoder for the eventual SDL port. */
int func_00E76A_logic_sz_505(void)
{
    return 0;  /* TODO: SDL — opaque RLE sprite blit to the VGA framebuffer (es:[bx]) */
}

/* @asm        0x00E867..0x00E876  (15 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00E867_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0xe74
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (15 bytes). no LCALLs
 * @status     SHADOWED (interior of func_00E76A; auto-segmentation artifact, not a standalone function)
 */
int func_00E867_logic_sz_15(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00E964..0x00EC31  (717 bytes)  region=load_image
 * @asm_file   re_work/disasm/func_00E964.asm
 * @pattern    VIDEO_SPRITE_BLIT
 * @prologue   ENTER 0x16e  ; then push dx,bx,ax,di,si (register args + saves)
 * @args_seen  []  (register args ax,dx,bx PLUS stack args [bp+6],[bp+8] and far ptr [bp+0xa]:[bp+0xc])
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  X-scaled opaque RLE-sprite rasterizer into a caller far framebuffer
 * @status     PLATFORM_LAYER / SDL milestone-3 swap-point (VGA sprite blit; honest stub)
 *
 * NOTE: auto-banner "54 bytes / 0x00E99A" was truncated at the JNS mirror-flag setup;
 * the true body runs 0x00E964..0x00EC2E (717 B, `retf 8`; next func 0x00EC32 per
 * functions.json).  Scaled twin of func_00E76A: identical glyph/clip/descriptor setup
 * (ax = signed glyph index + mirror flag, dx = dest-descriptor far ptr, bx = clip
 * record, glyph table [bp+0xa]:[bp+0xc]).  Additionally [bp+6] = source-X start phase
 * and [bp+8] = horizontal scale numerator: a 0x152-byte stack mask (`[bp-0x152]`) is
 * built per source column by a (phase += [bp+8]; >=0x64 -> emit, -=0x64) Bresenham
 * step (the `0x32`/`0x64` rounding at 0x00EA00) so the glyph is squeezed/expanded in X
 * before the RLE decode writes opaque pixels with `mov es:[bx],al` to the framebuffer
 * (0x7000/0x700 segment wrap at 64K).  `retf 8` pops the four stack words.  No return
 * value, no DGROUP state written.
 *
 * PLATFORM_LAYER: VGA software rasterizer (milestone-3 SDL swap-point); the scaled
 * pixel raster is the hardware/video path, kept as an honest stub with the cited @asm
 * describing the byte-exact decoder for the eventual SDL port. */
int func_00E964_logic_sz_717(void)
{
    return 0;  /* TODO: SDL — X-scaled opaque RLE sprite blit to the VGA framebuffer */
}

/* @asm        0x00EADE..0x00EAED  (15 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00EADE_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0xe74
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (15 bytes). no LCALLs
 * @status     SHADOWED (interior of func_00E964; auto-segmentation artifact, not a standalone function)
 */
int func_00EADE_logic_sz_15(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00EC32..0x00EC96  (100 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00EC32_unknown.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 10, 12]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  scale a source record's (w,h) by a percentage and write a
 *                 placed/centered bounding box into a destination struct
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * Args (stack): [bp+6]:[bp+8] = es:bx destination struct (far);
 *               [bp+0xA] = scale percent; [bp+0xC]:[bp+0xE] = ds:di source table (far).
 * Args (register): ax = record index (stride 12 in the source table); bx = anchor
 *               row; dx = anchor col.  The source record is at table + index*12 +
 *               0x36; its +8/+0xA words are the unscaled width/height.  Each is
 *               scaled with rounding ((v*scale + 50) / 100).  Destination layout:
 *               +8 = scaled width, +0xA = scaled height, +4 = dx - scaled_w/2
 *               (horizontally centred on the anchor), +6 = bx - scaled_h + 1
 *               (bottom-anchored).  `retf 0xA` pops the five stack words; the
 *               prototype is widened to model the far ptrs + register args.
 */
int func_00EC32_logic_sz_100(void far *dst /*bp+6:bp+8*/, uint16_t scale_bp_0A,
                             const void far *src_tbl /*bp+0xC:bp+0xE*/,
                             uint16_t index /*ax*/, int anchor_row /*bx*/,
                             int anchor_col /*dx*/)
{
    /* @asm 0x00EC39 lds di,[bp+0xC] (ds:di=table); les bx,[bp+6] (es:bx=dst);
     *      0x00EC3F si=ax; si=si*3; si=si*4 (si = index*12); add si,di; add si,0x36
     *      (si -> source record).  0x00EC4D ax=[si+8]; mul [bp+0xA]; add ax,0x32;
     *      cx=100; sub dx,dx; div cx (ax = (w*scale+50)/100); mov es:[bx+8],ax (scaled w).
     *      0x00EC61 dx=ax; ax=[si+0xA]; si=dx (stash scaled w); mul [bp+0xA]; add ax,0x32;
     *      sub dx,dx; div cx (ax = (h*scale+50)/100); mov es:[bx+0xA],ax (scaled h).
     *      0x00EC76 shr si,1 (scaled_w/2); sub si,[bp-4](dx_in=col); neg si
     *      (si = col - scaled_w/2); mov es:[bx+4],si.
     *      0x00EC81 sub ax,[bp-2](bx_in=row); neg ax; inc ax (ax = row - scaled_h + 1);
     *      mov es:[bx+6],ax.  0x00EC8B cx=0x1B5A; mov ds,cx (restore DGROUP);
     *      pop si; pop di; leave; retf 0xA. */
    const uint8_t far *rec = (const uint8_t far *)src_tbl + (uint16_t)(index * 12) + 0x36;
    uint16_t raw_w   = *(const uint16_t far *)(rec + 8);
    uint16_t raw_h   = *(const uint16_t far *)(rec + 0xA);
    uint16_t scaled_w = (uint16_t)(((uint32_t)raw_w * scale_bp_0A + 0x32) / 0x64);
    uint16_t scaled_h = (uint16_t)(((uint32_t)raw_h * scale_bp_0A + 0x32) / 0x64);
    uint8_t far *d = (uint8_t far *)dst;

    *(uint16_t far *)(d + 8)   = scaled_w;
    *(uint16_t far *)(d + 0xA) = scaled_h;
    *(uint16_t far *)(d + 4)   = (uint16_t)(anchor_col - (scaled_w >> 1));   /* centred X */
    *(uint16_t far *)(d + 6)   = (uint16_t)(anchor_row - scaled_h + 1);      /* bottom Y  */
    return 0;
}

/* @asm        0x00EC96..0x00EEA3  (525 bytes)  region=load_image
 * @asm_file   re_work/disasm/func_00EC96.asm
 * @pattern    VIDEO_SPRITE_BLIT
 * @prologue   ENTER 0x28  ; then push dx,bx,ax,di,si (register args + saves)
 * @args_seen  []  (register args ax,dx,bx PLUS stack glyph-table far ptr [bp+8]:[bp+0xa])
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  masked (transparent-over-0) RLE-sprite rasterizer into a far framebuffer
 * @status     PLATFORM_LAYER / SDL milestone-3 swap-point (VGA sprite blit; honest stub)
 *
 * NOTE: auto-banner "49 bytes / 0x00ECC7" was truncated at the JNS mirror-flag setup;
 * the true body runs 0x00EC96..0x00EEA0 (525 B, `retf 6`; next func 0x00EEA4 per
 * functions.json).  Masked twin of func_00E76A: byte-identical glyph/clip/descriptor
 * setup and RLE control codes, but each pixel write is gated by `cmp es:[bx],0; jne`
 * (@0x00EE0F/0x00EE48/0x00EE6C) so the glyph only paints over framebuffer bytes that
 * are still 0 (transparent overlay).  Same `mov es:[bx],al` framebuffer store with
 * ±dst_stride advance and 0x7000/0x700 segment wrap.  `retf 6` pops the one stack far
 * ptr.  No return value, no DGROUP state written.
 *
 * PLATFORM_LAYER: VGA software rasterizer (milestone-3 SDL swap-point); kept as an
 * honest stub with the cited @asm describing the byte-exact masked decoder. */
int func_00EC96_logic_sz_525(void)
{
    return 0;  /* TODO: SDL — masked RLE sprite blit to the VGA framebuffer (over 0 pixels) */
}

/* @asm        0x00ED93..0x00EDA2  (15 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00ED93_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0xe74
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (15 bytes). no LCALLs
 * @status     SHADOWED (interior of func_00EC96; auto-segmentation artifact, not a standalone function)
 */
int func_00ED93_logic_sz_15(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00EEA4..0x00F183  (735 bytes)  region=load_image
 * @asm_file   re_work/disasm/func_00EEA4.asm
 * @pattern    VIDEO_SPRITE_BLIT
 * @prologue   ENTER 0x16e  ; then push dx,bx,ax,di,si (register args + saves)
 * @args_seen  []  (register args ax,dx,bx PLUS stack args [bp+6],[bp+8] and far ptr [bp+0xa]:[bp+0xc])
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  X-scaled masked (transparent-over-0) RLE-sprite rasterizer to a far framebuffer
 * @status     PLATFORM_LAYER / SDL milestone-3 swap-point (VGA sprite blit; honest stub)
 *
 * NOTE: auto-banner "54 bytes / 0x00EEDA" was truncated at the JNS mirror-flag setup;
 * the true body runs 0x00EEA4..0x00F180 (735 B, `retf 8`; next func 0x00F184 per
 * functions.json).  Combination of func_00E964 (the [bp+8] X-scale Bresenham column
 * mask built in the `[bp-0x152]` stack buffer, 0x32/0x64 rounding at 0x00EF40) and
 * func_00EC96 (the `cmp es:[bx],0; jne` mask gate at 0x00F0CE/0x00F118/0x00F14A): a
 * horizontally-scaled glyph painted only over framebuffer 0-bytes via `mov es:[bx],al`
 * with ±dst_stride advance and 0x7000/0x700 segment wrap.  `retf 8` pops the four
 * stack words.  No return value, no DGROUP state written.
 *
 * PLATFORM_LAYER: VGA software rasterizer (milestone-3 SDL swap-point); kept as an
 * honest stub with the cited @asm describing the byte-exact scaled+masked decoder. */
int func_00EEA4_logic_sz_735(void)
{
    return 0;  /* TODO: SDL — X-scaled masked RLE sprite blit to the VGA framebuffer */
}

/* @asm        0x00F01E..0x00F02D  (15 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00F01E_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0xe74
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (15 bytes). no LCALLs
 * @status     SHADOWED (interior of func_00EEA4; auto-segmentation artifact, not a standalone function)
 */
int func_00F01E_logic_sz_15(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00F184..0x00F389  (517 bytes)  region=load_image
 * @asm_file   re_work/disasm/func_00F184.asm
 * @pattern    VIDEO_SPRITE_BLIT
 * @prologue   ENTER 0x28  ; then push dx,bx,ax,di,si (register args + saves)
 * @args_seen  []  (register args ax,dx,bx PLUS stack colour [bp+6] and far ptr [bp+8]:[bp+0xa]... )
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  solid-colour (silhouette) RLE-sprite rasterizer into a far framebuffer
 * @status     PLATFORM_LAYER / SDL milestone-3 swap-point (VGA sprite blit; honest stub)
 *
 * NOTE: auto-banner "49 bytes / 0x00F1B5" was truncated at the JNS mirror-flag setup;
 * the true body runs 0x00F184..0x00F386 (517 B, `retf 8`; next func 0x00F38A per
 * functions.json).  Silhouette twin of func_00E76A: identical glyph/clip/descriptor
 * setup and RLE control walk, but each opaque pixel is written as the fixed colour
 * byte `[bp+6]` (`mov al,[bp+6]; mov es:[bx],al` @0x00F2FF/0x00F336/0x00F356) instead
 * of the source pixel, so the glyph's RLE shape is stamped as a solid-colour mask.
 * Same ±dst_stride advance and 0x7000/0x700 segment wrap.  `retf 8` pops the four
 * stack words.  No return value, no DGROUP state written.
 *
 * PLATFORM_LAYER: VGA software rasterizer (milestone-3 SDL swap-point); kept as an
 * honest stub with the cited @asm describing the byte-exact silhouette decoder. */
int func_00F184_logic_sz_517(void)
{
    return 0;  /* TODO: SDL — solid-colour silhouette RLE sprite blit to the VGA framebuffer */
}

/* @asm        0x00F281..0x00F290  (15 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00F281_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0xe74
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (15 bytes). no LCALLs
 * @status     SHADOWED (interior of func_00F184; auto-segmentation artifact, not a standalone function)
 */
int func_00F281_logic_sz_15(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00F38A..0x00F44F  (197 bytes)  region=load_image
 * @asm_file   re_work/disasm/func_00F38A.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 0x10  ; then push ax,di,si (n in ax + saves)
 * @args_seen  [6]  (plus far ptr seg [bp+8], satellite far ptr [bp+0xA]:[bp+0xC], reg n=ax)
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  in-place insertion sort of a WORD key array carrying a parallel
 *                 BYTE satellite array (ascending by key)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: auto-banner "46 bytes" truncated at the first basic block; real body
 * 0xF38A..0xF44E (197 B, `retf 8`).  Args: [bp+6]:[bp+8] = far ptr to key[n]
 * (uint16_t), [bp+0xA]:[bp+0xC] = far ptr to sat[n] (uint8_t), ax = n (register).
 * It repeatedly scans for the first adjacent inversion key[i+1] < key[i], extracts
 * that element, closes the gap by shifting the tail down one (key[i+2..]→key[i+1..],
 * same for sat), finds the insertion point j (first key[j] >= extracted), opens a
 * gap there by shifting key[j..]/sat[j..] up one, and drops the element at j.  This
 * is a stable insertion sort.  `retf 8` pops the four stack words.  No return value.
 */
int func_00F38A_logic_sz_46(uint16_t key_off_bp_06, uint16_t key_seg_bp_08,
                            uint16_t sat_off_bp_0A, uint16_t sat_seg_bp_0C,
                            uint16_t n /*ax*/)
{
    /* @asm 0x00F391 mov [bp-0x10],0 (i=0).  Outer reload @0x00F39A: les di,[bp+6];
     *      si=i; bx=i*2; dx=n-1; cmp si,dx; jl 0xF3AC else jmp 0xF448 (done when i>=n-1).
     *      0x00F3AC ax=key[i+1] (es:[bx+di+2]); cmp ax,key[i] (es:[bx+di]); jae 0xF3B5:
     *      i++; bx+=2; [bp-0x10]=i; jmp 0xF3A5 (advance over sorted adjacents).
     *      Inversion @0x00F3BE: cx=(n-1)-i-1 (tail count); di+=bx+2 (->&key[i+1]);
     *      push si(i); push cx; ds=es; si=di+2 (->&key[i+2]); if cx!=0 rep movsw
     *      (shift key[i+2..]→key[i+1..]); pop cx; lds si,[bp+0xA]; les di,[bp+0xA];
     *      pop bx(=i); inc bx; si+=bx; di+=bx; inc si (si=&sat[i+2], di=&sat[i+1]);
     *      dl=sat[i+1] (save satellite); if cx!=0 rep movsb (shift sat down).
     *      Find j @0x00F3F1: les di,[bp+6]; si=0(j); bx=0; cx=n-1; loop while j<n-1 and
     *      key[j] < ax: 0x00F400 cmp ax,key[j]; jbe 0xF40C (stop at first key[j]>=ax);
     *      j++; bx+=2.  @0x00F40C push bx(j*2); push si(j); cx-=j; je 0xF437 (no shift):
     *      else open gap: push cx; cx<<=1; di+=bx; ds=es; di+=cx (->&key[n-1]); si=di-2;
     *      std; cx>>=1; rep movsw (shift key[j..n-2]→key[j+1..n-1]); lds si,[bp+0xA];
     *      pop cx; pop di(=j); push di; di+=si; ds->es; di+=cx (->&sat[n-1]); si=di-1;
     *      rep movsb (shift sat[j..]→sat[j+1..]); cld.
     *      @0x00F437 lds si,[bp+0xA]; pop bx(=j); sat[j]=dl; les di,[bp+6]; pop bx(=j*2);
     *      key[j]=ax; jmp 0xF39A (restart outer at same i).  @0x00F448 done: retf 8. */
    uint16_t far *key = (uint16_t far *)(((uint32_t)key_seg_bp_08 << 16) | key_off_bp_06);
    uint8_t  far *sat = (uint8_t  far *)(((uint32_t)sat_seg_bp_0C << 16) | sat_off_bp_0A);
    int i = 0;

    while (i < (int)n - 1) {
        uint16_t k;
        uint8_t  s;
        int j, t;
        if (key[i + 1] >= key[i]) {           /* @asm 0xF3B0 jae: already in order */
            i++;
            continue;
        }
        k = key[i + 1];                       /* extract the small element */
        s = sat[i + 1];
        for (t = i + 1; t <= (int)n - 2; t++) {   /* @asm 0xF3D5/0xF3EC: close gap (down) */
            key[t] = key[t + 1];
            sat[t] = sat[t + 1];
        }
        for (j = 0; j < (int)n - 1; j++)          /* @asm 0xF400: insertion point */
            if (key[j] >= k)
                break;
        for (t = (int)n - 1; t >= j + 1; t--) {   /* @asm 0xF423/0xF434: open gap (up) */
            key[t] = key[t - 1];
            sat[t] = sat[t - 1];
        }
        key[j] = k;                               /* @asm 0xF442 / 0xF43B: drop it in */
        sat[j] = s;
        /* i not advanced: restart the scan from the same position */
    }
    return 0;
}

/* @asm        0x00F450..0x00F50F  (191 bytes)  region=load_image
 * @asm_file   re_work/disasm/func_00F450.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 0x10  ; then push ax,di,si (n in ax + saves)
 * @args_seen  [6]  (plus far ptr seg [bp+8], satellite far ptr [bp+0xA]:[bp+0xC], reg n=ax)
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  in-place insertion sort of a BYTE key array carrying a parallel
 *                 BYTE satellite array (ascending by key) — byte-key twin of func_00F38A
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: auto-banner "44 bytes" truncated mid-loop; real body 0xF450..0xF50F
 * (191 B, `retf 8`; 0xF50F NOP pad, next func 0xF510).  Identical structure to
 * func_00F38A but the key array is uint8_t (byte compares, movsb shifts) instead
 * of uint16_t.  Args: [bp+6]:[bp+8] = far ptr to key[n] (uint8_t),
 * [bp+0xA]:[bp+0xC] = far ptr to sat[n] (uint8_t), ax = n (register).  Scans for
 * the first adjacent inversion key[i+1] < key[i], extracts it, closes the gap
 * (shift tail down), finds insertion point j (first key[j] >= extracted), opens a
 * gap (shift up), and drops it at j.  Stable insertion sort.  `retf 8` pops the
 * four stack words.  No return value.
 */
int func_00F450_logic_sz_44(uint16_t key_off_bp_06, uint16_t key_seg_bp_08,
                            uint16_t sat_off_bp_0A, uint16_t sat_seg_bp_0C,
                            uint16_t n /*ax*/)
{
    /* @asm 0x00F457 mov [bp-0x10],0 (i=0).  Outer reload @0x00F460: les di,[bp+6];
     *      si=i; bx=si; dx=n-1; cmp si,dx; jl 0xF470 else jmp 0xF508 (done i>=n-1).
     *      0x00F470 al=key[i+1] (es:[bx+di+1]); cmp al,key[i] (es:[bx+di]); jae 0xF479:
     *      i++; bx+=1; [bp-0x10]=i; jmp 0xF469 (advance over sorted adjacents).
     *      Inversion @0x00F482: cx=(n-1)-i-1; di+=bx+1 (->&key[i+1]); push si; push cx;
     *      ds=es; si=di+1 (->&key[i+2]); if cx!=0 rep movsb (shift key down);
     *      pop cx; lds si,[bp+0xA]; les di,[bp+0xA]; pop bx(=i); inc bx; si+=bx; di+=bx;
     *      inc si; dl=sat[i+1] (save); if cx!=0 rep movsb (shift sat down).
     *      Find j @0x00F4B5: les di,[bp+6]; si=0; bx=0; cx=n-1; loop while j<n-1 and
     *      key[j] < al: 0x00F4C4 cmp al,key[j]; jbe 0xF4D0 (stop at first key[j]>=al);
     *      j++; bx+=1.  @0x00F4D0 push bx(j); push si(j); cx-=j; je 0xF4F7 else open gap:
     *      push cx; di+=bx; ds=es; di+=cx (->&key[n-1]); si=di-1; std; rep movsb
     *      (shift key[j..n-2]→key[j+1..n-1]); lds si,[bp+0xA]; pop cx; pop di(=j);
     *      push di; di+=si; ds->es; di+=cx (->&sat[n-1]); si=di-1; rep movsb (shift sat);
     *      cld.  @0x00F4F7 lds si,[bp+0xA]; pop bx(=j); sat[j]=dl; les di,[bp+6];
     *      pop bx(=j); key[j]=al; jmp 0xF460 (restart at same i).  @0x00F508 retf 8. */
    uint8_t far *key = (uint8_t far *)(((uint32_t)key_seg_bp_08 << 16) | key_off_bp_06);
    uint8_t far *sat = (uint8_t far *)(((uint32_t)sat_seg_bp_0C << 16) | sat_off_bp_0A);
    int i = 0;

    while (i < (int)n - 1) {
        uint8_t k, s;
        int j, t;
        if (key[i + 1] >= key[i]) {           /* @asm 0xF474 jae: already in order */
            i++;
            continue;
        }
        k = key[i + 1];                       /* extract the small element */
        s = sat[i + 1];
        for (t = i + 1; t <= (int)n - 2; t++) {   /* @asm 0xF499/0xF4B0: close gap (down) */
            key[t] = key[t + 1];
            sat[t] = sat[t + 1];
        }
        for (j = 0; j < (int)n - 1; j++)          /* @asm 0xF4C4: insertion point */
            if (key[j] >= k)
                break;
        for (t = (int)n - 1; t >= j + 1; t--) {   /* @asm 0xF4E3/0xF4F4: open gap (up) */
            key[t] = key[t - 1];
            sat[t] = sat[t - 1];
        }
        key[j] = k;                               /* @asm 0xF502 / 0xF4FB: drop it in */
        sat[j] = s;
        /* i not advanced: restart the scan from the same position */
    }
    return 0;
}

/* @asm        0x00F510..0x00F52C  (28 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00F510_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  set_video_mode (record mode @0x83AA; optionally call BIOS int 10h)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_00F510_logic_sz_28(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x00F514 mov ax,[bp+6]; 0x00F517 mov [0x83AA],ax  -> record the
     *      requested video mode in the DGROUP word 0x83AA (mode-shadow global).
     *      0x00F51D cmp word [bp+8],0; 0x00F521 je 0x00F52A: only when the second
     *      argument is non-zero does it actually program the adapter:
     *      0x00F523 mov ax,[bp+6]; 0x00F526 xor ah,ah; 0x00F528 int 0x10
     *      (BIOS video, AH=0 set-mode, AL=mode).  leave; retf.
     * The C-visible effect is the 0x83AA store; the int 0x10 is a pure platform
     * op (BIOS set video mode) kept as an @asm-cited comment per project
     * convention (cf. func_077ADE).  No meaningful return value. */
    DG16(0x83AA) = arg0_bp_06;     /* @asm 0x00F517 record mode */
    if (arg1_bp_08 != 0) {                      /* @asm 0x00F51D / 0x00F521 */
        /* @asm 0x00F528 int 0x10  AH=0 (set video mode), AL = (uint8_t)arg0 */
        /* set_video_mode((uint8_t)arg0_bp_06); */
    }
    return 0;
}

/* @asm        0x00F52C..0x00F5BF  (147 bytes)  region=load_image
 * @asm_file   re_work/disasm/func_00F52C.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 4
 * @args_seen  [6, 12]  (really 7 stack params: [bp+6..bp+0x14])
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  blit a rectangular sprite from a source bitmap to the 0xA000
 *                 VGA framebuffer (320-wide), row by row, with src segment wrap
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: auto-banner "35 bytes" truncated at the address setup; real body
 * 0xF52C..0xF5BE (147 B, `retf`).  Args:
 *   [bp+6]:[bp+8] = far ptr to a source descriptor {+2 = src_stride (bytes/row),
 *                   +4 = src_offset_base, +6 = src_segment_base};
 *   [bp+0xA] = extra source byte offset;  [bp+0xC] = source row index;
 *   [bp+0xE] = destination X (byte column);  [bp+0x10] = destination Y (row);
 *   [bp+0x12] = copy width in bytes;  [bp+0x14] = height in rows.
 * The source far address = base_seg:base_off normalized for (row*src_stride +
 * extra_off), so wide sheets crossing 64K are addressed correctly.  Destination
 * = 0xA000:([bp+0xE] + 320*[bp+0x10]).  Per row it copies `width` bytes (as
 * words + a trailing byte when width is odd), advancing src by src_stride-width
 * and dst by 320-width.  The even-width path also wraps the source segment when
 * the source offset passes 0x8000.  No return value (caller pops args). */
/* Prototype widened to the seven stack params the body actually consumes
 * ([bp+6..bp+0x14]); the auto-banner only spotted [bp+6] and [bp+0xC]. */
int func_00F52C_logic_sz_35(uint16_t src_desc_off_bp_06, uint16_t src_desc_seg_bp_08,
                            uint16_t extra_off_bp_0A, uint16_t row_idx_bp_0C,
                            uint16_t dst_x_bp_0E, uint16_t dst_y_bp_10,
                            uint16_t width_bp_12, uint16_t height_bp_14)
{
    /* @asm 0x00F534 les di,[bp+6]; bx=es:[di+2](src_stride); si=es:[di+4](src_off);
     *      cx=es:[di+6](src_seg).  0x00F543 ax=[bp+0xC]; mul bx (row*src_stride);
     *      0x00F548 shl dx,0xC; add cx,dx (carry high word into seg<<12);
     *      0x00F54D dx=ax; and dx,0xFFF0; shr dx,4; add cx,dx (seg += offset>>4);
     *      0x00F557 and ax,0xF; add si,ax; add si,[bp+0xA] (si = src offset).
     *      0x00F55F es=0xA000; 0x00F564 ax=0x140(320); mul [bp+0x10]; di=[bp+0xE]+ax
     *      (dst VGA offset).  0x00F56F dx=[bp+0x12](width); bx-=dx (src row leftover);
     *      ax=[bp+0x14](height); push bp; bp=0x140-dx (dst row leftover); ds=cx.
     *      0x00F57F or ax,ax; je 0xF5B8 (no rows).  0x00F586 shr dx,1 (words=width/2);
     *      jae 0xF59D (even): odd path @0xF58A loop ax rows: if dx!=0 {cx=dx; rep movsw};
     *      movsb; add si,bx; add di,bp; dec ax; jne.  Even path @0xF59D: if dx==0 done;
     *      loop ax rows: cx=dx; rep movsw; add si,bx; jns else {si-=0x8000; ds+=0x800}
     *      (src seg wrap); add di,bp; dec ax; jne.  0xF5B8 pop bp; restore; retf.
     * Note: each row's copy advances si/di by `width`; the explicit src_stride/0x140
     * advances below fold the in-copy advance + the bx/bp leftovers into one step. */
    const uint8_t far *desc =
        (const uint8_t far *)(((uint32_t)src_desc_seg_bp_08 << 16) | (uint16_t)src_desc_off_bp_06);
    uint16_t src_stride = *(const uint16_t far *)(desc + 2);
    uint16_t src_off    = *(const uint16_t far *)(desc + 4);
    uint16_t src_seg    = *(const uint16_t far *)(desc + 6);

    uint16_t row_idx   = row_idx_bp_0C;
    uint16_t extra_off = extra_off_bp_0A;
    uint16_t dst_x     = dst_x_bp_0E;
    uint16_t dst_y     = dst_y_bp_10;
    uint16_t width     = width_bp_12;
    uint16_t height    = height_bp_14;

    /* normalize the source far address for row*src_stride + extra_off */
    {
        uint32_t prod = (uint32_t)row_idx * src_stride;     /* dx:ax */
        src_seg += (uint16_t)((prod >> 16) << 12);          /* shl dx,0xC */
        src_seg += (uint16_t)(((uint16_t)prod & 0xFFF0) >> 4);
        src_off += (uint16_t)((uint16_t)prod & 0x000F) + extra_off;
    }

    {
        /* per-row pointer advance = (in-copy `width`) + (asm leftovers bx / bp):
         *   src: width + (src_stride - width) = src_stride
         *   dst: width + (0x140    - width)   = 0x140                              */
        int odd          = (int)(width & 1);
        uint8_t far *dst = (uint8_t far *)(((uint32_t)0xA000u << 16)
                                           | (uint16_t)(dst_x + (uint16_t)(0x140 * dst_y)));
        const uint8_t far *src =
            (const uint8_t far *)(((uint32_t)src_seg << 16) | src_off);
        uint16_t r;

        if (height == 0)
            return 0;
        /* The odd path (@0xF58A) copies words+1 byte = `width` bytes; the even path
         * (@0xF59D) returns early when width<2 (words==0) and otherwise copies `width`
         * bytes per row.  Both reduce to a `width`-byte row copy, so a single loop
         * (advancing by the full src_stride / 0x140 strides) reproduces either. */
        if (odd || width >= 2) {
            for (r = 0; r < height; r++) {
                uint16_t b;
                for (b = 0; b < width; b++)
                    dst[b] = src[b];
                src += src_stride;          /* @asm in-copy advance + bx leftover */
                dst += 0x140;               /* @asm in-copy advance + bp leftover */
            }
        }
    }
    return 0;
}

/* @asm        0x00F5E6..0x00F6CF  (233 bytes)  region=load_image
 * @asm_file   re_work/disasm/func_00F5E6.asm
 * @pattern    PLATFORM_TIMING
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10]  (plus the near sub-helpers 0x00F69A/0x00F6CF folded in)
 * @lcalls     0
 * @near_calls 1  (0x00F69A, which in turn calls 0x00F6CF)
 * @callers    0
 * @touches_8542 False
 * @inferred_role  busy-wait micro-delay calibrated to the CPU via a CGA-retrace tick
 * @status     PLATFORM_LAYER / SDL milestone-3 swap-point (CGA retrace + spin loop; honest stub)
 *
 * NOTE: auto-banner "68 bytes / 0x00F62A" was truncated at the first JCXZ; the true
 * body runs 0x00F5E6..0x00F6CE (233 B incl. the near sub-helpers 0x00F69A and the
 * 0x00F6CF retrace-tick measurer, `retf`; next func 0x00F6D0-region per
 * functions.json end=0xF6CF).  This is a CPU-speed-calibrated spin delay:
 *   - sets the BIOS-data-area byte es:0000:[0x440]=1 then spins until it reads back 1
 *     (an interrupt-driven heartbeat, segment 0 — NOT a DGROUP write);
 *   - on first use lazily measures the loop count per CGA vertical-retrace period
 *     (helper 0x00F6CF polls CGA status port 0x3DA bit 3 with interrupts disabled and
 *     counts iterations into the CS-relative module words cs:[0x12]/cs:[0x14] — again
 *     CS-relative locals, NOT DGROUP);
 *   - then runs a `movsb`-padded inner spin (counts at 0x2260/0xFA00) sized from
 *     [bp+6] so the wall-clock delay is hardware-independent.
 * The auto-banner's "Reads/Writes DGROUP 0x12/0x440" is a mis-attribution: 0x12/0x14
 * are cs-relative and 0x440 is the segment-0 BIOS data area, so there is no DGROUP
 * state for the rules layer to preserve.
 *
 * PLATFORM_LAYER: a CPU-cycle / CGA-retrace busy-wait — pure timing hardware, replaced
 * by the modern front end's frame pacing.  Honest stub per project convention; the
 * cited @asm preserves the calibration for the eventual SDL timer port. */
int func_00F5E6_logic_sz_233(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    (void)arg0_bp_06; (void)arg1_bp_08; (void)arg2_bp_0A;
    return 0;  /* TODO: SDL — CPU-calibrated micro-delay (CGA retrace tick + spin loop) */
}

/* @asm        0x00F702..0x00F71F  (29 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00F702_unknown.asm
 * @pattern    WRAPPER_LCALL
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 10, 14]
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x0016
 * @inferred_role  WRAPPER_LCALL (29 bytes). 0x0D1D:0x0016
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00F702_rtl_sz_29(uint16_t arg0_bp_06, uint16_t arg1_bp_0A, uint16_t arg2_bp_0E)
{
    /* @auto: wrapper forwards to LCALL 0x0D1D:0x0016. */
    return overlay_call_0D1D_0016();
}

/* @asm        0x00F8EC..0x00F8F6  (10 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00F8EC_unknown.asm
 * @pattern    TINY_RETURN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_RETURN (10 bytes). no LCALLs
 * @status     SHADOWED (interior of func_00F8DD; auto-segmentation artifact, not a standalone function)
 */
int func_00F8EC_logic_sz_10(void)
{
    /* @auto: tiny return-only function. */
    return 0;
}

/* @asm        0x00F8F6..0x00F960  (106 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00F8F6_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     1
 * @near_calls 5
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x126A
 *
 * Near CALL targets:
 *   - 0x00F98D  (4x)
 *   - 0x00F960
 * @inferred_role  DISPATCHER (106 bytes). 0x0D1D:0x126A
 * @status     SHADOWED (interior of func_00F8DD; auto-segmentation artifact, not a standalone function)
 */
int func_00F8F6_rtl_sz_106(uint16_t arg0_bp_06)
{
    /* @asm Reads DGROUP 0x2B16 (==0xD6D6 guard) and the cs-managed atexit/flush
     *      tables at 0x2B26/0x2B28/0x2B32/0x2B36; flushes the C stdio buffers via the
     *      near helper 0x00F98D (run-the-list) and 0x00F960 (close/flush handles),
     *      invokes the registered exit handler vector [0x2B1C] when the magic matches,
     *      runs the overlay teardown 0x0D1D:0x126A, and finally TERMINATES THE PROCESS
     *      with `mov ah,0x4C; int 0x21` (exit code = [bp+6]).  This is the DOS C
     *      runtime `exit()`/`_cexit()` path (SHADOWED interior of func_00F8DD).
     * PLATFORM_LAYER: the atexit/flush tables, the overlay teardown and the DOS
     * INT 21h AH=4Ch process-terminate are all host/runtime plumbing replaced by the
     * modern front end; the rules layer must not terminate the host process, so this
     * is an honest stub.  No DGROUP state is produced for the rules layer. */
    (void)arg0_bp_06;
    return 0;  /* @asm int 0x21 AH=4Ch — host-replaced; do not terminate the modern process */
}

/* @asm        0x00F9C4..0x00FA7E  (186 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00F9C4_fclose_or_remove.asm
 * @pattern    DISPATCHER
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     6
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x1896
 *   - 0x0D1D:0x1E7A
 *   - 0x0D1D:0x07E4
 *   - 0x0D1D:0x07A4
 *   - 0x0D1D:0x08FA
 *   - 0x0D1D:0x0E4A
 *
 * Near CALL targets:
 *   - 0x010CA0
 * @inferred_role C_RUNTIME / DISPATCH_VIA_OVERLAY  (HIGH)
 * @status     BYTE_VERIFIED 2026-06-09 (control flow ported from re_work/disasm/func_00F9C4.asm)
 */
/* PORTED 2026-06-09 from func_00F9C4.asm — closes/finalises an open file-record and,
 * when it carried a "needs save/rename" flag, splits its path and commits it through
 * the C-runtime overlays.  arg0 = near ptr to the file record `r`; the gate is the
 * flag byte r[6]: bit6 (0x40) short-circuits straight to the clear-and-exit, and only
 * records with one of bits 0x83 set are processed.  The record's r[0xA4] word (asm
 * `[si-0x290E+0x29B2]`) is the "rename target" handle and r[7] the mode byte.  Helpers:
 * 0x0D1D:0x1896 = finalise/handle (-> di), near func_010CA0 = flush/sync the record,
 * 0x0D1D:0x1E7A = commit-by-mode (negative result => failure), 0x0D1D:0x07E4/0x07A4 =
 * splitpath into the scratch buffers at [bp-0xE]/[bp-0xC] (the leading '\\' at [bp-0xE]
 * chooses which half is the basename), 0x0D1D:0x08FA + 0x0D1D:0x0E4A = rename/close the
 * target.  The overlay shims take their args off the DOS stack so they are `(void)`
 * here; the C-visible effects (the r[6] gate and its final `r[6]=0` clear, the r[7]/
 * r[0xA4] reads, the near sync call, and the success/-1 return in di) are faithful. */
int func_00F9C4_rtl_sz_186(uint16_t arg0_bp_06)
{
    uint8_t near *r = (uint8_t near *)arg0_bp_06;  /* @asm si = [bp+6] (file record) */
    int result = -1;                               /* @asm di = 0xFFFF (default) */

    /* @asm 0x00F9D2 test [si+6],0x40; jne -> 0xFA72 (already-handled short-circuit) */
    /* @asm 0x00F9DB test [si+6],0x83; je  -> 0xFA72 (nothing to commit)            */
    if ((r[6] & 0x40) == 0 && (r[6] & 0x83) != 0) {
        uint16_t rename_target;                    /* @asm [bp-4] = [si+0xA4] */
        /* @asm 0x00F9E4 push si; lcall 0D1D:0x1896 -> di */
        result = overlay_call_0D1D_1896();
        rename_target = *(uint16_t near *)(r + 0xA4);
        /* @asm 0x00F9FC push si; call 0x10CA0 (flush/sync the record) */
        func_010CA0();
        /* @asm 0x00FA03 al=[si+7]; push ax; lcall 0D1D:0x1E7A; or ax,ax; jl 0xFA6F */
        if ((int16_t)overlay_call_0D1D_1E7A() < 0) {
            result = -1;                           /* @asm 0x00FA6F di = 0xFFFF */
        } else if (rename_target != 0) {           /* @asm 0x00FA15 cmp [bp-4],0; je 0xFA72 */
            /* @asm 0x00FA1B/0x00FA23 splitpath the record's name into the scratch
             *      buffers [bp-0xE]/[bp-0xC]; the leading '\\' picks the basename half */
            overlay_call_0D1D_07E4();              /* @asm lcall 0D1D:0x7E4 */
            overlay_call_0D1D_07A4();              /* @asm lcall 0D1D:0x7A4 (else branch) */
            /* @asm 0x00FA4D rename/commit then close the target handle */
            overlay_call_0D1D_08FA();              /* @asm lcall 0D1D:0x8FA */
            overlay_call_0D1D_0E4A();              /* @asm lcall 0D1D:0xE4A; or ax,ax; je 0xFA72 */
        }
    }

    r[6] = 0;                                      /* @asm 0x00FA72 mov byte [si+6],0 */
    return result;                                 /* @asm 0x00FA76 mov ax,di; retf */
}

/* @asm        0x00FA7E..0x00FAA9  (43 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00FA7E_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10]
 * @lcalls     2
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x1E46
 *   - 0x0D1D:0x16FC
 * @inferred_role  UNKNOWN (43 bytes). 0x0D1D:0x1E46 + 0x0D1D:0x16FC
 * @status     BYTE_VERIFIED 2026-06-09 (control flow ported from re_work/disasm/func_00FA7E.asm)
 */
/* PORTED 2026-06-09 from func_00FA7E.asm — acquire a runtime handle and, if valid,
 * forward the three caller args plus that handle to the C-runtime worker.  Calls
 * 0x0D1D:0x1E46 to obtain a handle in si; when it is 0 the routine bails returning 0,
 * otherwise it pushes (si, [bp+0xA], [bp+8], [bp+6]) and tail-calls 0x0D1D:0x16FC,
 * returning that result.  The overlay shims take their args off the DOS stack, so they
 * are `(void)` here; the C-visible control flow (the handle gate and the return value)
 * is faithful to the asm. */
int func_00FA7E_rtl_sz_43(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    int handle = overlay_call_0D1D_1E46();   /* @asm 0x00FA82 lcall 0D1D:0x1E46; si=ax */
    (void)arg0_bp_06; (void)arg1_bp_08; (void)arg2_bp_0A;
    if (handle == 0)                         /* @asm 0x00FA89 or si,si; jne 0xFA92 */
        return 0;                            /* @asm 0x00FA8D sub ax,ax; jmp 0xFAA4 */
    /* @asm 0x00FA92 push si;[bp+0xA];[bp+8];[bp+6]; lcall 0D1D:0x16FC */
    return overlay_call_0D1D_16FC();         /* @asm 0x00FA9C result returned in ax */
}

