/* ============================================================================
 * load_image_00C0D0_00D27F.c -- load_image functions in file range 0x00C0D0..0x00D27F
 * Auto-generated by tools/full_pipeline.py for VICEROY.
 *
 * 30 functions in this file. Each carries a citation block plus
 * an auto-traced control-flow body.  Functions marked SKELETON have body
 * content derived from control-flow but their semantics still need hand-port.
 * ============================================================================ */
#include "viceroy.h"
#include "overlay_externs.h"

/* @asm        0x00C0D0..0x00C109  (57 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C0D0_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (57 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C0D0_logic_sz_57(void)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x004A
     */
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00C0D8 JE 0x00C0E8 */ {
            goto label_00C11B;  /* @0x00C0E5 */
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00C17A..0x00C18E  (20 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C17A_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (20 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C17A_logic_sz_20(uint16_t arg0_bp_06)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00C1F8..0x00C20C  (20 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C1F8_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (20 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C1F8_logic_sz_20(uint16_t arg0_bp_06)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00C276..0x00C28A  (20 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C276_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (20 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C276_logic_sz_20(uint16_t arg0_bp_06)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00C30A..0x00C31B  (17 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C30A_unknown.asm
 * @pattern    WRAPPER_LCALL
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x0DF2
 * @inferred_role  thin C-runtime wrapper (clears arg bit15, forwards to 0x0D1D:0x0DF2)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_00C30A_rtl_sz_17(uint16_t arg0_bp_06)
{
    /* @asm 0x00C30D mov ax,[bp+6]; 0x00C310 and ah,0x7f; 0x00C313 push ax;
     *      0x00C314 lcall 0x0D1D:0x0DF2 -> forwards the argument with bit 15
     *      cleared (ah &= 0x7F) to the C-runtime/overlay library routine and
     *      returns its result (leave/retf at 0x00C319, no post-processing).
     * library-implementation-only / body in the 0x0D1D thunk page. */
    (void)(arg0_bp_06 & 0x7FFF);   /* the masked value is what the lcall receives */
    return overlay_call_0D1D_0DF2();
}

/* @asm        0x00C322..0x00C361  (63 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C322_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 4
 * @args_seen  [6, 8]
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x0E04
 * @inferred_role  PROLOGUE_HEAVY (63 bytes). 0x0D1D:0x0E04
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C322_rtl_sz_63(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: control-flow trace from disassembly. */
        /* @0x00C326 */ overlay_call_0D1D_0E04();
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00C362..0x00C40F  (173 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C362_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   ENTER 6
 * @args_seen  [6, 8]
 * @lcalls     4
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x11B4
 *   - 0x0D1D:0x113C  (3x)
 * @inferred_role  DISPATCHER (173 bytes). 0x0D1D:0x11B4 + 0x0D1D:0x113C
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C362_rtl_sz_173(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: control-flow trace from disassembly. */
        if (/* JLE fallthrough cond: */ ax > 0) /* @0x00C371 JLE 0x00C396 */ {
            if (/* JLE fallthrough cond: */ ax > 0) /* @0x00C375 JLE 0x00C37E */ {
            }
            /* @0x00C388 */ overlay_call_0D1D_11B4();
            if (/* JL fallthrough cond: */ ax >= 0) /* @0x00C394 JL 0x00C373 */ {
            }
        }
        /* @0x00C39F */ overlay_call_0D1D_113C();
        /* @0x00C3B2 */ overlay_call_0D1D_113C();
        if (/* JBE fallthrough cond: */ ax > 0) /* @0x00C3BC JBE 0x00C403 */ {
            if (/* JG fallthrough cond: */ ax <= 0) /* @0x00C3C9 JG 0x00C3E3 */ {
            }
            /* @0x00C3F3 */ overlay_call_0D1D_113C();
            if (/* JA fallthrough cond: */ ax <= 0) /* @0x00C401 JA 0x00C3C7 */ {
            }
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00C410..0x00C459  (73 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C410_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10, 12]
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x117E
 * @inferred_role C_RUNTIME_NUMERIC  (LOW)
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C410_rtl_sz_73(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x036C
     */
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x00C41F JNE 0x00C424 */ {
        }
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x00C429 JNE 0x00C43E */ {
            /* @0x00C434 */ overlay_call_0D1D_117E();
            goto label_00C450;  /* @0x00C43C */
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00C45A..0x00C486  (44 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C45A_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 0x50
 * @args_seen  [6, 8]
 * @lcalls     1
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x04DA
 *
 * Near CALL targets:
 *   - 0x00C410
 * @inferred_role  UNKNOWN (44 bytes). 0x0D1D:0x04DA
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C45A_rtl_sz_44(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: control-flow trace from disassembly. */
        /* @0x00C46E */ func_00C410();
        /* @0x00C479 */ overlay_call_0D1D_04DA();
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00C498..0x00C4A3  (11 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C498_unknown.asm
 * @pattern    TINY_RETURN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  []
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0B22:0x0022
 * @inferred_role  thin C-runtime wrapper (passes register BX through to 0x0B22:0x0022)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_00C498_op_sz_11(void)
{
    /* @asm 0x00C49B push bx; 0x00C49C lcall 0x0B22:0x0022; 0x00C4A1 leave; retf.
     * Thin forwarder: pushes the incoming register argument BX and tail-calls
     * the 0x0B22 C-runtime/overlay library routine, returning its result.
     * library-implementation-only / body in the 0x0B22 thunk page.  (BX is a
     * register-convention input, so it is not visible in this (void) signature.) */
    return overlay_call_0B22_0022();
}

/* @asm        0x00C4A4..0x00C4DB  (55 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C4A4_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 6
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (55 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C4A4_logic_sz_55(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00C51A..0x00C5E7  (205 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C51A_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 0xe
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  LARGE_LOGIC (205 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C51A_logic_sz_205(void)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x0372, 0x0374, 0x0808, 0x92C0
     */
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x00C525 JNE 0x00C52A */ {
            goto label_00C642;  /* @0x00C527 */
        }
        if (/* JGE fallthrough cond: */ ax < 0) /* @0x00C535 JGE 0x00C53A */ {
            goto label_00C642;  /* @0x00C537 */
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00C53F JE 0x00C544 */ {
            goto label_00C642;  /* @0x00C541 */
        }
        goto label_00C614;  /* @0x00C557 */
        if (/* JLE fallthrough cond: */ ax > 0) /* @0x00C572 JLE 0x00C577 */ {
            goto label_00C611;  /* @0x00C574 */
        }
        if (/* JL fallthrough cond: */ ax >= 0) /* @0x00C577 JL 0x00C581 */ {
            if (/* JBE fallthrough cond: */ ax > 0) /* @0x00C57C JBE 0x00C581 */ {
                goto label_00C611;  /* @0x00C57E */
            }
        }
        if (/* JLE fallthrough cond: */ ax > 0) /* @0x00C5B0 JLE 0x00C604 */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00C646..0x00C690  (74 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C646_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 0xa
 * @args_seen  [6]
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x0FB2
 * @inferred_role  PROLOGUE_HEAVY (74 bytes). 0x0D1D:0x0FB2
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C646_rtl_sz_74(uint16_t arg0_bp_06)
{
    /* @auto: control-flow trace from disassembly. */
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00C667 JE 0x00C67A */ {
            goto label_00C689;  /* @0x00C677 */
        }
        /* @0x00C689 */ overlay_call_0D1D_0FB2();
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00C7DF..0x00C7EB  (12 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C7DF_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  byte setter (commits arg low byte to DGROUP:0x0383)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_00C7DF_logic_sz_12(uint16_t arg0_bp_06)
{
    /* @asm 0x00C7E3 mov ax,[bp+6]; 0x00C7E6 mov [0x0383],al; leave; retf.
     * Stores the low byte of the argument into the DGROUP byte global at
     * 0x0383 (a static-region scalar) and returns the argument (ax). */
    *(uint8_t near *)0x0383 = (uint8_t)arg0_bp_06;
    return arg0_bp_06;
}

/* @asm        0x00C899..0x00C8AB  (18 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C899_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  word setter (0x92F6 = arg, 0x92F4 = 0)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_00C899_logic_sz_18(uint16_t arg0_bp_06)
{
    /* @asm 0x00C89D mov ax,[bp+6]; 0x00C8A0 mov [0x92F6],ax;
     *      0x00C8A3 mov word [0x92F4],0; leave; retf.
     * Stores the argument into DGROUP word 0x92F6 and clears the companion
     * word 0x92F4 (both BSS runtime globals).  Returns the argument (ax).
     * Sister of func_00C7DF; 0x92F4/0x92F6 are reset together by func_00CA0C. */
    *(uint16_t near *)0x92F6 = arg0_bp_06;
    *(uint16_t near *)0x92F4 = 0;
    return arg0_bp_06;
}

/* @asm        0x00C8AB..0x00C8DB  (48 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C8AB_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 0
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (48 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C8AB_logic_sz_48(uint16_t arg0_bp_06)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Writes DGROUP: 0x92E4, 0x92E6, 0x92EC, 0x92EE, 0x92F0, 0x92F2
     */
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00C8FC..0x00C954  (88 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00C8FC_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 4
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (88 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00C8FC_logic_sz_88(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: control-flow trace from disassembly. */
        if (/* JGE fallthrough cond: */ ax < 0) /* @0x00C90A JGE 0x00C917 */ {
        }
        if (/* JGE fallthrough cond: */ ax < 0) /* @0x00C91D JGE 0x00C92A */ {
        }
        if (/* JLE fallthrough cond: */ ax > 0) /* @0x00C93E JLE 0x00C942 */ {
        }
        if (/* JLE fallthrough cond: */ ax > 0) /* @0x00C952 JLE 0x00C956 */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00CA0C..0x00CA56  (74 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00CA0C_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 2
 * @args_seen  [8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (74 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00CA0C_logic_sz_74(uint16_t arg0_bp_08)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Writes DGROUP: 0x83AC, 0x92F8, 0x9300, 0x9302, 0x9304, 0x9306, 0x9308
     */
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00CB59..0x00CB72  (25 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00CB59_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  nibble-masked coordinate-pair setter (0x0590, 0x0592)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_00CB59_logic_sz_25(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x00CB5D mov ax,[bp+6]; 0x00CB60 and ax,0xF;
     *      0x00CB63 mov bx,[bp+8]; 0x00CB66 and bx,0xF;
     *      0x00CB69 mov [0x0590],ax; 0x00CB6C mov [0x0592],bx; leave; retf.
     * Masks both arguments to their low nibble (0..15) and stores them to the
     * DGROUP word pair 0x0590/0x0592 (static-region globals, paired with the
     * 0x05AE..0x05C0 block written by func_00CECF/func_00CF19).  Returns
     * arg0 & 0xF (ax). */
    *(uint16_t near *)0x0590 = arg0_bp_06 & 0x000F;
    *(uint16_t near *)0x0592 = arg1_bp_08 & 0x000F;
    return arg0_bp_06 & 0x000F;
}

/* @asm        0x00CC8F..0x00CCEB  (92 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00CC8F_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   ENTER 0
 * @args_seen  [6, 8]
 * @lcalls     5
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0A58:0x0054
 *   - 0x0A58:0x02CE
 *   - 0x0A58:0x000D
 *   - 0x0A58:0x0207
 *   - 0x0A58:0x02E0
 * @inferred_role  DISPATCHER (92 bytes). 0x0A58:0x0054 + 0x0A58:0x02CE
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00CC8F_op_sz_92(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x83AC, 0x92F8
     * Writes DGROUP: 0x92FC, 0x92FE
     */
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x00CCA5 JNE 0x00CCAF */ {
            /* @0x00CCA7 */ overlay_call_0A58_0054();
            goto label_00CCB4;  /* @0x00CCAC */
        }
        /* @0x00CCAF */ overlay_call_0A58_02CE();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00CCC3 JE 0x00CCD5 */ {
            if (/* JNE fallthrough cond: */ ax == 0) /* @0x00CCD3 JNE 0x00CCDD */ {
                /* @0x00CCD5 */ overlay_call_0A58_000D();
                goto label_00CCE9;  /* @0x00CCDA */
            }
        }
        /* @0x00CCDE */ overlay_call_0A58_0207();
        /* @0x00CCE4 */ overlay_call_0A58_02E0();
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00CD0B..0x00CD4E  (67 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00CD0B_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 0
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x00CCEB
 * @inferred_role  PROLOGUE_HEAVY (67 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00CD0B_logic_sz_67(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x83AC, 0x92F8, 0x92FA, 0x92FC, 0x92FE
     */
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00CD16 JE 0x00CD24 */ {
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00CD29 JE 0x00CD33 */ {
            /* @0x00CD30 */ func_00CCEB();
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00CD38 JE 0x00CD3C */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00CECF..0x00CEE8  (25 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00CECF_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0
 * @args_seen  [6, 10]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  far-pointer + scale setter (0x05AC:0x05AE = ptr, 0x05B0 = scale)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: arg0 is a FAR pointer occupying [bp+6] (offset) and [bp+8] (segment);
 * the auto-banner's args_seen [6,10] missed the [bp+8] segment half consumed by
 * the `les` instruction.  Widened the prototype to a far pointer to model it.
 */
int func_00CECF_logic_sz_25(void far *src_ptr /*bp+6:bp+8*/, uint16_t scale_bp_0A)
{
    /* @asm 0x00CED4 les ax,[bp+6]; 0x00CED7 mov [0x05AE],ax (offset);
     *      0x00CEDA mov ax,es; 0x00CEDC mov [0x05AC],ax (segment);
     *      0x00CEDF mov ax,[bp+0xA]; 0x00CEE2 mov [0x05B0],ax; leave; retf.
     * Splits the far pointer arg into its offset/segment halves and stores them
     * to the DGROUP far-ptr global at 0x05AC(segment):0x05AE(offset); stores the
     * word arg [bp+0xA] into 0x05B0.  0x05B0 is later used as the row-stride
     * multiplier by func_00CF19 (the 0x05AC..0x05C0 block is this module's
     * blit/coordinate context). */
    *(uint16_t near *)0x05AE = (uint16_t)(uint32_t)src_ptr;          /* offset  */
    *(uint16_t near *)0x05AC = (uint16_t)((uint32_t)src_ptr >> 16);  /* segment */
    *(uint16_t near *)0x05B0 = scale_bp_0A;                          /* stride  */
    return 0;
}

/* @asm        0x00CEE8..0x00CF12  (42 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00CEE8_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 0
 * @args_seen  [6, 8, 10, 12]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (42 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00CEE8_logic_sz_42(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Writes DGROUP: 0x05B2, 0x05B4, 0x05B6, 0x05B8, 0x05C2
     */
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00CF19..0x00CF32  (25 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00CF19_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  blit-address computer (col=arg0, row=arg1; offset=row*stride+col)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_00CF19_logic_sz_25(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x00CF1D mov bx,[bp+6]; 0x00CF20 mov [0x05BA],bx;
     *      0x00CF24 mov ax,[bp+8]; 0x00CF27 mov [0x05BC],ax;
     *      0x00CF2A mov dx,[0x05B0]; 0x00CF2E mul dx (ax = arg1 * stride);
     *      0x00CF30 add ax,bx (+ arg0); 0x00CF32 mov [0x05BE],ax;
     *      0x00CF35 add ax,[0x05AE] (+ ptr offset); 0x00CF39 mov [0x05C0],ax; retf.
     * Records the (col=arg0 @0x05BA, row=arg1 @0x05BC) pair, computes the linear
     * pixel offset  row*stride + col  into 0x05BE, then adds the framebuffer base
     * offset (0x05AE, set by func_00CECF) to form the absolute address in 0x05C0.
     * `mul dx` is an unsigned 16-bit multiply; only the low word (ax) is kept.
     * Returns the absolute address word (ax = 0x05C0). */
    uint16_t col    = arg0_bp_06;
    uint16_t row    = arg1_bp_08;
    uint16_t stride = *(uint16_t near *)0x05B0;
    uint16_t linear = (uint16_t)(row * stride) + col;
    uint16_t addr   = linear + *(uint16_t near *)0x05AE;
    *(uint16_t near *)0x05BA = col;
    *(uint16_t near *)0x05BC = row;
    *(uint16_t near *)0x05BE = linear;
    *(uint16_t near *)0x05C0 = addr;
    return addr;
}

/* @asm        0x00CF3E..0x00CFC4  (134 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00CF3E_unknown.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 0x12
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  MEDIUM_LOGIC (134 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00CF3E_logic_sz_134(void)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x0594, 0x0596, 0x05A4, 0x05A6, 0x05B2, 0x05B4, 0x05B6, 0x05B8, 0x92F8, 0xA899
     */
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00CF4A JE 0x00CFA6 */ {
            if (/* JNE fallthrough cond: */ ax == 0) /* @0x00CF51 JNE 0x00CFA6 */ {
                if (/* JG fallthrough cond: */ ax <= 0) /* @0x00CF69 JG 0x00CFA6 */ {
                    if (/* JL fallthrough cond: */ ax >= 0) /* @0x00CF74 JL 0x00CFA6 */ {
                        if (/* JG fallthrough cond: */ ax <= 0) /* @0x00CF7D JG 0x00CFA6 */ {
                            if (/* JL fallthrough cond: */ ax >= 0) /* @0x00CF88 JL 0x00CFA6 */ {
                                if (/* JL fallthrough cond: */ ax >= 0) /* @0x00CF8E JL 0x00CFAC */ {
                                    if (/* JG fallthrough cond: */ ax <= 0) /* @0x00CF9C JG 0x00CFC0 */ {
                                        goto label_00CFC7;  /* @0x00CFA3 */
                                        goto label_00D078;  /* @0x00CFA9 */
                                        goto label_00CFC7;  /* @0x00CFBD */
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00D0B6..0x00D0D9  (35 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00D0B6_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (35 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00D0B6_logic_sz_35(uint16_t arg0_bp_06)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x07E8, 0x07EA
     */
        if (/* JG fallthrough cond: */ ax <= 0) /* @0x00D0BF JG 0x00D0DA */ {
            if (/* JL fallthrough cond: */ ax >= 0) /* @0x00D0C3 JL 0x00D0DA */ {
                if (/* JG fallthrough cond: */ ax <= 0) /* @0x00D0CB JG 0x00D0DA */ {
                    if (/* JL fallthrough cond: */ ax >= 0) /* @0x00D0D0 JL 0x00D0DA */ {
                    }
                }
            }
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00D106..0x00D1A4  (158 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00D106_unknown.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  []
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0A58:0x038B
 * @inferred_role  MEDIUM_LOGIC (158 bytes). 0x0A58:0x038B
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00D106_op_sz_158(void)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x07E6, 0x07E8, 0x07EA, 0x07EE, 0x07F2, 0x07F4, 0x07F8, 0x07FA
     * Writes DGROUP: 0x07E6, 0x07EC, 0x07EE, 0x07F0, 0x07F2, 0x07F4, 0x07F8, 0x07FA, 0x07FC, 0x07FE
     */
        /* @0x00D11B */ overlay_call_0A58_038B();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00D13A JE 0x00D148 */ {
            if (/* JNE fallthrough cond: */ ax == 0) /* @0x00D13E JNE 0x00D148 */ {
                goto label_00D14E;  /* @0x00D146 */
            }
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00D150 JE 0x00D15E */ {
            if (/* JNE fallthrough cond: */ ax == 0) /* @0x00D157 JNE 0x00D15E */ {
                goto label_00D160;  /* @0x00D15C */
            }
        }
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x00D166 JNE 0x00D16C */ {
        }
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x00D173 JNE 0x00D18E */ {
            if (/* JNE fallthrough cond: */ ax == 0) /* @0x00D17C JNE 0x00D18E */ {
                if (/* JNE fallthrough cond: */ ax == 0) /* @0x00D180 JNE 0x00D18E */ {
                    if (/* JNE fallthrough cond: */ ax == 0) /* @0x00D186 JNE 0x00D18E */ {
                        goto label_00D194;  /* @0x00D18C */
                    }
                }
            }
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00D19A JE 0x00D1B1 */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00D1CA..0x00D1E4  (26 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00D1CA_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (26 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00D1CA_logic_sz_26(void)
{
    /* @auto: tiny accessor reads DGROUP:0x07FC. */
    return *((uint16_t near*)0x07FC);
}

/* @asm        0x00D1E4..0x00D218  (52 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00D1E4_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (52 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00D1E4_logic_sz_52(uint16_t arg0_bp_06)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x0806
     * Writes DGROUP: 0x0808
     */
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x00D20D JNE 0x00D20A */ {
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00D212 JE 0x00D20F */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00D272..0x00D27F  (13 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00D272_kbhit.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (13 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00D272_logic_sz_13(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

