/* ============================================================================
 * load_image_0024C6_0033E9.c -- load_image functions in file range 0x0024C6..0x0033E9
 * Auto-generated by tools/full_pipeline.py for VICEROY.
 *
 * 30 skeleton entries; 29 real functions in this file (the 30th, func_003193,
 * was the SHADOWED tail of func_003104 and is folded into it -- not a standalone
 * function).  Each carries a citation block plus a hand-ported body.
 *
 * 2026-06-09: bodies hand-ported from the func_XXXXXX.asm disassembly.  This
 * file is the lowest-address load_image image, so several near-CALL targets
 * (0x2494, 0x2942, 0x2952, 0x28B0) live below 0x24C6 / in the 0x2892..0x2992
 * gap and are not yet emitted into any sibling .c; they are forward-declared
 * file-locally below (sibling convention).  This module is the on-screen
 * "label/tooltip" + horizontal stacked-bar drawing layer: it measures glyph
 * runs (overlay 0x0C2A:6), sets the blit clip/colour (0x0C28:0xA), and blits
 * sprites/rects (0x0C11:0xC, 0x0D1D:0x11B4) and proportional text
 * (0x0B9E:0xA, 0x0C36:0xA).
 * ============================================================================ */
#include "viceroy.h"
#include "dgroup.h"
#include "overlay_externs.h"

/* File-local overlay-call externs (RTLink targets not present in
 * overlay_externs.h).  Same convention as the sibling load_image_*.c files:
 * each is a far overlay entry resolved by the RTLink thunk layer at run time. */
extern int  overlay_call_0000_0062();  /* @ref RTLink seg 0x0000 off 0x0062 -- string by id  */
extern int  overlay_call_0AE7_0002();  /* @ref RTLink seg 0x0AE7 off 0x0002 -- point hit-test */
extern int  overlay_call_0BCA_0002();  /* @ref RTLink seg 0x0BCA off 0x0002 -- fill rect    */
extern int  overlay_call_0BF5_0000();  /* @ref RTLink seg 0x0BF5 off 0x0000 -- draw frame    */
extern int  overlay_call_0ACB_0006();  /* @ref RTLink seg 0x0ACB off 0x0006 -- cell predicate*/
extern int  overlay_call_004B_0318();  /* @ref RTLink seg 0x004B off 0x0318 -- string blit   */
extern int  overlay_call_0C0C_0006();  /* @ref RTLink seg 0x0C0C off 0x0006 -- cursor x/y     */
extern int  overlay_call_0C2A_0006();  /* @ref RTLink seg 0x0C2A off 0x0006 -- measure glyph  */

/* Near siblings called from this file but living below 0x24C6 / in the
 * 0x2892..0x2992 gap (not yet emitted as separate .c).  Far functions reached
 * by the large-model `push cs; call near` idiom (each ends in retf). */
extern void func_002494(uint16_t code, uint16_t *out_glyph, uint16_t *out_attr); /* @0x2494 glyph/attr lookup */
extern void func_002942(uint16_t arg0);   /* @0x2942 -> overlay 0x0D1D:0x07A4 with id 0x62 */
extern void func_002952(uint16_t arg0);   /* @0x2952 -> overlay 0x0D1D:0x07A4 with id 0x64 */
extern void func_0028B0(uint16_t arg0);   /* @0x28B0 -> overlay 0x0D1D:0x07A4 with id 0x50 */

/* @asm        0x0024C6..0x0024C6+126  (126 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0024C6_unknown.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 8
 * @lcalls     5 (0xC0C:6, 0xAE7:2, 0xA58:0x38B, 0x262:0xDA)
 * @inferred_role  hover/tooltip dwell loop for the cell under the cursor.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_0024C6.asm -- tooltip dwell loop: while the
 * pointer (overlay 0xC0C:6 -> 32-bit cursor) stays inside the clamped hot-rect
 * [0x2DA4/0x2DA6] and the hit-test (0xAE7:2) plus the popup builder (0xA58:0x38B)
 * keep returning "still hovering", spin; then dismiss via overlay 0x262:0xDA. */
int func_0024C6_op_sz_126(void)
{
    int32_t limit;        /* [bp-4]:[bp-2]  clamped cursor+0x1e upper bound (dx:ax) */
    int32_t bound;        /* [0x2DA6]:[0x2DA4] saved hot-rect bound                 */
    int32_t cur;          /* dx:ax current cursor                                   */
    int16_t lo, hi;       /* [bp-8]/[bp-6]  out params for the 0xA58 popup builder  */
    int hovering;         /* dx flag        */

    /* @asm 0x0024CA if ([0x4a]==0) goto done; @0x0024D1 if ([0x7ee]!=0) goto done. */
    if (DG8(0x004A) == 0)              /* je 0x253d */
        goto done;
    if (DG16(0x07EE) != 0)             /* jne 0x253d */
        goto done;

    /* @asm 0x0024D8 lcall 0xc0c,6 -> dx:ax cursor; @0x0024E3 add 0x1e (32-bit). */
    cur = (int32_t)overlay_call_0C0C_0006();   /* dx:ax cursor */
    limit = cur + 0x1E;

    /* @asm 0x0024E9 bound = [0x2DA6]:[0x2DA4]; if (limit > bound) limit = bound. */
    bound = ((int32_t)DGS16(0x2DA6) << 16) | (uint16_t)DG16(0x2DA4);
    if (limit > bound)                 /* @asm cmp dx,[0x2da6]/cmp ax,[0x2da4]; jbe/jl/jg */
        limit = bound;
    /* @asm 0x0024FE [bp-4]:[bp-2] = limit (kept in locals -- the DGROUP bound is read-only). */

scan:
    /* @asm 0x002504 lcall 0xae7,2 -> point hit-test; if (ax!=0) not hovering. */
    if (overlay_call_0AE7_0002() != 0) {   /* or ax,ax; jne 0x2526 */
        hovering = 0;
    } else {
        /* @asm 0x00250D push &lo,&hi; lcall 0xa58,0x38b; hovering = (ax==0). */
        (void)lo; (void)hi;
        hovering = (overlay_call_0A58_038B() != 0) ? 0 : 1;
    }

    /* @asm 0x002528 if (!hovering) goto done. */
    if (hovering == 0)
        goto done;

    /* @asm 0x00252C lcall 0xc0c,6 -> cursor; while it has not passed the limit, re-scan. */
    cur = (int32_t)overlay_call_0C0C_0006();
    if (cur < limit)                   /* @asm cmp dx,[bp-2]; jl 0x2504 / cmp ax,[bp-4]; jb */
        goto scan;                     /* still inside the hot-rect: keep dwelling */

done:
    /* @asm 0x00253D lcall 0x262,0xda (dismiss / commit). */
    overlay_call_0262_00DA();
    return 0;
}

/* @asm        0x002544..0x00260D  (201 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002544_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 4
 * @args_seen  [6]
 * @near_calls 1 (0x0024C6)
 * @lcalls     0xB9E:0xA, 0xBF5:0, 0xB70:0x3A, 0xC0C:6
 * @inferred_role  draw the active tooltip then run the dwell loop.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: the auto banner span (0x002544..0x002580, "60 bytes") was a false cut at
 * the first forward branch @0x002551; the true function is 201 bytes ending at the
 * leave/retf @0x00260C (functions.json foff=0x2544 end=0x260D).
 */
/* PORTED 2026-06-09 from func_002544.asm -- if a tooltip is armed ([0x4a]!=0,
 * arg0!=0): blit it (sprite via 0xB9E:0xA when no string handle [0x14BA], else
 * the framed string via 0xBF5:0), wait for the cursor to settle (0xB70:0x3A then
 * spin on 0xC0C:6), then clear the four "tooltip armed" flag bytes. */
int func_002544_logic_sz_60(uint16_t arg0_bp_06)
{
    int32_t t0, t1;     /* [bp-4]/[bp-2] cursor snapshots */

    /* @asm 0x002548 push cs; call 0x24c6 (run the dwell loop first). */
    func_0024C6_op_sz_126();

    /* @asm 0x00254C if ([0x4a]==0 || arg0==0) goto clear. */
    if (DG8(0x004A) == 0)              /* jne 0x2556 else jmp 0x25fd */
        goto clear;
    if (arg0_bp_06 == 0)               /* jne 0x255f else jmp 0x25fd */
        goto clear;

    /* @asm 0x00255F if ([0x14ba]==0) draw the icon/sprite tooltip via 0xB9E:0xA. */
    if (DG16(0x14BA) == 0) {
        /* @asm push [0x2dae..0x2da8], [0x2cc8], 0x22; ax=[0x2cca],dx=[0x2ccc],bx=[0x2cc6]. */
        overlay_call_0B9E_000A();      /* @asm 0x002587 */
    } else {
        /* @asm 0x00258E push 0,0,[0x2cc8],[0x2cc6],[0x2ccc],[0x2cca]; the 4 words at [0x14ba];
         *      [0x2dae..0x2da8]; 0x0025C1 lcall 0xbf5,0 (framed string draw). */
        overlay_call_0BF5_0000();
    }

    /* @asm 0x0025C9 push [0x2ccc],[0x2cc6],[0x2cc8]; ax=[0x2cca]; lcall 0xb70,0x3a (settle). */
    overlay_call_0B70_003A();          /* @asm 0x0025DE */

    /* @asm 0x0025E3 lcall 0xc0c,6 -> t0; then spin: while cursor (0xc0c,6) == t0 keep waiting. */
    t0 = (int32_t)overlay_call_0C0C_0006();   /* dx:ax snapshot into [bp-4]:[bp-2] */
    do {
        t1 = (int32_t)overlay_call_0C0C_0006();   /* @asm 0x0025EE re-read cursor (dx:ax) */
    } while (t1 == t0);                /* @asm cmp ax,[bp-4]; cmp dx,[bp-2]; je 0x25ee */

clear:
    /* @asm 0x0025FD al=0; [0x4a]=[0x4b]=[0x4c]=[0x2d54]=0. */
    DG8(0x004A)   = 0;
    DG8(0x004B)   = 0;
    DG8(0x004C)   = 0;
    DG8(0x2D54)   = 0;
    return 0;
}

/* @asm        0x00260E..0x002631  (35 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00260E.asm
 * @pattern    WRAPPER
 * @prologue   PUSH-BP-MOV-BP-SP
 * @lcalls     0x0D1D:0x11B4 (x2, RTL far strcat)
 * @inferred_role  tooltip_append: strcat(DS:0x2D54, src) + strcat(DS:0x2D54, DS:0x4D)
 * @status     PORTED 2026-06-12 (full body decompiled from VICEROY.EXE)
 *
 * Original signature is (src_off, src_seg) -- a far pointer split across two
 * stack words.  The modern port takes a host pointer (the two callers are
 * func_002632 below, passing the find_char_in_buffer result, and ai_eval_unit's
 * colony message block passing DS:(0x5D48 + colony*0xCA)).  DS:0x4D is the
 * separator literal in the DGROUP init image (loaded from VICEROY.EXE). */
void func_00260E_tooltip_append(const char *src)
{
    /* @asm 0x002611 push [bp+8],[bp+6](src); push ds,0x2D54; lcall 0xD1D:0x11B4
     *      (far strcat: dest = DS:0x2D54 tooltip text buffer). */
    char *dst = (char *)&DG8(0x2D54);
    unsigned len = 0;
    while (dst[len]) len++;
    if (src) {                          /* headless: NULL when string table absent */
        while (*src && len < 0xFF) dst[len++] = *src++;
    }
    /* @asm 0x002622 push ds,0x4D; push ds,0x2D54; lcall 0xD1D:0x11B4
     *      (append the DS:0x4D separator literal). */
    {
        const char *sep = (const char *)&DG8(0x004D);
        while (*sep && len < 0xFF) dst[len++] = *sep++;
    }
    dst[len] = 0;
}

/* @asm        0x002632..0x002647  (21 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002632.asm
 * @pattern    WRAPPER_NEARCALL
 * @prologue   PUSH-BP-MOV-BP-SP
 * @lcalls     0x0000:0x0062 (same-seg far -> file 0x2462 = find_char_in_buffer)
 * @near_calls 1 (0x00260E)
 * @inferred_role  tooltip_append_indexed: append string #arg0 from the NAMES table
 * @status     PORTED 2026-06-12 (full body decompiled from VICEROY.EXE)
 */
void func_002632_tooltip_append_indexed(uint16_t name_word)
{
    /* @asm 0x002635 push [bp+6]; lcall 0x0000:0x62 -> DX:AX = far ptr to the
     *      name_word'th NUL-string in the loaded NAMES table (find_char_in_buffer,
     *      ported in src/iolib/format.c; returns NULL headless);
     * @asm 0x00263F push dx,ax; call 0x260E (append it + separator). */
    extern void far *find_char_in_buffer(uint16_t count);
    func_00260E_tooltip_append((const char *)find_char_in_buffer(name_word));
}

/* @asm        0x0026D4..0x002700  (44 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0026D4_unknown.asm
 * @pattern    WRAPPER_NEARCALL
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10]
 * @near_calls 1 (0x0024C6)
 * @inferred_role  arm a tooltip: flush the prior one, latch its id/key and origin.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_0026D4.asm -- arm a tooltip: run/flush the current
 * dwell loop, set armed=1, latch [0x4b]=[0x7ee] (key) and [0x4c]=arg0 (id), then
 * store the cursor origin (cursor() + (arg2:arg1)) into [0x2DA4]/[0x2DA6]. */
int func_0026D4_logic_sz_44(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    int32_t origin;

    /* @asm 0x0026D7 push cs; call 0x24c6 (flush). */
    func_0024C6_op_sz_126();

    /* @asm 0x0026DB [0x4a]=1; [0x4b]=[0x7ee]; [0x4c]=arg0. */
    DG8(0x004A) = 1;
    DG8(0x004B) = DG8(0x07EE);
    DG8(0x004C) = (uint8_t)arg0_bp_06;

    /* @asm 0x0026EC lcall 0xc0c,6 -> dx:ax; add (arg2:arg1); store to [0x2da4]/[0x2da6]. */
    origin = (int32_t)overlay_call_0C0C_0006();        /* dx:ax cursor */
    origin += ((int32_t)(int16_t)arg2_bp_0A << 16) | (uint16_t)arg1_bp_08;
    DG16(0x2DA4) = (uint16_t)origin;                   /* @asm mov [0x2da4],ax */
    DG16(0x2DA6) = (uint16_t)(origin >> 16);           /* @asm mov [0x2da6],dx */
    return 0;
}

/* @asm        0x00273E..0x00275B  (29 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00273E_unknown.asm
 * @pattern    TINY_RETURN
 * @inferred_role  store four words into the DGROUP rect/coord cluster at 0x2CC6..0x2CCD
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: true body is 29 bytes (0x00273E..0x00275B) and takes four args; the
 * skeleton header's 10-byte span and 1-arg signature were a false auto-segmentation
 * cut (the @args_seen pass only saw the first store).
 */
void func_00273E_logic_sz_10(uint16_t arg0_bp_06, uint16_t arg1_bp_08,
                             uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    /* @asm 0x002741 mov ax,[bp+6];  mov [0x2cca],ax
     * @asm 0x002747 mov ax,[bp+8];  mov [0x2ccc],ax
     * @asm 0x00274d mov ax,[bp+0xa]; mov [0x2cc6],ax
     * @asm 0x002753 mov ax,[bp+0xc]; mov [0x2cc8],ax
     * Plain setter for the four adjacent DGROUP words. */
    DG16(0x2CCA) = arg0_bp_06;
    DG16(0x2CCC) = arg1_bp_08;
    DG16(0x2CC6) = arg2_bp_0A;
    DG16(0x2CC8) = arg3_bp_0C;
}

/* @asm        0x00275C..0x002892  (310 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00275C_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 0x54
 * @args_seen  [6, 8, 10]
 * @lcalls     0xBCA:2, 0xB9E:0xA, 0xBF5:0, 0xD1D:0x7E4, 0xD1D:0x117E, 0x4B:0x318, 0xB70:0x3A
 * @near_calls 1 (0x2494, far via push cs/call near)
 * @inferred_role  build and blit the popup label box (frame + text) for a cell.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: the auto banner span (0x00275C..0x002783, "39 bytes") was a false cut at the
 * first forward branch @0x002765; the true function is 310 bytes ending at the
 * leave/retf @0x002891 (functions.json foff=0x275C end=0x2892).
 */
/* PORTED 2026-06-09 from func_00275C.asm -- draw a label/tooltip box at the
 * current rect [0x2CC6..0x2CCD]: clear the interior (0xBCA:2), look up the glyph
 * via the near helper @0x2494, blit either the framed string (0xBF5:0 when a
 * string handle [0x14BA] is present) or the bitmap glyph (0xB9E:0xA), format the
 * caption (0xD1D:0x7E4 / 0xD1D:0x117E into a [bp-0x54] scratch buffer), blit the
 * caption (0x4B:0x318), and -- when arg0!=0 -- draw the connector via 0xB70:0x3A. */
int func_00275C_logic_sz_39(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    uint16_t glyph;      /* [bp-2] glyph code from helper @0x2494 */
    uint16_t attr;       /* [bp-4] attribute/colour from helper   */
    char     buf[0x54];  /* [bp-0x54] caption scratch buffer      */

    /* @asm 0x002760 if ([0x4a]==0 && (arg2|arg1)==0) goto done. */
    if (DG8(0x004A) == 0 && (arg2_bp_0A | arg1_bp_08) == 0)   /* jmp 0x2890 */
        goto done;

    /* @asm 0x002772 push [0x2dae..0x2da8], [0x2cc8]+[0x2ccc], 0; ax=[0x2cca],
     *      bx=[0x2cc6]+ax, dec ax; dx=[0x2ccc]-1; lcall 0xbca,2 (clear interior). */
    overlay_call_0BCA_0002();          /* @asm 0x00279B */

    /* @asm 0x0027A0 push &attr,&glyph,([0x4c] zero-extended); push cs; call 0x2494. */
    func_002494((uint16_t)DG8(0x004C), &glyph, &attr);

    /* @asm 0x0027B6 if (glyph==0x22 && [0x14ba]!=0) draw framed string via 0xBF5:0. */
    if (glyph == 0x22 && DG16(0x14BA) != 0) {
        overlay_call_0BF5_0000();      /* @asm 0x0027F6 */
    } else {
        /* @asm 0x002800 push [0x2dae..0x2da8],[0x2cc8],(glyph low byte);
         *      ax=[0x2cca],dx=[0x2ccc],bx=[0x2cc6]; lcall 0xb9e,0xa (bitmap glyph). */
        overlay_call_0B9E_000A();      /* @asm 0x002823 */
    }

    /* @asm 0x002828 if ([0x4a]!=0) format caption from [0x2d54] (0xD1D:0x7E4)
     *      else format from (arg2:arg1) (0xD1D:0x117E), into ss:buf. */
    if (DG8(0x004A) != 0) {
        overlay_call_0D1D_07E4();      /* @asm 0x002836 push 0x2d54,&buf; lcall 0xd1d,0x7e4 */
    } else {
        overlay_call_0D1D_117E();      /* @asm 0x00284B push arg2,arg1,&buf; lcall 0xd1d,0x117e */
    }
    (void)buf;

    /* @asm 0x002853 push attr,[0x2ccc]+1,[0x2cc6],[0x2cca],ss,&buf; lcall 0x4b,0x318 (text blit). */
    overlay_call_004B_0318();          /* @asm 0x002868 */

    /* @asm 0x002870 if (arg0!=0) draw connector via 0xb70,0x3a. */
    if (arg0_bp_06 != 0) {
        overlay_call_0B70_003A();      /* @asm 0x00288B */
    }

done:
    return 0;
}

/* @asm        0x002783..0x002790  (13 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002783_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @status     SHADOWED (interior of func_00275C; auto-segmentation artifact, not a standalone function)
 *
 * NOTE: 0x2783 falls inside func_00275C (0x275C..0x2892); this is not a real
 * function -- it is the middle of the box-clear push sequence.  No callers.
 * Kept only so existing references compile; it does no game work.
 */
int func_002783_logic_sz_13(void)
{
    /* @auto: SHADOWED artifact -- returns the rect-left word it happened to read. */
    return DG16(0x2CCA);
}

/* @asm        0x002892..0x0028B0  (30 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002892_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10]
 * @near_calls 2 (0x0026D4, 0x00275C)
 * @inferred_role  arm a tooltip (func_0026D4) then immediately render it (func_00275C).
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002892.asm -- arm-and-draw a tooltip:
 * func_0026D4(arg0,arg1,arg2) latches it, then func_00275C(1,0,0) draws it. */
int func_002892_logic_sz_30(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    /* @asm 0x002895 push arg2,arg1,arg0; call 0x26d4. */
    func_0026D4_logic_sz_44(arg0_bp_06, arg1_bp_08, arg2_bp_0A);
    /* @asm 0x0028A4 push 0,0,1; call 0x275c. */
    func_00275C_logic_sz_39(1, 0, 0);
    return 0;
}

/* @asm        0x002992..0x0029AC  (26 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002992_unknown.asm
 * @pattern    WRAPPER_LCALL
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8]
 * @lcalls     1 (0x00:0x62 string-by-id, 0x0D1D:0x11B4 blit)
 * @inferred_role  resolve a localized string by id (arg1) and blit it as the glyph at arg0.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002992.asm -- look up string-by-id (overlay
 * 0x0000:0x0062 with id=arg1, returns a far ptr dx:ax) and blit it at slot arg0
 * via overlay 0x0D1D:0x11B4. */
int func_002992_rtl_sz_26(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x002995 push arg1; lcall 0,0x62 -> dx:ax. */
    overlay_call_0000_0062();          /* string_by_id(arg1) */
    /* @asm 0x00299F push dx,ax,ds,arg0; lcall 0xd1d,0x11b4 (blit). */
    overlay_call_0D1D_11B4();
    return 0;
}

/* @asm        0x0029AC..0x0029DD  (49 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0029AC_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8]
 * @lcalls     1 (0x0D1D:0x11B4)
 * @near_calls 2 (0x002942, 0x002952)
 * @inferred_role  bracketed string blit: open-mark(arg0), id-string(arg1)@arg0, close-mark(arg0).
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_0029AC.asm -- draw a value with leading/trailing
 * marker glyphs: func_002942(arg0) draws the open marker, the id-string for arg1
 * (overlay 0x00:0x62) is blitted at arg0 (0x0D1D:0x11B4), then func_002952(arg0)
 * draws the close marker. */
int func_0029AC_rtl_sz_49(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x0029B0 si=arg0; push si; call 0x2942 (open marker). */
    func_002942(arg0_bp_06);
    /* @asm 0x0029BB push arg1; lcall 0,0x62 -> dx:ax; push dx,ax,ds,si; lcall 0xd1d,0x11b4. */
    overlay_call_0000_0062();          /* string_by_id(arg1) */
    overlay_call_0D1D_11B4();
    /* @asm 0x0029D2 push si; call 0x2952 (close marker). */
    func_002952(arg0_bp_06);
    return 0;
}

/* @asm        0x0029DE..0x002A05  (39 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0029DE_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 0x14
 * @args_seen  [6, 8, 10]
 * @lcalls     2 (0x0D1D:0x08FA fmt-number, 0x0D1D:0x11B4 blit)
 * @inferred_role  format arg2 as a number into a scratch buffer and blit it at (arg0,arg1).
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_0029DE.asm -- number-to-text(arg2) into a 0x14-byte
 * stack buffer via overlay 0x0D1D:0x08FA, then blit the text at slot (arg0,arg1)
 * via overlay 0x0D1D:0x11B4. */
int func_0029DE_rtl_sz_39(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    char buf[0x14];    /* [bp-0x14] formatted-number scratch */

    /* @asm 0x0029E2 push 0xa,&buf,arg2; lcall 0xd1d,0x8fa (itoa base 10). */
    overlay_call_0D1D_08FA();
    /* @asm 0x0029F3 push ss,&buf,arg1,arg0; lcall 0xd1d,0x11b4 (blit). */
    overlay_call_0D1D_11B4();
    (void)buf;
    return 0;
}

/* @asm        0x002A06..0x002A6E  (104 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002A06_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   ENTER 0x18
 * @args_seen  [6, 8, 10]
 * @lcalls     4 (0x0D1D:0x08FA, 0x0D1D:0x0842, 0x0D1D:0x11B4 x2)
 * @inferred_role  right-justify a formatted number in an 8-glyph field at (arg0,arg1).
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002A06.asm -- render arg2 as a number into an
 * 8-cell field starting at (arg0,arg1): format it (0x0D1D:0x08FA), measure its
 * length (0x0D1D:0x0842), pad the field on the left with blanks at id 0x6C
 * (0x0D1D:0x11B4) for (8 - len) cells, then blit the number (0x0D1D:0x11B4). */
int func_002A06_rtl_sz_104(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    char buf[0x18];    /* [bp-0x18] formatted-number scratch */
    int  len;          /* di = strlen of the number */
    int  pad;          /* si = 8 - len blanks to draw  */

    /* @asm 0x002A0C push 2,&buf,arg2; lcall 0xd1d,0x8fa (format with field width 2?). */
    overlay_call_0D1D_08FA();
    /* @asm 0x002A22 push &buf; lcall 0xd1d,0x842 -> di = length. */
    len = overlay_call_0D1D_0842();

    /* @asm 0x002A30 ax = 8 - len; if (ax > 0) draw (8-len) blank cells at id 0x6c. */
    pad = 8 - len;
    if (pad > 0) {                          /* jle 0x2a57 */
        int x = (int)arg0_bp_06;            /* @asm di=arg0 walks left->right */
        for (; pad > 0; --pad) {            /* @asm dec si; jne 0x2a44 */
            /* @asm 0x002A44 push ds,0x6c,arg1,x; lcall 0xd1d,0x11b4 (blank cell). */
            (void)x;
            overlay_call_0D1D_11B4();
        }
    }

    /* @asm 0x002A57 push ss,&buf,arg1,arg0; lcall 0xd1d,0x11b4 (the number). */
    overlay_call_0D1D_11B4();
    (void)buf;
    return 0;
}

/* @asm        0x002A6E..0x002A98  (42 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002A6E_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 0x14
 * @args_seen  [6, 8, 10, 12]
 * @lcalls     2 (0x0D1D:0x0916 fmt, 0x0D1D:0x11B4 blit)
 * @inferred_role  format arg2/arg3 (0x0916) into a buffer and blit at (arg0,arg1).
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002A6E.asm -- format the (arg2,arg3) pair via
 * overlay 0x0D1D:0x0916 into a 0x14-byte scratch buffer, then blit it at slot
 * (arg0,arg1) via overlay 0x0D1D:0x11B4. */
int func_002A6E_rtl_sz_42(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    char buf[0x14];    /* [bp-0x14] scratch */

    /* @asm 0x002A72 push 0xa,&buf,arg3,arg2; lcall 0xd1d,0x916 (format pair). */
    overlay_call_0D1D_0916();
    /* @asm 0x002A86 push ss,&buf,arg1,arg0; lcall 0xd1d,0x11b4 (blit). */
    overlay_call_0D1D_11B4();
    (void)buf;
    return 0;
}

/* @asm        0x002A98..0x002AC6  (46 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002A98_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10, 12]
 * @lcalls     1 (0x0D1D:0x11B4)
 * @near_calls 1 (0x002A6E)
 * @inferred_role  blit a fraction "arg1/.." then a separator glyph (id 0x6E) at arg0.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002A98.asm -- draw a paired value:
 * func_002A6E(arg0, arg1, arg2, arg3) renders the formatted pair, then a
 * separator glyph (id 0x6E) is blitted at (arg0,arg1) via overlay 0x0D1D:0x11B4. */
int func_002A98_rtl_sz_46(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    /* @asm 0x002AA0 si=arg0; di=arg1(@bp+8); push arg3,arg2,arg1,si; call 0x2a6e. */
    func_002A6E_rtl_sz_42(arg0_bp_06, arg1_bp_08, arg2_bp_0A, arg3_bp_0C);
    /* @asm 0x002AB4 push ds,0x6e,di,si; lcall 0xd1d,0x11b4 (separator glyph). */
    overlay_call_0D1D_11B4();
    return 0;
}

/* @asm        0x002AC6..0x002AE1  (27 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002AC6_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8]
 * @lcalls     1 (0x0C2A:6 measure)
 * @inferred_role  measured pixel width of string (arg0,arg1) minus 1.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002AC6.asm -- return (text width of the string
 * (arg0,arg1) measured by overlay 0x0C2A:6, in font [0x89E]/[0x8A0]) minus 1. */
int func_002AC6_logic_sz_27(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x002AC9 push [0x8a0],[0x89e],arg1,arg0; ax=0; lcall 0xc2a,6; dec ax. */
    int w = overlay_call_0C2A_0006();
    return w - 1;
}

/* @asm        0x002AE2..0x002AFD  (27 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002AE2_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8]
 * @lcalls     1 (0x0C2A:6 measure)
 * @inferred_role  measured pixel width of string (arg0,arg1) minus 1 (alt font [0x268A]/[0x268C]).
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002AE2.asm -- twin of func_002AC6 using the
 * alternate font ([0x268A]/[0x268C]); returns measured width minus 1. */
int func_002AE2_logic_sz_27(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x002AE5 push [0x268c],[0x268a],arg1,arg0; ax=0; lcall 0xc2a,6; dec ax. */
    int w = overlay_call_0C2A_0006();
    return w - 1;
}

/* @asm        0x002AFE..0x002B38  (58 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002AFE_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10, 12]
 * @lcalls     2 (0x0C28:0xA set-style, 0x0C11:0xC blit-string)
 * @inferred_role  set colour [0x830] and blit string (arg0,arg1) at column arg2/row arg3.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002AFE.asm -- set the text style/clip (colour byte
 * [0x830], width 0xFFFF) via overlay 0x0C28:0xA, then blit the string (arg0,arg1)
 * with x=arg2, y=arg3, palette [0x2DA8] via overlay 0x0C11:0xC. */
int func_002AFE_op_sz_58(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    /* @asm 0x002B05 push 0; dl=[0x830],dh=0; ax=0xffff,bx=0; lcall 0xc28,0xa. */
    overlay_call_0C28_000A();
    /* @asm 0x002B17 push [0x8a0],[0x89e],arg1,arg0,0; bx=&[0x2da8]; ax=arg2,dx=arg3; lcall 0xc11,0xc. */
    overlay_call_0C11_000C();
    return 0;
}

/* @asm        0x002B38..0x002B72  (58 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002B38_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10, 12, 14]
 * @lcalls     2 (0x0C28:0xA, 0x0C11:0xC)
 * @inferred_role  set colour=arg4 and blit string (arg0,arg1) at column arg2/row arg3.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002B38.asm -- like func_002AFE but the colour is
 * the explicit arg4 (du=bx=dx=arg4): set style (0x0C28:0xA) then blit the string
 * (arg0,arg1) at x=arg2,y=arg3, palette [0x2DA8] via 0x0C11:0xC. */
int func_002B38_op_sz_58(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E)
{
    /* @asm 0x002B40 di=arg2(@bp+0xa); si=arg4(@bp+0xe); push si; dx=bx=si; ax=0xffff; lcall 0xc28,0xa. */
    overlay_call_0C28_000A();
    /* @asm 0x002B50 push [0x8a0],[0x89e],arg1,arg0,0; bx=&[0x2da8]; ax=arg2,dx=arg3; lcall 0xc11,0xc. */
    overlay_call_0C11_000C();
    return 0;
}

/* @asm        0x002B72..0x002BC7  (85 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002B72_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10, 12, 14]
 * @lcalls     2 (0x0C28:0xA, 0x0C2A:6 measure, 0x0C11:0xC)
 * @inferred_role  right-justify string (arg0,arg1) ending at column arg2, colour arg4.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002B72.asm -- right-justify: set style colour=arg4
 * (0x0C28:0xA), measure the string width (0x0C2A:6), subtract it from the start
 * column arg2 (si = arg2 - width), then blit (arg0,arg1) left-shifted to that
 * column via 0x0C11:0xC; returns the new column. */
int func_002B72_op_sz_85(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E)
{
    int si;    /* running column */

    /* @asm 0x002B7D push arg4; dx=bx=arg4; ax=0xffff; lcall 0xc28,0xa (style). */
    overlay_call_0C28_000A();
    /* @asm 0x002B8A push [0x8a0],[0x89e],arg1,arg0; ax=0; lcall 0xc2a,6 -> width; si = arg2 - width. */
    si = (int)arg2_bp_0A - overlay_call_0C2A_0006();
    /* @asm 0x002BA1 push [0x8a0],[0x89e],arg1,arg0,0; ax=si; bx=&[0x2da8]; dx=arg3; lcall 0xc11,0xc. */
    overlay_call_0C11_000C();
    /* @asm 0x002BC1 mov ax,si (return the column). */
    return si;
}

/* @asm        0x002BC8..0x002C0C  (68 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002BC8_unknown.asm
 * @pattern    UNKNOWN
 * @inferred_role  vertically-centre a glyph/sprite: compute a clamped y from the
 *                 measured height (func_002AC6) and forward to the blit (func_002B38)
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: the two near targets are far functions called via the `push cs; call near`
 * large-model idiom (both do `retf`).  func_002AC6 takes (arg0,arg1) and returns a
 * size-1; func_002B38 takes 5 stack args.  Caller is cdecl (cleans its own pushes).
 */
void func_002BC8_logic_sz_68(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E, uint16_t arg5_bp_10)
{
    /* @asm 0x002BD0 args arg5,arg4 pre-pushed for the outer func_002B38 call.
     * @asm 0x002BD9 push arg1,arg0; 0x002BDE call func_002AC6 -> ax (a measured span). */
    int measured = func_002AC6_logic_sz_27(arg0_bp_06, arg1_bp_08);

    /* @asm 0x002BE4 sar ax,1 (measured/2, signed); 0x002BE6 cx=arg3; sar cx,1 (arg3/2).
     * @asm 0x002BEF si = arg3/2 - measured/2; 0x002BF1 si += arg2.
     * @asm 0x002BF4 or si,si; jge -> if si < 0 si = 0 (clamp to >= 0).
     * (sar = arithmetic >>1, floor-toward-negative; rendered as signed >> 1.) */
    int y = ((int16_t)arg3_bp_0C >> 1) - (measured >> 1) + (int16_t)arg2_bp_0A;
    if (y < 0)
        y = 0;

    /* @asm 0x002BFE push si(=y),arg1,arg0; 0x002C02 call func_002B38 with
     * (arg0, arg1, y, arg4, arg5); 0x002C05 add sp,0xa cleans all 5 words. */
    func_002B38_op_sz_58(arg0_bp_06, arg1_bp_08, (uint16_t)y, arg4_bp_0E, arg5_bp_10);
}

/* @asm        0x002C0C..0x002C4A  (62 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002C0C_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10, 12]
 * @lcalls     2 (0x0C28:0xA, 0x0C11:0xC)
 * @inferred_role  blit string (arg0,arg1) with colour [0x830] outline [0x833] (alt font).
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002C0C.asm -- twin of func_002AFE for the alternate
 * font ([0x268A]/[0x268C]): set style from fill colour [0x830] and outline [0x833]
 * (0x0C28:0xA), then blit the string (arg0,arg1) at x=arg2,y=arg3 (0x0C11:0xC). */
int func_002C0C_op_sz_62(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    /* @asm 0x002C13 push 0; dl=[0x830],dh=0; bl=[0x833],bh=0; ax=0xffff; lcall 0xc28,0xa. */
    overlay_call_0C28_000A();
    /* @asm 0x002C29 push [0x268c],[0x268a],arg1,arg0,0; bx=&[0x2da8]; ax=arg2,dx=arg3; lcall 0xc11,0xc. */
    overlay_call_0C11_000C();
    return 0;
}

/* @asm        0x002C4A..0x002C82  (56 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002C4A_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10, 12, 14, 16]
 * @lcalls     2 (0x0C28:0xA, 0x0C11:0xC)
 * @inferred_role  blit string (arg0,arg1) at (arg2,arg3) with style (arg4,arg5), alt font.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002C4A.asm -- alt-font string blit with explicit
 * style (fill=arg4, outline=arg5): set style (0x0C28:0xA) then blit (arg0,arg1)
 * at x=arg2,y=arg3 via 0x0C11:0xC. */
int func_002C4A_op_sz_56(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E, uint16_t arg5_bp_10)
{
    /* @asm 0x002C51 push 0; ax=0xffff; dx=arg4; bx=arg5; lcall 0xc28,0xa. */
    overlay_call_0C28_000A();
    /* @asm 0x002C61 push [0x268c],[0x268a],arg1,arg0,0; bx=&[0x2da8]; ax=arg2,dx=arg3; lcall 0xc11,0xc. */
    overlay_call_0C11_000C();
    return 0;
}

/* @asm        0x002C82..0x002CE0  (94 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002C82_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 4
 * @args_seen  [6, 8, 10, 12, 14, 16]
 * @lcalls     2 (0x0C28:0xA, 0x0C2A:6 measure, 0x0C11:0xC)
 * @inferred_role  right-justify string (arg0,arg1) ending at arg2 with style (arg4,arg5).
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002C82.asm -- alt-font right-justify: set style
 * (fill=arg4, outline=arg5) via 0x0C28:0xA, measure width (0x0C2A:6),
 * si = arg2 - width, blit (arg0,arg1) at that column (0x0C11:0xC); return column. */
int func_002C82_op_sz_94(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E, uint16_t arg5_bp_10)
{
    int si;

    /* @asm 0x002C8E push 0; ax=0xffff; dx=arg4; bx=arg5; lcall 0xc28,0xa (style). */
    overlay_call_0C28_000A();
    /* @asm 0x002C9E push [0x268c],[0x268a],arg1,arg0; ax=0; lcall 0xc2a,6 -> width; si = arg2 - width. */
    si = (int)arg2_bp_0A - overlay_call_0C2A_0006();
    /* @asm 0x002CBA push [0x268c],[0x268a],arg1,arg0,0; ax=si; bx=&[0x2da8]; dx=arg3; lcall 0xc11,0xc. */
    overlay_call_0C11_000C();
    /* @asm 0x002CDA mov ax,si (return the column). */
    return si;
}

/* @asm        0x002CE0..0x002D27  (71 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002CE0_unknown.asm
 * @pattern    UNKNOWN
 * @inferred_role  vertically-centre variant (twin of func_002BC8): clamp a y from
 *                 func_002AE2's measured span and forward to the blit func_002C4A
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: same shape as func_002BC8; func_002AE2 measures (arg0,arg1), func_002C4A
 * takes 6 stack args.  Both far, called via `push cs; call near`.
 */
void func_002CE0_logic_sz_71(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E, uint16_t arg5_bp_10, uint16_t arg6_bp_12)
{
    /* @asm 0x002CE8 args arg6,arg5,arg4 pre-pushed for the outer func_002C4A call.
     * @asm 0x002CF5 push arg1,arg0; 0x002CF9 call func_002AE2 -> ax (measured span). */
    int measured = func_002AE2_logic_sz_27(arg0_bp_06, arg1_bp_08);

    /* @asm 0x002CFF sar ax,1; 0x002D01 cx=arg3; sar cx,1; 0x002D0A si=arg3/2-measured/2;
     * @asm 0x002D0C si += arg2; 0x002D0F or si,si; jge -> if si < 0 si = 0.
     * (sar = arithmetic >>1; rendered as signed >> 1.) */
    int y = ((int16_t)arg3_bp_0C >> 1) - (measured >> 1) + (int16_t)arg2_bp_0A;
    if (y < 0)
        y = 0;

    /* @asm 0x002D19 push si(=y),arg1,arg0; 0x002D1D call func_002C4A with
     * (arg0, arg1, y, arg4, arg5, arg6); 0x002D20 add sp,0xc cleans all 6 words. */
    func_002C4A_op_sz_56(arg0_bp_06, arg1_bp_08, (uint16_t)y,
                         arg4_bp_0E, arg5_bp_10, arg6_bp_12);
}

/* @asm        0x002D28..0x002D73  (75 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002D28_unknown.asm
 * @pattern    DISPATCHER
 * @inferred_role  draw a glyph (arg0) using a colour/style word selected by code arg1:
 *                 table[arg1] when arg1>=0 (else default), plus a second overdraw pass
 *                 when arg1 is in the 8..0x17 band.
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: word table at DGROUP 0x2F74, stride 0x10 (BSS runtime, DGROUP_MEMORY_MAP §2);
 * 0x2E0A and 0x2DB0 are default-style near words.  Targets are far (`push cs; call near`).
 */
void func_002D28_logic_sz_75(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    int code = (int16_t)arg1_bp_08;
    uint16_t style;

    /* @asm 0x002D30 or si,si; jl 0x2D42 -> if (code >= 0) style = word[code*0x10 + 0x2F74]
     * @asm 0x002D45 else style = [0x2E0A]. */
    if (code >= 0)
        style = DG16(0x2F74 + (unsigned)arg1_bp_08 * 0x10);
    else
        style = DG16(0x2E0A);

    /* @asm 0x002D49 push arg0; 0x002D4B call func_002992(arg0, style). */
    func_002992_rtl_sz_26(arg0_bp_06, style);

    /* @asm 0x002D51 cmp si,8; jl ; 0x002D56 cmp si,0x18; jge -> only when 8 <= code < 0x18: */
    if (code >= 8 && code < 0x18) {
        /* @asm 0x002D5D call func_0028B0(arg0)  (return value discarded). */
        func_0028B0(arg0_bp_06);
        /* @asm 0x002D63 push [0x2DB0]; 0x002D69 call func_002992(arg0, [0x2DB0]). */
        func_002992_rtl_sz_26(arg0_bp_06, DG16(0x2DB0));
    }
}

/* @asm        0x002D74..0x002E4E  (218 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002D74_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 0xc; push dx; push ax; push si  (dx/bx/ax are register args)
 * @inferred_role  size one stacked-bar row: choose a sub-bar count and a binary
 *                 shift, returning the per-row geometry through three out-pointers.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 *
 * Calling convention (large model, retf 0xe -> 7 stack words; 3 register args):
 *   register  ax = kind_index (-> [bp-0x10]),  dx = total (-> [bp-0xe], also guard),
 *             bx = guard2
 *   stack     [bp+6]  flags
 *             [bp+8]  out_shift   (near ptr; *out_shift starts 0, grows by 1)
 *             [bp+0xa] out_w      (near ptr; receives the leftover width)
 *             [bp+0xc] lo         (a lower-bound coordinate)
 *             [bp+0xe] avail      (available width)
 *             [bp+0x12] out_acc   (near ptr; += width/2)
 *   returns   count (ax)
 *
 * Re-signatured to take real C pointers for the three near-pointer out-params
 * (no external callers -- see grep in the porting notes); the register args are
 * surfaced as explicit parameters. */
/* PORTED 2026-06-09 from func_002D74.asm -- given the kind's base width from the
 * record table es:[0x83E] (+0x3E, +2 border when flags&2) and the requested
 * total/avail, divide avail by (total-1) to get a candidate sub-bar count clamped
 * to [1, base_w+1], grow the binary shift until (count*(total-1) >> shift) fits
 * the remaining width, and write back the leftover width and half-width
 * accumulator.  Returns the chosen count (0 when either guard word is zero). */
int func_002D74_logic_sz_218(uint16_t flags, int16_t *out_shift, int16_t *out_w,
                             uint16_t lo, uint16_t avail, int16_t *out_acc,
                             int16_t total, int16_t guard2, int16_t kind_index)
{
    int count = 0;        /* [bp-0xa] */
    int base_w;           /* [bp-2]   */
    int rem_w;            /* [bp-0xc] */
    int span;             /* [bp-4]   */
    int seg = 0;          /* [bp-6]   */
    int shift = 0;
    uint8_t far *rec;

    (void)lo;

    /* @asm 0x002D80 if (dx==0) goto done; @0x002D87 if (bx==0) goto done. */
    if (total == 0)            /* or dx,dx; jne 0x2d87 else jmp 0x2e46 */
        goto done;
    if (guard2 == 0)           /* or bx,bx; jne 0x2d8e else jmp 0x2e46 */
        goto done;

    /* @asm 0x002D8E *out_shift = 0. */
    *out_shift = 0;

    /* @asm 0x002D95 si=kind_index; base_w = es:[0x83E][si*0x24 + 0x3E]. */
    rec = *(uint8_t far * far *)DG_PTR(0x083E);
    base_w = *(int16_t far *)(rec + (int)kind_index * 0x24 + 0x3E);

    /* @asm 0x002DAC if (flags & 2) base_w += 2. */
    if (flags & 2)
        base_w += 2;
    /* @asm 0x002DB7 rem_w = avail - base_w. */
    rem_w = (int16_t)avail - base_w;

    /* @asm 0x002DC0 if (total > 1) count = clamp(avail/(total-1), 1, base_w+1) else count=1. */
    if (total > 1) {
        int q = (int16_t)avail / (total - 1);   /* idiv */
        if (q > base_w + 1) q = base_w + 1;     /* cmp ax,cx; jle */
        if (q < 1) q = 1;                       /* cmp ax,1; jge */
        count = q;
    } else {
        count = 1;
    }

    /* @asm 0x002DE9 span = (total - 1) * count; (ax then sar'd by [bp-4]'s shift). */
    span = (total - 1) * count;

    /* @asm 0x002DF3..0x002E12 grow *out_shift until (span >> shift) <= rem_w. */
    shift = *out_shift;
    for (;;) {
        /* @asm 0x002DFF/0x002E0A seg/check = (span >> shift) + base_w / (span >> shift). */
        if ((span >> shift) <= rem_w)   /* @asm cmp ax,[bp-0xc]; jg 0x2df6 -> keep looping */
            break;
        (*out_shift)++;                 /* @asm inc word ptr [bx] */
        shift = *out_shift;
    }
    /* seg = (span >> shift) + base_w (value used for the leftover below). */
    seg = (span >> shift) + base_w;

    /* @asm 0x002E14 top = (total-1 > seg) ? total : avail; top -= seg. */
    {
        int top = ((total - 1) > seg) ? (int)total : (int16_t)avail;
        top -= seg;
        /* @asm 0x002E2B if ([bp+0xa] out_w != 0) *out_w = top. */
        if (out_w)
            *out_w = (int16_t)top;
        /* @asm 0x002E36 if ([bp+0xc] lo != 0) *out_acc += top >> 1. */
        if (lo != 0 && out_acc)
            *out_acc = (int16_t)(*out_acc + (top >> 1));
    }

done:
    /* @asm 0x002E46 return count. */
    return count;
}

/* @asm        0x002E4E..0x002EE3  (149 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002E4E_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   ENTER 0x16
 * @args_seen  [6, 8, 10, 12, 14]
 * @lcalls     4 (0x0D1D:0x08FA fmt, 0x0C2A:6 measure, 0x0B9E:0xA text, 0x0C28:0xA, 0x0C11:0xC)
 * @inferred_role  draw a small numeric badge: format the value, optionally draw it as
 *                 text, then blit a coloured chip behind/around it.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 */
/* PORTED 2026-06-09 from func_002E4E.asm -- numeric-chip drawer.  If value
 * arg0<=0 do nothing.  Otherwise format arg0 (0x0D1D:0x08FA) into a 0x16-byte
 * buffer, measure it (0x0C2A:6 -> width-1 into [bp-2]); when arg4!=0 draw the
 * number text shifted right of (arg1,arg2) using the proportional font
 * (0x0B9E:0xA); finally set the chip colour=arg3 (0x0C28:0xA) and blit the chip
 * sprite at (arg1+1,arg2+1) via 0x0C11:0xC. */
int func_002E4E_rtl_sz_149(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E)
{
    char buf[0x16];   /* [bp-0x16] formatted-number scratch */
    int  w;           /* [bp-2] measured width - 1 */

    /* @asm 0x002E52 if ((int)arg0 <= 0) return. */
    if ((int16_t)arg0_bp_06 <= 0)          /* jg 0x2e5b else jmp 0x2ee1 */
        return 0;

    /* @asm 0x002E5B arg2 += 2; push 0xa,&buf,arg0; lcall 0xd1d,0x8fa (itoa). */
    arg2_bp_0A += 2;
    overlay_call_0D1D_08FA();

    /* @asm 0x002E70 push [0x8a0],[0x89e],ss,&buf; ax=0; lcall 0xc2a,6; dec ax; w=ax. */
    w = overlay_call_0C2A_0006() - 1;

    /* @asm 0x002E88 if (arg4 != 0) draw the number text via 0xb9e,0xa at (arg1,arg2). */
    if (arg4_bp_0E != 0) {
        /* @asm 0x002E8E push [0x2dae..0x2da8],7,0; bx=w+2; ax=arg1,dx=arg2; lcall 0xb9e,0xa. */
        overlay_call_0B9E_000A();
    }

    /* @asm 0x002EB1 push arg3; ax=0xffff; dx=bx=arg3; lcall 0xc28,0xa (chip colour). */
    overlay_call_0C28_000A();
    /* @asm 0x002EC1 push [0x8a0],[0x89e],ss,&buf,0; ax=arg1+1,dx=arg2+1; bx=&[0x2da8]; lcall 0xc11,0xc. */
    overlay_call_0C11_000C();
    (void)buf; (void)w;
    return 0;
}

/* @asm        0x002EE4..0x00304A  (358 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_002EE4_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 0x1a
 * @args_seen  [6, 8, 10, 12, 14, 16]
 * @lcalls     3 (0x0C36:0xA tile-blit x2, 0x012B:0x015C separator)
 * @near_calls 3 (0x002D74 sizer, 0x002E4E badge x2)
 * @inferred_role  draw a full horizontal stacked progress bar with tick marks and two
 *                 numeric badges.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 *
 * Signature (retf 0xc -> 6 stack words consumed):
 *   func(uint16_t flags@bp+6, uint16_t arg1@bp+8, uint16_t x@bp+0xa,
 *        uint16_t y@bp+0xc, uint16_t row@bp+0xe, uint16_t cap@bp+0x10) -> ax
 */
/* PORTED 2026-06-09 from func_002EE4.asm -- render a horizontal stacked bar.
 * Calls the sizer func_002D74 to get the per-step count [bp-0x16] and shift
 * [bp-0x14]; if it returns 0 bail.  Then walks rows ([bp-0x10] from 0 to
 * (cap>>shift)): for each it blits filled segment tiles via overlay 0x0C36:0xA
 * (colour cell [0x83E]:[0x840]), draws the every-other-step separator dot via
 * 0x012B:0x015C when flags&2, and advances the running pixel offset [bp+0x10].
 * Finally, when the "show numbers" predicate ([0x70] or step==1 with width>1)
 * holds, draws the two count badges (filled / capacity) via func_002E4E. */
int func_002EE4_op_sz_358(uint16_t flags_bp_06, uint16_t arg1_bp_08, uint16_t lo_bp_0A,
                          uint16_t mid_bp_0C, uint16_t y_bp_0E, uint16_t cap_bp_10,
                          int16_t reg_dx, int16_t reg_bx, int16_t reg_ax)
{
    /* [bp-0x1c]=bx, [bp-0x1e]=dx, [bp-0x20]=ax  (the three register args). */
    int   r_bx = reg_bx;     /* [bp-0x1c] */
    int   r_dx = reg_dx;     /* [bp-0x1e] */
    int   r_ax = reg_ax;     /* [bp-0x20] */

    int   count;             /* [bp-0x16] sizer result            */
    int16_t shift_w = 0;     /* [bp-0x14] binary shift            */
    int16_t out_w   = 0;     /* [bp-4]    leftover width from sizer*/
    int   acc       = 0;     /* [bp-8]    running fill accumulator */
    int   cap_sh    = (int16_t)arg1_bp_08;  /* [bp-0xa] arg1 >> shift  */
    int   fill      = 0;     /* [bp-6]    fill value                */
    int   fill_sh   = 0;     /* [bp-0x18] fill >> shift             */
    int   inner     = 0;     /* [bp-0xc]  r_dx >> shift             */
    int   nrows     = 0;     /* [bp-0x1a] r_bx >> shift (row count) */
    int   row;               /* [bp-0xe]  current cap copy          */
    int   step;              /* [bp-0x10] step index                */
    int   last_full = 0;     /* [bp-0x12] index of last full step   */
    int   show_num;          /* [bp-2]                              */

    /* @asm 0x002EEB [bp-0x12]=0; call func_002D74(out_shift=&shift_w, out_w=&out_w,
     *      lo=[bp+0xa], avail=[bp+0xc], out_acc=&[bp+0x10]; flags; regs dx/bx/ax). */
    last_full = 0;
    count = func_002D74_logic_sz_218(flags_bp_06, &shift_w, &out_w,
                                     lo_bp_0A, mid_bp_0C,
                                     (int16_t *)&cap_bp_10,   /* out_acc = &[bp+0x10] */
                                     r_dx, r_bx, r_ax);
    /* @asm 0x002F0C if (count == 0) goto done. */
    if (count == 0)
        goto done;

    /* @asm 0x002F16 acc=0; cap_sh = arg1; fill = fill_sh = -(arg1 - r_bx). */
    acc     = 0;
    cap_sh  = (int16_t)arg1_bp_08;
    fill    = -(cap_sh - r_bx);
    fill_sh = fill;

    /* @asm 0x002F2C cl=shift; cap_sh>>=cl; fill_sh>>=cl; inner=r_dx>>cl; nrows=r_bx>>cl. */
    {
        int cl = (int)shift_w;
        cap_sh  >>= cl;
        fill_sh >>= cl;
        inner = r_dx >> cl;
        nrows = r_bx >> cl;
    }

    /* @asm 0x002F45 if (shift!=0 && ((cap_sh & fill) & 1)) inner++. */
    if (shift_w != 0 && ((cap_sh & fill) & 1))
        inner++;

    /* @asm 0x002F58 row = cap[bp+0x10]; step = 0. */
    row  = (int16_t)cap_bp_10;
    step = 0;

    /* @asm 0x002FD9 while (step < nrows) { ... } */
    while (step < nrows) {
        /* @asm 0x002F66 draw the filled segment tile (push [0x840],[0x83e],y+1;
         *      ax=r_ax; bx=&[0x2da8]; dx=row; lcall 0xc36,0xa). */
        overlay_call_0C36_000A();

        /* @asm 0x002F82 if (fill_sh == step) last_full = row(=[bp+0x10]). */
        if (fill_sh == step)
            last_full = (int16_t)cap_bp_10;
        /* @asm 0x002F90 if (fill_sh <= step) draw the end-cap tile id 0x38. */
        if (fill_sh <= step) {
            overlay_call_0C36_000A();      /* end-cap tile (id 0x38) */
        }

        /* @asm 0x002FB4 row += count; @0x002FBA if (flags & 1) draw the sub-ticks. */
        row += count;
        if (flags_bp_06 & 1) {
            /* @asm 0x002FC0 acc += out_w; then 0x002FC8 loop: acc -= out_w; row++;
             *      while (acc >= inner). */
            acc += out_w;
            while (acc >= inner) {
                acc -= out_w;
                row++;
            }
        }

        /* @asm 0x002FE1 when flags&2: draw the separator dot via 0x012b,0x15c. */
        if (flags_bp_06 & 2) {
            overlay_call_012B_015C();
        }
        step++;                            /* @asm 0x002FD6 inc step */
    }

    /* @asm 0x002FFE show_num = [0x70]; if (count==1 && r_bx>1) show_num = 1. */
    show_num = (int16_t)DG16(0x0070);
    if (count == 1 && r_bx > 1)
        show_num = 1;

    /* @asm 0x003015 if (show_num != 0) draw the two count badges. */
    if (show_num != 0) {
        /* @asm 0x00301B func_002E4E(value=fill, x=row+2, y=[bp+0xe], col=0xf, flag=1). */
        func_002E4E_rtl_sz_149((uint16_t)fill, (uint16_t)(row + 2), y_bp_0E, 0x0F, 1);
        /* @asm 0x003032 func_002E4E(value=cap_sh, x=last_full+2, y=[bp+0xe], col=0xc, flag=1). */
        func_002E4E_rtl_sz_149((uint16_t)cap_sh, (uint16_t)(last_full + 2), y_bp_0E, 0x0C, 1);
    }

done:
    (void)r_ax;
    /* @asm 0x003046 leave; retf 0xc. */
    return 0;
}

/* @asm        0x00304A..0x003104  (186 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00304A_unknown.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 0xc
 * @args_seen  [6, 8, 10, 12, 14]
 * @near_calls 1 (0x002D74 sizer)
 * @lcalls     1 (0x0ACB:6 cell predicate)
 * @inferred_role  hit-test which sub-bar of a stacked bar a point (arg2,arg3) lands in.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: the auto banner span (0x00304A..0x0030D8, "142 bytes") was a false cut at
 * the in-function tail; the true function is 186 bytes ending at the leave/retf
 * @0x003101 (functions.json foff=0x304A end=0x3104).
 *
 * Signature (retf 0xa -> 5 stack words; 3 register args dx/bx/ax forwarded to sizer):
 *   func(uint16_t flags@bp+6, uint16_t arg1@bp+8, uint16_t px@bp+0xa,
 *        uint16_t py@bp+0xc, uint16_t row@bp+0xe,
 *        int16_t reg_dx, int16_t reg_bx, int16_t reg_ax) -> hit index (ax, -1 = miss)
 */
/* PORTED 2026-06-09 from func_00304A.asm -- hit-test a stacked bar.  Runs the same
 * sizer func_002D74 to get per-step count [bp-0xa] and the kind's two widths from
 * the record table es:[0x83E] (base [bp-4], height [bp-8]).  Walks each step from
 * the top, calling the cell predicate overlay 0x0ACB:6 over the rect (px..px+1,
 * row..row+base-1); the first step whose predicate is true sets the result
 * [bp-0xc] = step index.  Returns that index (or the initial -1 on a miss). */
int func_00304A_logic_sz_142(uint16_t flags_bp_06, uint16_t arg1_bp_08, uint16_t px_bp_0A,
                             uint16_t py_bp_0C, uint16_t row_bp_0E,
                             int16_t reg_dx, int16_t reg_bx, int16_t reg_ax)
{
    int   result = -1;    /* [bp-0xc] */
    int   count;          /* [bp-0xa] */
    int   base_w;         /* [bp-4]   */
    int   height;         /* [bp-8]   */
    int   step;           /* [bp-2]   */
    int   kind_idx;       /* si = [bp-0x12] = entry ax */
    int16_t shift_w = 0;  /* [bp-6]  sizer's out_shift */
    uint8_t far *rec;

    (void)arg1_bp_08; (void)px_bp_0A;

    /* @asm 0x003057 call func_002D74(out_shift=&shift_w, out_w=0, lo=[bp+8],
     *      avail=[bp+0xa], (bp+0x10)=[bp+0xc], out_acc=&[bp+0xe](=&row); flags; regs dx/bx/ax). */
    count = func_002D74_logic_sz_218(flags_bp_06, &shift_w, (int16_t *)0,
                                     arg1_bp_08, px_bp_0A, (int16_t *)&row_bp_0E,
                                     reg_dx, reg_bx, reg_ax);
    /* @asm 0x003074 if (count == 0) goto done. */
    if (count == 0)
        goto done;

    /* @asm 0x00307B si=[bp-0x12]=entry ax; rec=es:[0x83E]; base_w = rec[si*0x24+0x3E]. */
    kind_idx = (int16_t)reg_ax;
    rec = *(uint8_t far * far *)DG_PTR(0x083E);
    base_w = *(int16_t far *)(rec + kind_idx * 0x24 + 0x3E);
    /* @asm 0x003092 if (flags & 2) base_w += 2. */
    if (flags_bp_06 & 2)
        base_w += 2;
    /* @asm 0x00309D height = rec[si*0x24+0x40]. */
    height = *(int16_t far *)(rec + kind_idx * 0x24 + 0x40);

    /* @asm 0x0030B0 step = reg_bx - 1; row[bp+0xe] += (reg_bx-1)*count (jump to bottom). */
    step = reg_bx - 1;
    row_bp_0E = (uint16_t)((int16_t)row_bp_0E + ((reg_bx - 1) * count));

    /* @asm 0x0030F6..0x0030C2 walk steps from the bottom up while result < 0: */
    while (result < 0) {                    /* cmp [bp-0xc],0; jl 0x30c2 */
        if (step < 0)                       /* @asm cmp [bp-2],0; jl 0x30fc */
            break;
        /* @asm 0x0030C8 predicate over (py..py+height) x (row..row+base_w-1) via 0xacb,6. */
        if (overlay_call_0ACB_0006() != 0) {  /* @asm or ax,ax; je 0x30ed */
            /* @asm 0x0030E7 result = step. */
            result = step;
        }
        /* @asm 0x0030F0 row -= count; step--. */
        row_bp_0E = (uint16_t)((int16_t)row_bp_0E - count);
        step--;
    }

done:
    /* @asm 0x0030FC return result (ax = [bp-0xc]). */
    (void)height;
    return result;
}

/* @asm        0x003104..0x0033E9  (741 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_003104_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 0x24
 * @args_seen  [6]
 * @lcalls     2 (0x0C36:0xA tile-blit)
 * @near_calls 2 (0x002E4E badge x2)
 * @inferred_role  draw the multi-row stacked-bar panel summarising the table at 0x2CC6
 *                 (per-row counts 0x2CCE, kinds 0x2CF4, offsets 0x2CE2) with badges.
 * @status     PORTED 2026-06-09 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: the auto banner segmented this region into a 143-byte func_003104 plus a
 * SHADOWED func_003193; the true function is one 741-byte body (0x003104..0x0033E9,
 * functions.json foff=0x3104 end=0x33E9) ending at leave/retf 2 @0x0033E6.  The
 * separately-banner'd func_003193 is the interior loop and is NOT a standalone
 * function -- it is folded in here.
 */
/* PORTED 2026-06-09 from func_003104.asm -- render the whole stacked-bar summary
 * panel for the layout tables in DGROUP 0x2CC6..0x2CF5 (row count [0x2CE0]).
 * Pass 1 (0x3122) totals the per-row counts ([0x2CCE]) and accumulates the
 * widths; pass 2 (0x3150) sums the per-row record widths from es:[0x83E].  It
 * then derives a uniform binary shift [bp-0x1c] so every row fits the field
 * arg0, and per row draws its segment tiles via overlay 0x0C36:0xA (normal id,
 * end-cap 0x38, selected 0x3A based on the [0x2CF5] flag bits) and, when the
 * row's "show numbers" predicate holds, two count badges via func_002E4E. */
int func_003104_logic_sz_143(uint16_t arg0_bp_06, int16_t reg_ax, int16_t reg_dx, int16_t reg_bx)
{
    /* Register args: ax -> run_x init ([bp-0x2a]), dx -> baseline y ([bp-0x28]),
     * bx -> x-origin offset ([bp-0x26]). */
    int run_x   = (int16_t)reg_ax;  /* [bp-0x2a] running pixel x */
    int y_base  = (int16_t)reg_dx;  /* [bp-0x28] baseline row    */
    int x_org   = (int16_t)reg_bx;  /* [bp-0x26] origin offset   */

    int total_w   = 0;    /* [bp-0x24]  sum of per-row counts             */
    int n_multi   = 0;    /* [bp-0x20]  count of rows with count > 1       */
    int extra_w   = 0;    /* [bp-0xa]   accumulated (count-1) extra width  */
    int row_total = 0;    /* [bp-0x22]  derived per-row max width          */
    int width_sum = 0;    /* [bp-0xc]   sum of record widths               */
    int shift     = 0;    /* [bp-0x1c]  uniform binary shift               */
    int field     = 0;    /* [bp-0xe]                                     */
    int x;                /* [bp-4]     fit metric                         */
    int row;              /* [bp-0x16]  row index                         */
    int ax, cl;

    int seg_top;          /* [bp-8]   threshold step                       */
    int sel_mark;         /* [bp-0x18] run_x at the threshold step         */
    int run_snap;         /* [bp-0x12] run_x snapshot at row start         */
    int row_w;            /* [bp-0x1a] */
    int step;             /* [bp-0x14] */
    int color_id;         /* [bp-0x1e] */
    int show_num;         /* [bp-2]   */
    uint8_t far *rec;
    int kind, recw;

    (void)y_base;

    /* ----- pass 1 @0x3122: total the per-row counts at [0x2CCE] (stride 2) ----- */
    /* @asm row=0; while ([0x2CE0] > row) { ax=[0x2CCE][row]; total_w+=ax;
     *      if (ax>1){ n_multi++; extra_w += ax-1; } row++; } */
    for (row = 0; (int16_t)DG16(0x2CE0) > row; row++) {
        ax = (int16_t)DG16(0x2CCE + row * 2);
        total_w += ax;
        if (ax > 1) {
            n_multi++;
            extra_w += ax - 1;
        }
    }
    (void)total_w;

    /* ----- pass 2 @0x3150: sum the record widths from es:[0x83E] ----- */
    /* @asm row=0; while ([0x2CE0]>row){ si=[0x2CF4][row]&0xfff; width_sum +=
     *      es:[0x83E][si*0x24+0x3e]; row++; } */
    width_sum = 0;
    rec = *(uint8_t far * far *)DG_PTR(0x083E);
    for (row = 0; (int16_t)DG16(0x2CE0) > row; row++) {
        kind = DG16(0x2CF4 + row * 2) & 0x0FFF;
        width_sum += *(int16_t far *)(rec + kind * 0x24 + 0x3E);
    }

    /* ----- derive the uniform shift @0x317C..0x31CC ----- */
    /* @asm field=0; do { cx = max(0, -([0x2CE0]*field - width_sum));
     *      x = (1-[0x2CE0])*arg0 - cx + x_org;
     *      if (x < n_multi){ if(arg0>0) arg0--; else if(cx>0) field++; else x=n_multi; }
     *   } while (n_multi > x); */
    field = 0;
    for (;;) {
        int cx;
        ax = (int16_t)DG16(0x2CE0) * field - width_sum;
        ax = -ax;
        if (ax < 0) ax = 0;             /* @asm or ax,ax; jge -> else sub ax,ax */
        cx = ax;
        ax = (1 - (int16_t)DG16(0x2CE0)) * (int16_t)arg0_bp_06 - cx + x_org;
        x = ax;                         /* [bp-4] */
        if (x < n_multi) {              /* @asm cmp ax,[bp-0x20]; jge 0x31c6 */
            if ((int16_t)arg0_bp_06 > 0)      /* @asm cmp arg0,0; jle 0x31b6 */
                arg0_bp_06--;
            else if (cx > 0)                  /* @asm or cx,cx; jle 0x31c0 */
                field++;
            else
                x = n_multi;                  /* @asm 0x31c0 [bp-4]=n_multi */
        }
        if (n_multi <= x)               /* @asm cmp [bp-0x20],ax; jg 0x3181 (loop) */
            break;
    }

    /* @asm 0x31CE if (extra_w != 0) { row_total = x / extra_w; if (row_total==0)
     *      grow shift until (extra_w >> shift) <= x; } */
    if (extra_w != 0) {
        row_total = x / extra_w;        /* @asm idiv [bp-0xa] -> [bp-0x22] */
        if (row_total == 0) {
            shift = 0;
            do {
                shift++;                /* @asm inc [bp-0x1c] */
                cl = shift;
            } while ((extra_w >> cl) > x);   /* @asm sar ax,cl; cmp ax,[bp-4]; jg 0x31df */
        }
    }

    /* ----- main render loop @0x31F4..0x33E4 over each row ----- */
    /* @asm row = 0; while ([0x2CE0] > row) { color_id=...; <body>; row++ } */
    for (row = 0; (int16_t)DG16(0x2CE0) > row; row++) {
        int rowcnt = (int16_t)DG16(0x2CCE + row * 2);

        /* @asm 0x33AF select color_id: if (row_total==0) color_id=1, else
         *      color_id = min(es:[0x83E][kind*0x24+0x3e]+1, row_total). */
        if (row_total == 0) {                  /* @asm 0x33b5 jmp 0x31f8 */
            color_id = 1;
        } else {
            kind = DG16(0x2CF4 + row * 2) & 0x0FFF;
            ax = *(int16_t far *)(rec + kind * 0x24 + 0x3E) + 1;
            if (ax > row_total) ax = row_total;
            color_id = ax;
        }

        cl = shift;
        /* @asm 0x31FD row_w = [0x2CCE][row] - [0x2CE2][row]; seg_top = row_w >> shift. */
        row_w    = (int16_t)DG16(0x2CCE + row * 2) - (int16_t)DG16(0x2CE2 + row * 2);
        seg_top  = row_w >> cl;
        /* @asm 0x3215 run_snap = run_x; sel_mark = -1; step = 0. */
        run_snap = run_x;
        sel_mark = -1;
        step     = 0;

        /* @asm 0x329C per-step loop: while ((count >> shift) > step). */
        while (((int16_t)DG16(0x2CCE + row * 2) >> cl) > step) {
            int draw_normal = 1;

            /* @asm 0x32AF if (step == seg_top) sel_mark = run_x. */
            if (step == seg_top)
                sel_mark = run_x;

            /* @asm 0x32BD choose the tile: when flag&0x40 and step>=seg_top draw the
             *      "selected" cap id 0x3a instead of the normal segment. */
            if ((DG8(0x2CF5 + row * 2) & 0x40) && step >= seg_top) {
                /* @asm 0x32D7 draw id-0x3a cap tile at run_x (via 0xc36,0xa). */
                overlay_call_0C36_000A();
                draw_normal = 0;
            }

            if (draw_normal) {
                kind = DG16(0x2CF4 + row * 2);
                /* @asm 0x3228 draw the normal segment tile (kind & 0x0fff) at run_x. */
                overlay_call_0C36_000A();
                /* @asm 0x3253 draw the id-0x38 end-cap when
                 *      (kind&0x8000) || (step >= seg_top && !(kind&0x4000)). */
                if ((kind & 0x8000) || (step >= seg_top && !(kind & 0x4000))) {
                    overlay_call_0C36_000A();
                }
            }

            /* @asm 0x327F if ((count >> shift) - 1 > step) run_x += color_id. */
            if ((((int16_t)DG16(0x2CCE + row * 2) >> cl) - 1) > step)
                run_x += color_id;
            step++;                       /* @asm 0x3299 inc step */
        }

        /* @asm 0x32E8 show_num = [0x70]; if (color_id==1 && count>1) show_num=1. */
        show_num = (int16_t)DG16(0x0070);
        if (color_id == 1 && rowcnt > 1)
            show_num = 1;

        /* @asm 0x3305 if (show_num != 0) draw the two count badges. */
        if (show_num != 0) {
            int seg = (int16_t)DG16(0x2CE2 + row * 2);   /* [bp-6] */
            int rw  = row_w;
            /* @asm 0x3317 if (flag&0x40) { row_w += seg; seg = 0; }. */
            if (DG8(0x2CF5 + row * 2) & 0x40) {
                rw += seg;
                seg = 0;
            }
            /* @asm 0x3326 func_002E4E(rw, run_snap+2, y_base, col=(flag&0x80?0xc:0xf), 1). */
            {
                int col = (DG8(0x2CF5 + row * 2) & 0x80) ? 0x0C : 0x0F;
                func_002E4E_rtl_sz_149((uint16_t)rw, (uint16_t)(run_snap + 2),
                                       (uint16_t)y_base, (uint16_t)col, 1);
            }
            /* @asm 0x3355 func_002E4E(seg, sel_mark+2, y_base, col=(flag&0x40?0xf:0xc), 1). */
            {
                int col2 = (DG8(0x2CF5 + row * 2) & 0x40) ? 0x0F : 0x0C;
                func_002E4E_rtl_sz_149((uint16_t)seg, (uint16_t)(sel_mark + 2),
                                       (uint16_t)y_base, (uint16_t)col2, 1);
            }
        }

        /* @asm 0x337C run_x += es:[0x83E][kind*0x24+0x3e] - field + arg0. */
        kind = DG16(0x2CF4 + row * 2) & 0x0FFF;
        recw = *(int16_t far *)(rec + kind * 0x24 + 0x3E);
        run_x += recw - field + (int16_t)arg0_bp_06;
    }

    return 0;   /* @asm 0x33E4 leave; retf 2 */
}

/* ============================================================================
 * The SEPARATOR-APPEND wrapper family -- file 0x2648..0x2991  [BYTE_VERIFIED
 * 2026-06-12, full bodies disassembled from VICEROY.EXE]
 * ----------------------------------------------------------------------------
 * Each tiny body strcats ONE literal from the DGROUP separator table
 * (DS:0x50.." ", 0x52..", ", 0x55..": ", 0x58..".  ", 0x5C.."%", 0x5E.."(",
 * 0x60..")", 0x62.."{", 0x64.."}", 0x66.."+", 0x68.."-", 0x6A.."x") onto the
 * caller's buffer via 0x0D1D:0x7A4 (msc_strcat), or formats a number into a
 * stack scratch then appends it to the TOOLTIP buffer via func_00260E.
 * Thunk window names: 0x181F:0x18C(0x28B0)/0x196(0x28C0)/0x1B4(0x28E2)/
 * 0x1BE(0x28F2)/0x1DC(0x2902)/0x10A(0x2912)/0x11E(0x2922)/0x128(0x2932)/
 * 0x132(0x2942)/0x13C?(0x2952)/0x146(0x2962)/0x15A(0x2972)/0x164(0x2982);
 * the thunk call sites stay hit-counting stubs until each passes its dest. */
extern void msc_strcat(char *dest, const char *src);
extern void msc_itoa(int value, char *dest, int radix);
extern void msc_ltoa(long value, char *dest, int radix);

/* file 0x2648: append decimal int to the tooltip buffer */
void func_002648_tooltip_append_int(uint16_t value)
{
    char buf[20];                                /* @asm [bp-0x14] */
    msc_itoa((int)(int16_t)value, buf, 10);      /* @asm 0x002655 0x8FA radix 0xA */
    func_00260E_tooltip_append(buf);             /* @asm 0x002663 near 0x260E */
}

/* file 0x2668: append decimal LONG (lo,hi words) to the tooltip buffer */
void func_002668_tooltip_append_long(uint16_t lo, uint16_t hi)
{
    char buf[20];                                /* @asm [bp-0x14] */
    long v = (long)(((uint32_t)hi << 16) | lo);
    msc_ltoa(v, buf, 10);                        /* @asm 0x002678 0x916 radix 0xA */
    func_00260E_tooltip_append(buf);             /* @asm 0x002686 near 0x260E */
}

/* file 0x28B0: strcat(dest, " ")  (DS:0x50) */
void func_0028B0_append_space(char *dest) { msc_strcat(dest, (const char *)&DG8(0x50)); }

/* file 0x28C0: append COUNT spaces (loops the 0x28B0 body) */
void func_0028C0_append_spaces(char *dest, int16_t count)
{
    int16_t n;                                   /* @asm dx=[bp+8]; jle skip */
    for (n = 0; n < count; n++)
        func_0028B0_append_space(dest);          /* @asm 0x0028D4 call 0x28B0 */
}

/* files 0x28E2..0x2982: the one-literal strcat wrappers */
void func_0028E2_append_comma(char *dest)  { msc_strcat(dest, (const char *)&DG8(0x52)); } /* ", " */
void func_0028F2_append_colon(char *dest)  { msc_strcat(dest, (const char *)&DG8(0x55)); } /* ": " */
void func_002902_append_period(char *dest) { msc_strcat(dest, (const char *)&DG8(0x58)); } /* ".  " */
void func_002912_append_pct(char *dest)    { msc_strcat(dest, (const char *)&DG8(0x5C)); } /* "%" */
void func_002922_append_lparen(char *dest) { msc_strcat(dest, (const char *)&DG8(0x5E)); } /* "(" */
void func_002932_append_rparen(char *dest) { msc_strcat(dest, (const char *)&DG8(0x60)); } /* ")" */
void func_002942_append_lbrace(char *dest) { msc_strcat(dest, (const char *)&DG8(0x62)); } /* "{" */
void func_002952_append_rbrace(char *dest) { msc_strcat(dest, (const char *)&DG8(0x64)); } /* "}" */
void func_002962_append_plus(char *dest)   { msc_strcat(dest, (const char *)&DG8(0x66)); } /* "+" */
void func_002972_append_minus(char *dest)  { msc_strcat(dest, (const char *)&DG8(0x68)); } /* "-" */
void func_002982_append_x(char *dest)      { msc_strcat(dest, (const char *)&DG8(0x6A)); } /* "x" */
