/* ============================================================================
 * load_image_004EE6_005DF0.c -- load_image functions in file range 0x004EE6..0x005DF0
 * Auto-generated by tools/full_pipeline.py for VICEROY.
 *
 * 30 functions in this file. Each carries a citation block plus
 * an auto-traced control-flow body.  Functions marked SKELETON have body
 * content derived from control-flow but their semantics still need hand-port.
 * ============================================================================ */
#include "viceroy.h"
#include "dgroup.h"
#include "overlay_externs.h"

/* @asm        0x004EE6..0x00500F  (297 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004EE6_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 8
 * @args_seen  []
 * @lcalls     4
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x1059:0x000A
 *   - 0x09EF:0x002C
 *   - 0x09EF:0x0032  (2x)
 * @inferred_role  LARGE_LOGIC (297 bytes). 0x1059:0x000A + 0x09EF:0x002C
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_004EE6_op_sz_297(void)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x0094, 0x0096, 0x009A, 0x009E, 0x00A2, 0x0828, 0x5382
     * Writes DGROUP: 0x0094, 0x009E
     */
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x004EEF JNE 0x004EFB */ {
            if (/* JNE fallthrough cond: */ ax == 0) /* @0x004EF6 JNE 0x004EFB */ {
                goto label_0050BA;  /* @0x004EF8 */
            }
        }
        /* @0x004EFD */ overlay_call_1059_000A();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x004F07 JE 0x004F0C */ {
            goto label_0050BA;  /* @0x004F09 */
        }
        if (/* JL fallthrough cond: */ ax >= 0) /* @0x004F13 JL 0x004F24 */ {
            goto label_0050AF;  /* @0x004F21 */
        }
        /* @0x004F28 */ overlay_call_09EF_002C();
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x004F35 JNE 0x004F5E */ {
            /* @0x004F45 */ overlay_call_09EF_0032();
            if (/* JNE fallthrough cond: */ ax == 0) /* @0x004F4F JNE 0x004F82 */ {
                goto label_004F82;  /* @0x004F5B */
                /* @0x004F6C */ overlay_call_09EF_0032();
                if (/* JNE fallthrough cond: */ ax == 0) /* @0x004F76 JNE 0x004F82 */ {
                }
            }
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x004F87 JE 0x004F93 */ {
        }
        goto label_004FFA;  /* @0x004F96 */
        goto label_005016;  /* @0x004FA2 */
        goto label_005016;  /* @0x004FB0 */
        goto label_005016;  /* @0x004FBC */
        goto label_005016;  /* @0x004FC8 */
        if (/* JE fallthrough cond: */ ax != 0) /* @0x004FCF JE 0x005016 */ {
            goto label_005016;  /* @0x004FDB */
            if (/* JE fallthrough cond: */ ax != 0) /* @0x004FE3 JE 0x005016 */ {
                goto label_004FD6;  /* @0x004FEA */
                if (/* JE fallthrough cond: */ ax != 0) /* @0x004FF1 JE 0x005016 */ {
                    goto label_004FD6;  /* @0x004FF8 */
                    if (/* JA fallthrough cond: */ ax <= 0) /* @0x004FFE JA 0x005016 */ {
                    }
                }
            }
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x0050BC..0x0050EF  (51 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0050BC_unknown.asm
 * @pattern    WRAPPER_LCALL
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x02D8:0x000E
 * @inferred_role  WRAPPER_LCALL (51 bytes). 0x02D8:0x000E
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_0050BC_op_sz_51(uint16_t arg0_bp_06)
{
    /* @auto: wrapper forwards to LCALL 0x02D8:0x000E. */
    return overlay_call_02D8_000E();
}

/* @asm        0x0050F0..0x0050FB  (11 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0050F0_unknown.asm
 * @pattern    TINY_RETURN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  global setter (writes DGROUP word [0x009A])
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_0050F0_logic_sz_11(uint16_t arg0_bp_06)
{
    /* @asm 0x0050F3 mov ax,[bp+6]; 0x0050F6 mov [0x9a],ax -- setter for the
     * DGROUP word at 0x009A; returns the value written (left in ax). */
    DG16(0x009A) = arg0_bp_06;
    return arg0_bp_06;
}

/* @asm        0x0050FC..0x005107  (11 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0050FC_unknown.asm
 * @pattern    TINY_RETURN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  global setter (writes DGROUP word [0x0098])
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_0050FC_logic_sz_11(uint16_t arg0_bp_06)
{
    /* @asm 0x0050FF mov ax,[bp+6]; 0x005102 mov [0x98],ax -- setter for the
     * DGROUP word at 0x0098; returns the value written (left in ax). */
    DG16(0x0098) = arg0_bp_06;
    return arg0_bp_06;
}

/* @asm        0x005108..0x00513B  (51 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005108_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     1
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x02D8:0x000E
 *
 * Near CALL targets:
 *   - 0x0050F0
 * @inferred_role  UNKNOWN (51 bytes). 0x02D8:0x000E
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_005108_op_sz_51(uint16_t arg0_bp_06)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x009C, 0x00A0, 0x00A2
     * Writes DGROUP: 0x009E
     */
        /* @0x00510F */ func_0050F0();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00511B JE 0x005139 */ {
            if (/* JE fallthrough cond: */ ax != 0) /* @0x005122 JE 0x005131 */ {
                if (/* JNE fallthrough cond: */ ax == 0) /* @0x005129 JNE 0x005131 */ {
                }
            }
            /* @0x005134 */ overlay_call_02D8_000E();
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00513C..0x005156  (26 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00513C_unknown.asm
 * @pattern    WRAPPER_NEARCALL
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x005108
 * @inferred_role  WRAPPER_NEARCALL (26 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00513C_logic_sz_26(uint16_t arg0_bp_06)
{
    /* @auto: wrapper forwards to near CALL 0x005108. */
    return func_005108();
}

/* @asm        0x005160..0x00518D  (45 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005160_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     3
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0A58:0x0054
 *   - 0x0D1D:0x0132
 *   - 0x0A58:0x000D
 * @inferred_role  DISPATCHER (45 bytes). 0x0A58:0x0054 + 0x0D1D:0x0132
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_005160_op_sz_45(uint16_t arg0_bp_06)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x83AC
     */
        /* @0x005163 */ overlay_call_0A58_0054();
        /* @0x005178 */ overlay_call_0D1D_0132();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x005184 JE 0x00518B */ {
            /* @0x005186 */ overlay_call_0A58_000D();
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x0051D2..0x005210  (62 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0051D2_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10, 12, 14, 16, 18, 20]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (62 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_0051D2_logic_sz_62(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E, uint16_t arg5_bp_10, uint16_t arg6_bp_12, uint16_t arg7_bp_14)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x082E
     */
        if (/* JE fallthrough cond: */ ax != 0) /* @0x0051DA JE 0x005210 */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x005234..0x005272  (62 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005234_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10, 12, 14, 16, 18, 20]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (62 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_005234_logic_sz_62(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E, uint16_t arg5_bp_10, uint16_t arg6_bp_12, uint16_t arg7_bp_14)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x082C
     */
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00523C JE 0x005272 */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x005296..0x0052AC  (22 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005296_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  nudge an animated/auto-tiling sprite id by a sub-tile direction:
 *                 derive a direction 0..15 from (dir + ((x&3)+((y&3)<<2))) and step
 *                 the sprite within its group, bouncing at the group edge.
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * NOTE: true body is 134 bytes (0x005296..0x00531B); the skeleton header's 22-byte
 * span and `(void)` signature were a false auto-segmentation cut.  Register-param far
 * function: AL=sprite id, BL=direction nibble, SI=tile x, DI=tile y (no stack args).
 * All arithmetic is 8-bit; the final edge test (cmp/jae) is UNSIGNED.
 */
int func_005296_logic_sz_22(uint16_t sprite_al, uint16_t dir_bl,
                            uint16_t x_si, uint16_t y_di)
{
    /* @asm 0x00529C shift_a=2, mask_b=7 (defaults).
     * @asm 0x0052A6 dh=(x&3); 0x0052B1 ch=((y&3)<<2); 0x0052B7 dh += ch
     *      -> subtile = (x & 3) + ((y & 3) << 2)  (0..15). */
    int shift_a = 2;
    int mask_b  = 7;
    uint8_t sprite = (uint8_t)sprite_al;
    uint8_t subtile = (uint8_t)((x_si & 3) + ((y_di & 3) << 2));
    uint8_t dir, base;
    int8_t delta;

    /* @asm 0x0052B9 cmp al,0x10; jb -> if (sprite < 0x10)  return sprite (unchanged).
     * @asm 0x0052BD cmp al,0x88; jae -> if (sprite >= 0x88) return sprite. */
    if (sprite < 0x10 || sprite >= 0x88)
        return sprite;

    /* @asm 0x0052C1 cmp al,0x30; ja 0x52D0 -> if (sprite <= 0x30): shift_a=0,mask_b=0x1F
     * @asm 0x0052D0 else cmp al,0x40; ja 0x52DC -> if (sprite <= 0x40): shift_a=2,mask_b=0xF
     *      else keep the defaults (shift_a=2, mask_b=7). */
    if (sprite <= 0x30) {
        shift_a = 0;
        mask_b  = 0x1F;
    } else if (sprite <= 0x40) {
        shift_a = 2;
        mask_b  = 0x0F;
    }

    /* @asm 0x0052DC dl = (dir + subtile) & 0x0F. */
    dir = (uint8_t)((uint8_t)dir_bl + subtile) & 0x0F;

    /* @asm 0x0052E3 if (dir == 0) return sprite;  0x0052E8 if (dir == 8) return sprite. */
    if (dir == 0 || dir == 8)
        return sprite;

    /* @asm 0x0052ED ja 0x52F8: if (dir > 8)  delta =  (dir - 7) >> shift_a
     * @asm 0x0052EF else (dir < 8) delta = -((dir + 1) >> shift_a). */
    if (dir > 8)
        delta = (int8_t)((uint8_t)(dir - 7) >> shift_a);
    else
        delta = (int8_t)(-(int)((uint8_t)(dir + 1) >> shift_a));

    /* @asm 0x0052FD base = ((sprite - 0x10) & mask_b) + delta;
     * @asm 0x00530B cmp base,(mask_b+1); jae -> if stepping leaves the group
     *      (unsigned base >= mask_b+1) negate delta (bounce). */
    base = (uint8_t)(((uint8_t)(sprite - 0x10) & (uint8_t)mask_b) + (uint8_t)delta);
    if (base >= (uint8_t)(mask_b + 1))
        delta = (int8_t)(-(int)delta);

    /* @asm 0x005314 sprite += delta. */
    return (uint8_t)(sprite + (uint8_t)delta);
}

/* @asm        0x00531C..0x005375  (89 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00531C_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 0x10
 * @args_seen  [6, 8, 14, 16, 22, 24, 26, 28, 30, 32]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (89 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00531C_logic_sz_89(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0E, uint16_t arg3_bp_10, uint16_t arg4_bp_16, uint16_t arg5_bp_18, uint16_t arg6_bp_1A, uint16_t arg7_bp_1C, uint16_t arg8_bp_1E, uint16_t arg9_bp_20)
{
    /* @auto: control-flow trace from disassembly. */
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x005371 JNE 0x00537B */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x0053DE..0x00540A  (44 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0053DE_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (44 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_0053DE_logic_sz_44(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x005418..0x005436  (30 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005418_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (30 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_005418_logic_sz_30(uint16_t arg0_bp_06)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00543C..0x0054BF  (131 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00543C_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   ENTER 2
 * @args_seen  [6]
 * @lcalls     3
 * @near_calls 2
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x029F:0x0318
 *   - 0x029F:0x034C
 *   - 0x029F:0x02CC
 *
 * Near CALL targets:
 *   - 0x005418
 *   - 0x0053DE
 * @inferred_role  DISPATCHER (131 bytes). 0x029F:0x0318 + 0x029F:0x034C
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00543C_op_sz_131(uint16_t arg0_bp_06)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x00A0, 0x00A2
     */
        if (/* JLE fallthrough cond: */ ax > 0) /* @0x005449 JLE 0x005465 */ {
            /* @0x00544F */ func_005418();
            if (/* JNE fallthrough cond: */ ax == 0) /* @0x005457 JNE 0x0054D5 */ {
                /* @0x00545F */ func_0053DE();
                goto label_0054A6;  /* @0x005468 */
                if (/* JE fallthrough cond: */ ax != 0) /* @0x005471 JE 0x0054CA */ {
                    if (/* JNE fallthrough cond: */ ax == 0) /* @0x005478 JNE 0x0054CA */ {
                        /* @0x00547C */ overlay_call_029F_0318();
                        goto label_0054CA;  /* @0x005484 */
                        /* @0x005488 */ overlay_call_029F_034C();
                        goto label_005481;  /* @0x00548D */
                        /* @0x005492 */ overlay_call_029F_02CC();
                        goto label_005481;  /* @0x005497 */
                        goto label_005492;  /* @0x00549C */
                        goto label_005492;  /* @0x0054A0 */
                        goto label_005492;  /* @0x0054A4 */
                        if (/* JA fallthrough cond: */ ax <= 0) /* @0x0054A9 JA 0x0054CA */ {
                        }
                    }
                }
            }
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x0054DA..0x005504  (42 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0054DA_unknown.asm
 * @pattern    WRAPPER_LCALL
 * @prologue   ENTER 0x340
 * @args_seen  [6]
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x0C56
 * @inferred_role  WRAPPER_LCALL (42 bytes). 0x0D1D:0x0C56
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_0054DA_rtl_sz_42(uint16_t arg0_bp_06)
{
    /* @auto: wrapper forwards to LCALL 0x0D1D:0x0C56. */
    return overlay_call_0D1D_0C56();
}

/* @asm        0x00566E..0x0056F2  (132 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00566E_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   ENTER 0x114
 * @args_seen  []
 * @lcalls     6
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x07E4
 *   - 0x0D1D:0x07A4  (5x)
 *
 * Near CALL targets:
 *   - 0x0054DA
 * @inferred_role DISPATCH_VIA_OVERLAY / C_RUNTIME  (HIGH)
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_00566E_rtl_sz_132(void)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x036C, 0x0828, 0x2606
     */
        /* @0x00567A */ overlay_call_0D1D_07E4();
        /* @0x00568A */ overlay_call_0D1D_07A4();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x005697 JE 0x0056A9 */ {
            /* @0x0056A1 */ overlay_call_0D1D_07A4();
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x0056AE JE 0x0056C0 */ {
            /* @0x0056B8 */ overlay_call_0D1D_07A4();
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x0056C5 JE 0x0056E7 */ {
            /* @0x0056CF */ overlay_call_0D1D_07A4();
            /* @0x0056DF */ overlay_call_0D1D_07A4();
        }
        /* @0x0056ED */ func_0054DA();
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x0056F2..0x00575F  (109 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0056F2_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   ENTER 0x114
 * @args_seen  []
 * @lcalls     5
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x07E4
 *   - 0x0D1D:0x07A4  (4x)
 *
 * Near CALL targets:
 *   - 0x0054DA
 * @inferred_role DISPATCH_VIA_OVERLAY / C_RUNTIME  (HIGH)
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_0056F2_rtl_sz_109(void)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x036C, 0x2606
     */
        /* @0x0056FE */ overlay_call_0D1D_07E4();
        /* @0x00570E */ overlay_call_0D1D_07A4();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00571B JE 0x00572D */ {
            /* @0x005725 */ overlay_call_0D1D_07A4();
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x005732 JE 0x005754 */ {
            /* @0x00573C */ overlay_call_0D1D_07A4();
            /* @0x00574C */ overlay_call_0D1D_07A4();
        }
        /* @0x00575A */ func_0054DA();
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x005760..0x0057DF  (127 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005760_unknown.asm
 * @pattern    DISPATCHER
 * @prologue   ENTER 0x16
 * @args_seen  []
 * @lcalls     6
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x181F:0x05A8
 *   - 0x0984:0x00AA  (2x)
 *   - 0x181F:0x059A
 *   - 0x0984:0x04F6
 *   - 0x181F:0x0582
 * @inferred_role PER_POWER_OP  (MEDIUM)
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_005760_op_sz_127(void)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x0829, 0x84FC
     */
        /* @0x00576A */ overlay_call_181F_05A8();
        /* @0x005771 */ overlay_call_0984_00AA();
        /* @0x005779 */ overlay_call_181F_059A();
        /* @0x005780 */ overlay_call_0984_00AA();
        /* @0x005788 */ overlay_call_0984_04F6();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x005792 JE 0x0057DE */ {
            goto label_0057C5;  /* @0x005799 */
            if (/* JGE fallthrough cond: */ ax < 0) /* @0x0057A3 JGE 0x0057C2 */ {
                if (/* JNS fallthrough cond: */ ax signed 0) /* @0x0057B1 JNS 0x0057B5 */ {
                }
                goto label_00579C;  /* @0x0057BF */
            }
            if (/* JGE fallthrough cond: */ ax < 0) /* @0x0057C9 JGE 0x0057DE */ {
                /* @0x0057CE */ overlay_call_181F_0582();
                goto label_00579F;  /* @0x0057DB */
            }
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x005BFA..0x005C2B  (49 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005BFA_is_xy_in_map_bounds.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 2
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  is_xy_in_map_bounds: 1 if (x,y) is a valid 1-based map cell, else 0
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_005BFA_logic_sz_49(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x005BFE mov [bp-2],1 (result=1).
     * @asm 0x005C03 cmp [bp+6],1; jl  -> x<1 fails.
     * @asm 0x005C09 cmp [bp+8],1; jl  -> y<1 fails.
     * @asm 0x005C0F mov ax,[0x853a]; dec ax; cmp ax,[bp+6]; jle -> (width-1)<=x fails.
     * @asm 0x005C18 mov ax,[0x853c]; dec ax; cmp ax,[bp+8]; jg ok, else (height-1)<=y fails.
     * On any failure result is cleared to 0 (@0x005C21).  Signed compares.
     * g_map_width=0x853A, g_map_height=0x853C (DGROUP_MEMORY_MAP §2). */
    int x = (int16_t)arg0_bp_06;
    int y = (int16_t)arg1_bp_08;
    if (x < 1 || y < 1 ||
        (int16_t)(g_map_width  - 1) <= x ||
        (int16_t)(g_map_height - 1) <= y)
        return 0;
    return 1;
}

/* @asm        0x005C2C..0x005CB0  (132 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005C2C_unknown.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 2
 * @args_seen  [6, 8, 10]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  proximity predicate: 1 if delta (arg0,arg1) lies inside the
 *                 neighbourhood selected by arg2 (1=king/orthogonal-adjacent,
 *                 2=immediate 3x3, 3=within-2 diamond, else within-2 cross), else 0.
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 *
 * Bands OR-accumulate into the result and arg2 short-circuits after its band; all
 * compares are signed.  arg0/arg1 are deltas (abs-folded in place at entry).
 */
int func_005C2C_logic_sz_132(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    /* @asm 0x005C30 if arg0 <= 0: arg0 = -arg0;  0x005C3F if arg1 <= 0: arg1 = -arg1. */
    int ax_ = (int16_t)arg0_bp_06; if (ax_ <= 0) ax_ = -ax_;   /* |dx| */
    int ay  = (int16_t)arg1_bp_08; if (ay  <= 0) ay  = -ay;    /* |dy| */
    int result;

    /* @asm 0x005C4E ax=|dy|+|dx|; cmp ax,1; jg -> result = (|dx|+|dy| <= 1) ? 1 : 0. */
    result = ((ay + ax_) <= 1) ? 1 : 0;

    /* @asm 0x005C63 cmp arg2,1; je 0x5CAB -> done. */
    if ((int16_t)arg2_bp_0A == 1)
        return result;

    /* @asm 0x005C69 if (|dx| < 2 && |dy| < 2) result |= 1. */
    if (ax_ < 2 && ay < 2)
        result |= 1;

    /* @asm 0x005C79 cmp arg2,2; je 0x5CAB -> done. */
    if ((int16_t)arg2_bp_0A == 2)
        return result;

    /* @asm 0x005C7F ax=|dy|+|dx|; cmp ax,2; jg -> result |= (|dx|+|dy| <= 2) ? 1 : 0. */
    result |= ((ay + ax_) <= 2) ? 1 : 0;

    /* @asm 0x005C95 cmp arg2,3; je 0x5CAB -> done. */
    if ((int16_t)arg2_bp_0A == 3)
        return result;

    /* @asm 0x005C9B if (|dx| < 2 || |dy| < 2) result |= 1. */
    if (ax_ < 2 || ay < 2)
        result |= 1;

    return result;
}

/* @asm        0x005CB0..0x005CE6  (54 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005CB0_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 2
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (54 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics not yet decoded)
 */
int func_005CB0_logic_sz_54(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x8328, 0x832E, 0x8804, 0x8806
     */
        if (/* JG fallthrough cond: */ ax <= 0) /* @0x005CC0 JG 0x005CC8 */ {
            if (/* JGE fallthrough cond: */ ax < 0) /* @0x005CC6 JGE 0x005CCD */ {
            }
        }
        if (/* JG fallthrough cond: */ ax <= 0) /* @0x005CD4 JG 0x005CDC */ {
            if (/* JGE fallthrough cond: */ ax < 0) /* @0x005CDA JGE 0x005CE1 */ {
            }
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x005CE6..0x005CFE  (24 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005CE6_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  map_tile_addr_layer_15C: far address of tile (x,y) in map layer 0x15C
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
void far *func_005CE6_logic_sz_24(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x005CEA mov ax,[bp+8]; 0x005CED imul [0x853a] (ax = y*width);
     * 0x005CF1 add ax,[0x15c]; 0x005CF5 mov dx,[0x15e] (far ptr 0x15C off/seg);
     * 0x005CF9 add ax,[bp+6] -> returns dx:ax = &g_map_layer_15c[width*y + x].
     * Offset-only pointer arithmetic (segment unchanged) per the asm. */
    return (uint8_t far *)g_map_layer_15c
         + ((int)g_map_width * (int16_t)arg1_bp_08 + (int16_t)arg0_bp_06);
}

/* @asm        0x005CFE..0x005D1A  (28 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005CFE_map_tile_read_layer_15C.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  map_tile_read_layer_15C: byte at tile (x,y) in map layer 0x15C
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_005CFE_map_tile_read_layer_15C(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x005D02 mov ax,[0x853a]; 0x005D05 imul [bp+8]; 0x005D08 mov bx,ax;
     * 0x005D0A add bx,[0x15c]; 0x005D0E mov es,[0x15e]; 0x005D12 add bx,[bp+6];
     * 0x005D15 mov al,es:[bx] -> reads the byte g_map_layer_15c[width*y + x]. */
    return ((uint8_t far *)g_map_layer_15c)
        [(int)g_map_width * (int16_t)arg1_bp_08 + (int16_t)arg0_bp_06];
}

/* @asm        0x005D1A..0x005D31  (23 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005D1A_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  map_tile_addr_layer_160: far address of tile (x,y) in map layer 0x160
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
void far *func_005D1A_logic_sz_23(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x005D1E mov ax,[0x853a]; imul [bp+8]; add ax,[0x160]; mov dx,[0x162];
     * add ax,[bp+6] -> returns dx:ax = &g_map_layer_160[width*y + x]. */
    return (uint8_t far *)g_map_layer_160
         + ((int)g_map_width * (int16_t)arg1_bp_08 + (int16_t)arg0_bp_06);
}

/* @asm        0x005D32..0x005D4E  (28 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005D32_map_tile_read_layer_160.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  map_tile_read_layer_160: byte at tile (x,y) in map layer 0x160
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_005D32_map_tile_read_layer_160(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x005D36 mov ax,[0x853a]; imul [bp+8]; mov bx,ax; add bx,[0x160];
     * mov es,[0x162]; add bx,[bp+6]; mov al,es:[bx] -> byte g_map_layer_160[width*y+x]. */
    return ((uint8_t far *)g_map_layer_160)
        [(int)g_map_width * (int16_t)arg1_bp_08 + (int16_t)arg0_bp_06];
}

/* @asm        0x005D4E..0x005D76  (40 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005D4E_unknown.asm
 * @pattern    WRAPPER_NEARCALL
 * @prologue   ENTER 4
 * @args_seen  [6, 8, 10, 12]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x005D1A
 * @inferred_role  set/clear mask bits on tile (x,y) in map layer 0x160
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
void func_005D4E_logic_sz_40(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    /* @asm 0x005D52 push [bp+8],[bp+6]; call 0x5d1a -> far addr of layer-160 tile,
     * saved to [bp-4..bp-2].
     * @asm 0x005D65 cmp [bp+0xc],0; je 0x5d76 -> if arg3 (set-flag) != 0:
     *   @asm 0x005D6B al=[bp+0xa]; les bx,[bp-4]; 0x005D71 or es:[bx],al  (set mask bits)
     * else (arg3==0):
     *   @asm 0x005D79 al=[bp+0xa]; not al; les bx,[bp-4]; and es:[bx],al  (clear mask bits)
     * arg2 (bp+0xa) is the byte mask; no value returned. */
    uint8_t far *tile = (uint8_t far *)func_005D1A_logic_sz_23(arg0_bp_06, arg1_bp_08);
    uint8_t mask = (uint8_t)arg2_bp_0A;
    if (arg3_bp_0C != 0)
        *tile |= mask;
    else
        *tile &= (uint8_t)~mask;
}

/* @asm        0x005D84..0x005D9B  (23 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005D84_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  map_tile_addr_layer_164: far address of tile (x,y) in map layer 0x164
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
void far *func_005D84_logic_sz_23(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x005D88 mov ax,[0x853a]; imul [bp+8]; add ax,[0x164]; mov dx,[0x166];
     * add ax,[bp+6] -> returns dx:ax = &(map layer 0x164)[width*y + x].
     * Layer 0x164 far ptr lives at DGROUP 0x0164(off)/0x0166(seg); not yet a
     * named global (cf. g_map_layer_15c/160). */
    return (uint8_t far *)(*(void far * near *)0x0164)
         + ((int)g_map_width * (int16_t)arg1_bp_08 + (int16_t)arg0_bp_06);
}

/* @asm        0x005D9C..0x005DB9  (29 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005D9C_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  map_tile_read_layer_164: byte at tile (x,y) in map layer 0x164
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_005D9C_logic_sz_29(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x005DA0 mov ax,[bp+8]; imul [0x853a]; mov bx,ax; add bx,[0x164];
     * mov es,[0x166]; add bx,[bp+6]; mov al,es:[bx] -> byte (layer 0x164)[width*y+x]. */
    return ((uint8_t far *)(*(void far * near *)0x0164))
        [(int)g_map_width * (int16_t)arg1_bp_08 + (int16_t)arg0_bp_06];
}

/* @asm        0x005DBA..0x005DCB  (17 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005DBA_unknown.asm
 * @pattern    WRAPPER_NEARCALL
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x005D9C
 * @inferred_role  low nibble of tile (x,y) in map layer 0x164
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
int func_005DBA_logic_sz_17(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @asm 0x005DBD push [bp+8],[bp+6]; call 0x5d9c (read layer-164 byte);
     * 0x005DC7 and al,0xf -> returns the low nibble of the tile. */
    return func_005D9C_logic_sz_29(arg0_bp_06, arg1_bp_08) & 0x0F;
}

/* @asm        0x005DCC..0x005DF0  (36 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_005DCC_unknown.asm
 * @pattern    WRAPPER_NEARCALL
 * @prologue   ENTER 4
 * @args_seen  [6, 8, 10]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x005D84
 * @inferred_role  set low nibble of tile (x,y) in map layer 0x164 to arg2&0xF
 * @status     BYTE_VERIFIED 2026-06-08 (full body decompiled from VICEROY.EXE)
 */
void func_005DCC_logic_sz_36(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A)
{
    /* @asm 0x005DD0 push [bp+8],[bp+6]; call 0x5d84 -> far addr of layer-164 tile.
     * @asm 0x005DE0 les bx,[bp-4]; al=es:[bx]; 0x005DE6 xor al,[bp+0xa];
     *      0x005DE9 and al,0xf; 0x005DEB xor es:[bx],al.
     * Net effect: tile ^= ((tile ^ arg2) & 0xF), i.e. replace the tile's low
     * nibble with arg2's low nibble while preserving the high nibble. */
    uint8_t far *tile = (uint8_t far *)func_005D84_logic_sz_23(arg0_bp_06, arg1_bp_08);
    *tile ^= (uint8_t)((*tile ^ (uint8_t)arg2_bp_0A) & 0x0F);
}

