/* ============================================================================
 * load_image_0033F2_004E76.c -- load_image functions in file range 0x0033F2..0x004E76
 * Auto-generated by tools/full_pipeline.py for VICEROY.
 *
 * 30 functions in this file. Each carries a citation block plus
 * an auto-traced control-flow body.  Functions marked SKELETON have body
 * content derived from control-flow but their semantics still need hand-port.
 * ============================================================================ */
#include "viceroy.h"
#include "overlay_externs.h"

/* @asm        0x0033F2..0x00341D  (43 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0033F2_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (43 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_0033F2_logic_sz_43(void)
{
    /* @auto: tiny accessor reads DGROUP:0x2CE0. */
    return *((uint16_t near*)0x2CE0);
}

/* @asm        0x00341E..0x003435  (23 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00341E_unknown.asm
 * @pattern    WRAPPER_LCALL
 * @prologue   ENTER 8
 * @args_seen  [6]
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x181F:0x029A
 * @inferred_role  WRAPPER_LCALL (23 bytes). 0x181F:0x029A
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_00341E_op_sz_23(uint16_t arg0_bp_06)
{
    /* @auto: wrapper forwards to LCALL 0x181F:0x029A. */
    return overlay_call_181F_029A();
}

/* @asm        0x003436..0x00344F  (25 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_003436_terrain_id_normalize_to_8.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_003436_terrain_id_normalize_to_8(uint16_t arg0_bp_06)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x003460..0x0034C3  (99 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_003460_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   ENTER 0xc
 * @args_seen  [6, 8, 10, 12, 14, 16]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x003436
 * @inferred_role  PROLOGUE_HEAVY (99 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_003460_logic_sz_99(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E, uint16_t arg5_bp_10)
{
    /* @auto: control-flow trace from disassembly. */
        /* @0x00346A */ func_003436();
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x0034BC JNE 0x0034B4 */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x0034C4..0x003536  (114 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0034C4_unknown.asm
 * @pattern    COUNT_LOOP
 * @prologue   ENTER 0xc
 * @args_seen  [6, 8, 10, 12, 14, 16]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x003436
 * @inferred_role  COUNT_LOOP (114 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_0034C4_logic_sz_114(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E, uint16_t arg5_bp_10)
{
    /* @auto: control-flow trace from disassembly. */
        /* @0x0034CE */ func_003436();
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x003520 JNE 0x003528 */ {
            /* @0x003523 LOOP back to 0x00351B */
            goto label_00352C;  /* @0x003525 */
        }
        /* @0x00352A LOOP back to 0x00351B */
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x00352F JNE 0x003518 */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x003536..0x00356B  (53 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_003536_unknown.asm
 * @pattern    WRAPPER_NEARCALL
 * @prologue   ENTER 0x1a
 * @args_seen  [10, 16, 18]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x003436
 * @inferred_role  WRAPPER_NEARCALL (53 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_003536_logic_sz_53(uint16_t arg0_bp_0A, uint16_t arg1_bp_10, uint16_t arg2_bp_12)
{
    /* @auto: wrapper forwards to near CALL 0x003436. */
    return func_003436();
}

/* @asm        0x0035EC..0x003621  (53 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0035EC_unknown.asm
 * @pattern    WRAPPER_NEARCALL
 * @prologue   ENTER 0x1a
 * @args_seen  [10, 16, 18]
 * @lcalls     0
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * Near CALL targets:
 *   - 0x003436
 * @inferred_role  WRAPPER_NEARCALL (53 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_0035EC_logic_sz_53(uint16_t arg0_bp_0A, uint16_t arg1_bp_10, uint16_t arg2_bp_12)
{
    /* @auto: wrapper forwards to near CALL 0x003436. */
    return func_003436();
}

/* @asm        0x003710..0x003724  (20 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_003710_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (20 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_003710_logic_sz_20(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x0037BE..0x00380C  (78 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0037BE_unknown.asm
 * @pattern    UNKNOWN
 * @prologue   ENTER 2
 * @args_seen  []
 * @lcalls     1
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0427:0x004A
 *
 * Near CALL targets:
 *   - 0x003710
 * @inferred_role  UNKNOWN (78 bytes). 0x0427:0x004A
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_0037BE_op_sz_78(void)
{
    /* @auto: control-flow trace from disassembly. */
        if (/* JE fallthrough cond: */ ax != 0) /* @0x0037C8 JE 0x0037FA */ {
            if (/* JL fallthrough cond: */ ax >= 0) /* @0x0037D6 JL 0x0037F6 */ {
                if (/* JB fallthrough cond: */ ax >= 0) /* @0x0037E1 JB 0x0037E9 */ {
                    if (/* JA fallthrough cond: */ ax <= 0) /* @0x0037E5 JA 0x0037E9 */ {
                    }
                }
                /* @0x0037EB */ overlay_call_0427_004A();
                if (/* JL fallthrough cond: */ ax >= 0) /* @0x0037F4 JL 0x0037D4 */ {
                }
            }
            if (/* JGE fallthrough cond: */ ax < 0) /* @0x0037F8 JGE 0x0037FD */ {
            }
        }
        /* @0x003805 */ func_003710();
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00380C..0x003869  (93 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00380C_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0C36:0x000A
 * @inferred_role  PROLOGUE_HEAVY (93 bytes). 0x0C36:0x000A
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_00380C_op_sz_93(uint16_t arg0_bp_06)
{
    /* @auto: control-flow trace from disassembly. */
        if (/* JE fallthrough cond: */ ax != 0) /* @0x00381C JE 0x003843 */ {
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x003847 JE 0x003863 */ {
            /* @0x00385E */ overlay_call_0C36_000A();
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x00386A..0x0038CE  (100 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00386A_unknown.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 0x46
 * @args_seen  []
 * @lcalls     1
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0427:0x004A
 *
 * Near CALL targets:
 *   - 0x0037BE
 * @inferred_role  MEDIUM_LOGIC (100 bytes). 0x0427:0x004A
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_00386A_op_sz_100(void)
{
    /* @auto: control-flow trace from disassembly. */
        /* @0x003888 */ func_0037BE();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x003892 JE 0x0038AC */ {
            /* @0x00389B */ overlay_call_0427_004A();
            if (/* JL fallthrough cond: */ ax >= 0) /* @0x0038A2 JL 0x0038AC */ {
                goto label_0038B1;  /* @0x0038A9 */
            }
        }
        if (/* JAE fallthrough cond: */ ax < 0) /* @0x0038CA JAE 0x0038CF */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x003E40..0x003EEE  (174 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_003E40_unknown.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 0x60
 * @args_seen  [6, 8, 10, 12, 14]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  MEDIUM_LOGIC (174 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_003E40_logic_sz_174(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C, uint16_t arg4_bp_0E)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x0184, 0x5AD4
     */
        if (/* JGE fallthrough cond: */ ax < 0) /* @0x003E6A JGE 0x003E80 */ {
            goto label_003E85;  /* @0x003E7E */
        }
        if (/* JLE fallthrough cond: */ ax > 0) /* @0x003EA0 JLE 0x003EA5 */ {
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x003EC9 JE 0x003ECE */ {
            goto label_003F8A;  /* @0x003ECB */
        }
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x003ED0 JNE 0x003F3A */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x004314..0x004322  (14 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004314_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0x26
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (14 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004314_logic_sz_14(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x0043B1..0x0043D9  (40 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0043B1_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 0x325
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (40 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_0043B1_logic_sz_40(void)
{
    /* @auto: tiny accessor reads DGROUP:0x0184. */
    return *((uint16_t near*)0x0184);
}

/* @asm        0x004566..0x0046AC  (326 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004566_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 0x24
 * @args_seen  [10, 12, 14, 16, 18]
 * @lcalls     4
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0984:0x02FC
 *   - 0x181F:0x032C  (2x)
 *   - 0x181F:0x0344
 *
 * Near CALL targets:
 *   - 0x00386A
 * @inferred_role  LARGE_LOGIC (326 bytes). 0x0984:0x02FC + 0x181F:0x032C
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004566_op_sz_326(uint16_t arg0_bp_0A, uint16_t arg1_bp_0C, uint16_t arg2_bp_0E, uint16_t arg3_bp_10, uint16_t arg4_bp_12)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x0184, 0x5AD4, 0x8326, 0x8328, 0x832A, 0x832C, 0x832E
     */
        /* @0x004582 */ overlay_call_0984_02FC();
        if (/* JLE fallthrough cond: */ ax > 0) /* @0x004590 JLE 0x004595 */ {
        }
        if (/* JLE fallthrough cond: */ ax > 0) /* @0x00459E JLE 0x0045A3 */ {
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x0045B5 JE 0x0045BD */ {
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x0045CC JE 0x0045D4 */ {
        }
        /* @0x0045E8 */ overlay_call_181F_032C();
        /* @0x0045F8 */ overlay_call_181F_0344();
        if (/* JL fallthrough cond: */ ax >= 0) /* @0x004604 JL 0x00465F */ {
            /* @0x004622 */ overlay_call_181F_032C();
            /* @0x00465C */ func_00386A();
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x0048CC..0x0048D9  (13 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0048CC_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (13 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_0048CC_logic_sz_13(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x0048EA..0x0048FF  (21 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0048EA_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (21 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_0048EA_logic_sz_21(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x004900..0x00490F  (15 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004900_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (15 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004900_logic_sz_15(uint16_t arg0_bp_06)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x00493C..0x00494A  (14 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_00493C_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  [6, 10]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (14 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_00493C_logic_sz_14(uint16_t arg0_bp_06, uint16_t arg1_bp_0A)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x004984..0x004990  (12 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004984_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (12 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004984_logic_sz_12(uint16_t arg0_bp_06)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x0049B4..0x0049C2  (14 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0049B4_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  [6, 10]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (14 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_0049B4_logic_sz_14(uint16_t arg0_bp_06, uint16_t arg1_bp_0A)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x0049FC..0x004A10  (20 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_0049FC_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (20 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_0049FC_logic_sz_20(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x004A5C..0x004A80  (36 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004A5C_wait_for_keypress.asm
 * @pattern    UNKNOWN
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  []
 * @lcalls     2
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x029F:0x00F6
 *   - 0x0AE7:0x0016
 * @inferred_role  UNKNOWN (36 bytes). 0x029F:0x00F6 + 0x0AE7:0x0016
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004A5C_op_sz_36(void)
{
    /* @auto: control-flow trace from disassembly. */
        /* @0x004A62 */ overlay_call_029F_00F6();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x004A6E JE 0x004A77 */ {
            /* @0x004A70 */ overlay_call_0AE7_0016();
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x004A79 JE 0x004A62 */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x004A80..0x004A9A  (26 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004A80_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   ENTER 4
 * @args_seen  []
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (26 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004A80_logic_sz_26(void)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x004AFA..0x004B16  (28 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004AFA_drain_keyboard_buffer.asm
 * @pattern    WRAPPER_LCALL
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  []
 * @lcalls     1
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0AE7:0x0016
 * @inferred_role  WRAPPER_LCALL (28 bytes). 0x0AE7:0x0016
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004AFA_op_sz_28(void)
{
    /* @auto: wrapper forwards to LCALL 0x0AE7:0x0016. */
    return overlay_call_0AE7_0016();
}

/* @asm        0x004B16..0x004B44  (46 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004B16_unknown.asm
 * @pattern    PROLOGUE_HEAVY
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8, 10, 12]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  PROLOGUE_HEAVY (46 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004B16_logic_sz_46(uint16_t arg0_bp_06, uint16_t arg1_bp_08, uint16_t arg2_bp_0A, uint16_t arg3_bp_0C)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x07E8, 0x07EA
     */
        if (/* JG fallthrough cond: */ ax <= 0) /* @0x004B22 JG 0x004B44 */ {
            if (/* JL fallthrough cond: */ ax >= 0) /* @0x004B2A JL 0x004B44 */ {
                if (/* JG fallthrough cond: */ ax <= 0) /* @0x004B35 JG 0x004B44 */ {
                    if (/* JL fallthrough cond: */ ax >= 0) /* @0x004B3D JL 0x004B44 */ {
                    }
                }
            }
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x004B48..0x004B61  (25 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004B48_unknown.asm
 * @pattern    TINY_ACCESSOR
 * @prologue   PUSH-BP-MOV-BP-SP
 * @args_seen  [6, 8]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  TINY_ACCESSOR (25 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004B48_logic_sz_25(uint16_t arg0_bp_06, uint16_t arg1_bp_08)
{
    /* @auto: tiny accessor; field not auto-identified. */
    return 0;  /* TODO */
}

/* @asm        0x004B72..0x004D1D  (427 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004B72_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 0x350
 * @args_seen  [6]
 * @lcalls     14
 * @near_calls 1
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0D1D:0x07E4  (2x)
 *   - 0x0D1D:0x07A4
 *   - 0x004B:0x012E  (2x)
 *   - 0x181F:0x044E
 *   - 0x181F:0x0438  (2x)
 *   - 0x05B3:0x0144
 *   - 0x181F:0x0416  (2x)
 *   - 0x181F:0x0422
 *   - 0x181F:0x040A
 *   - 0x181F:0x03FE
 *
 * Near CALL targets:
 *   - 0x004A32
 * @inferred_role TEXT_DRAW / C_RUNTIME / DISPATCH_VIA_OVERLAY  (HIGH)
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004B72_rtl_sz_427(uint16_t arg0_bp_06)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x1F4A, 0x1F50, 0x5398, 0x53A6
     * Writes DGROUP: 0x1F4A, 0x1F50, 0x1F56, 0x1F64, 0x1F6A
     */
        /* @0x004B7F */ overlay_call_0D1D_07E4();
        if (/* JGE fallthrough cond: */ ax < 0) /* @0x004B8B JGE 0x004B9C */ {
            /* @0x004B94 */ overlay_call_0D1D_07A4();
        }
        /* @0x004BA4 */ overlay_call_004B_012E();
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x004BB0 JNE 0x004BB6 */ {
            /* @0x004BB3 */ func_004A32();
        }
        /* @0x004BD2 */ overlay_call_181F_044E();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x004BDC JE 0x004BE1 */ {
            goto label_004D0D;  /* @0x004BDE */
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x004C12 JE 0x004C1C */ {
            if (/* JE fallthrough cond: */ ax != 0) /* @0x004C15 JE 0x004C3E */ {
                if (/* JE fallthrough cond: */ ax != 0) /* @0x004C18 JE 0x004C54 */ {
                    goto label_004C99;  /* @0x004C1A */
                    /* @0x004C2A */ overlay_call_181F_0438();
                    goto label_004C8F;  /* @0x004C3C */
                    /* @0x004C4A */ overlay_call_181F_0438();
                    goto label_004C99;  /* @0x004C52 */
                }
            }
        }
        /* @0x004C62 */ overlay_call_05B3_0144();
        /* @0x004C71 */ overlay_call_181F_0416();
        /* @0x004C83 */ overlay_call_181F_0422();
        /* @0x004C91 */ overlay_call_181F_0416();
        /* @0x004C99 */ overlay_call_181F_040A();
        /* @0x004CB6 */ overlay_call_0D1D_07E4();
        /* @0x004CC6 */ overlay_call_004B_012E();
        /* @0x004CE5 */ overlay_call_181F_03FE();
        if (/* JNE fallthrough cond: */ ax == 0) /* @0x004CF6 JNE 0x004D03 */ {
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x004D1E..0x004DF7  (217 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004D1E_unknown.asm
 * @pattern    LARGE_LOGIC
 * @prologue   ENTER 8
 * @args_seen  []
 * @lcalls     6
 * @near_calls 2
 * @callers    0
 * @touches_8542 False
 *
 * LCALL targets:
 *   - 0x0AE7:0x0016
 *   - 0x181F:0x03D4  (2x)
 *   - 0x0D1D:0x030D  (2x)
 *   - 0x0A58:0x038B
 *
 * Near CALL targets:
 *   - 0x004B72
 *   - 0x004AFA
 * @inferred_role  LARGE_LOGIC (217 bytes). 0x0AE7:0x0016 + 0x181F:0x03D4
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004D1E_op_sz_217(void)
{
    /* @auto: control-flow trace from disassembly. */
    /*
     * Reads DGROUP: 0x008A, 0x008C, 0x0090, 0x0092, 0x0828
     * Writes DGROUP: 0x008A, 0x0090, 0x0092, 0x0828
     */
        if (/* JL fallthrough cond: */ ax >= 0) /* @0x004D33 JL 0x004D48 */ {
            if (/* JL fallthrough cond: */ ax >= 0) /* @0x004D3F JL 0x004D80 */ {
                if (/* JG fallthrough cond: */ ax <= 0) /* @0x004D41 JG 0x004D48 */ {
                    if (/* JB fallthrough cond: */ ax >= 0) /* @0x004D46 JB 0x004D80 */ {
                        if (/* JL fallthrough cond: */ ax >= 0) /* @0x004D4D JL 0x004D64 */ {
                            goto label_004D80;  /* @0x004D62 */
                        }
                        /* @0x004D7A */ func_004B72();
                    }
                }
            }
        }
        if (/* JE fallthrough cond: */ ax != 0) /* @0x004D87 JE 0x004DC1 */ {
            /* @0x004D89 */ overlay_call_0AE7_0016();
            /* @0x004D91 */ func_004AFA();
            if (/* JE fallthrough cond: */ ax != 0) /* @0x004D9E JE 0x004DA6 */ {
                if (/* JNE fallthrough cond: */ ax == 0) /* @0x004DA4 JNE 0x004DAB */ {
                }
            }
            if (/* JE fallthrough cond: */ ax != 0) /* @0x004DB0 JE 0x004DC1 */ {
                /* @0x004DB2 */ overlay_call_181F_03D4();
                /* @0x004DB9 */ overlay_call_0D1D_030D();
            }
        }
        /* @0x004DC9 */ overlay_call_0A58_038B();
        if (/* JE fallthrough cond: */ ax != 0) /* @0x004DD3 JE 0x004DF1 */ {
            if (/* JE fallthrough cond: */ ax != 0) /* @0x004DE0 JE 0x004DF1 */ {
                /* @0x004DE2 */ overlay_call_181F_03D4();
                /* @0x004DE9 */ overlay_call_0D1D_030D();
            }
        }
    return 0;  /* @auto: TODO confirm return semantics */
}

/* @asm        0x004DF8..0x004E76  (126 bytes)  region=load_image
 * @asm_file   ../code/VICEROY/disasm/func_004DF8_unknown.asm
 * @pattern    MEDIUM_LOGIC
 * @prologue   ENTER 2
 * @args_seen  [6]
 * @lcalls     0
 * @near_calls 0
 * @callers    0
 * @touches_8542 False
 * @inferred_role  MEDIUM_LOGIC (126 bytes). no LCALLs
 * @status     SKELETON (auto-traced control flow; semantics TBD)
 */
int func_004DF8_logic_sz_126(uint16_t arg0_bp_06)
{
    /* @auto: control-flow trace from disassembly. */
        goto label_004E9E;  /* @0x004E04 */
        goto label_004EE0;  /* @0x004E0D */
        goto label_004EE0;  /* @0x004E15 */
        goto label_004EE0;  /* @0x004E1D */
        goto label_004EE0;  /* @0x004E25 */
        goto label_004EE0;  /* @0x004E2D */
        goto label_004EE0;  /* @0x004E35 */
        goto label_004EE0;  /* @0x004E3D */
        goto label_004EE0;  /* @0x004E45 */
        goto label_004EE0;  /* @0x004E4D */
        goto label_004EE0;  /* @0x004E55 */
        goto label_004EE0;  /* @0x004E5D */
        goto label_004EE0;  /* @0x004E65 */
    return 0;  /* @auto: TODO confirm return semantics */
}

