#!/usr/bin/env python3
"""Generate the Cheat Engine table (VICEROY_DOSBOX.CT) + standalone Lua bridge
(viceroy_dosbox.lua) from the byte-cited inventory in addresses.json.

Everything the table exposes traces to a repo citation (see addresses.json and
README.md). At generation time the primary DGROUP anchor is re-verified against
the reconstituted VICEROY.EXE (bin/reconstitute.py -> raw/COLONIZE/VICEROY.EXE)
at DGROUP file base 0x1D9A0 (spec/systems/revolution.md), so the anchor bytes in
the emitted artifacts are byte-verified by construction.

Usage:  python3 tools/cheat_engine/make_ct.py
Writes: tools/cheat_engine/VICEROY_DOSBOX.CT, tools/cheat_engine/viceroy_dosbox.lua
"""
import json, os, sys
from xml.sax.saxutils import escape

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
INV = json.load(open(os.path.join(HERE, 'addresses.json')))

DGROUP_FILE_BASE = int(INV['anchors']['dgroup_file_base'], 16)
ANCHOR_AOB = INV['anchors']['primary']['bytes_hex']
ANCHOR_OFF = int(INV['anchors']['primary']['dgroup_off'], 16)
ANCHOR2_OFF = int(INV['anchors']['secondary']['dgroup_off'], 16)
ANCHOR2_STR = '-STGLFFBPR---'


def verify_anchor_against_exe():
    """Byte-verify the primary anchor against the reconstituted EXE (soft)."""
    exe = os.path.join(ROOT, 'raw', 'COLONIZE', 'VICEROY.EXE')
    want = bytes(int(b, 16) for b in ANCHOR_AOB.split())
    if not os.path.exists(exe):
        print('note: raw/COLONIZE/VICEROY.EXE not present (run bin/reconstitute.py) — '
              'skipping generation-time anchor byte-check')
        return
    data = open(exe, 'rb').read()
    got = data[DGROUP_FILE_BASE + ANCHOR_OFF: DGROUP_FILE_BASE + ANCHOR_OFF + len(want)]
    if got != want:
        sys.exit(f'ANCHOR MISMATCH vs VICEROY.EXE @0x{DGROUP_FILE_BASE + ANCHOR_OFF:X}: {got!r}')
    if data.count(want) != 1:
        sys.exit('ANCHOR NOT UNIQUE in VICEROY.EXE')
    print(f'anchor byte-check OK (file 0x{DGROUP_FILE_BASE + ANCHOR_OFF:05X}, unique in EXE)')


# ---------------------------------------------------------------- Lua bridge
LUA = r'''--[[
VICEROY (Sid Meier's Colonization, 1994 DOS) <-> DOSBox live-memory bridge
Generated by tools/cheat_engine/make_ct.py — do not hand-edit; edit the
generator / addresses.json instead.

How it works (see tools/cheat_engine/README.md for the full story):
 * DOSBox keeps emulated DOS RAM as one big host allocation; emulated physical
   address P sits at (MemBase + P).
 * The game's data segment (DGROUP) is found by scanning for the static
   section-name table "UNIT\0ORDERS\0ACTIONS\0" that lives at DGROUP:0x2258
   (unique in the EXE and in live RAM — docs/RUNTIME_SNAPSHOT.md).
 * MemBase (emulated phys 0) is recovered by walking DGROUP-segment candidates
   from high to low and accepting the first address whose BIOS Data Area checks
   out (u16[0x413] == 640 KB plus populated INT 08h/21h vectors). Do NOT assume
   the host allocation base is phys 0 — DOSBox 0.74-3 (Linux) puts phys 0 at
   allocation+0x10, which silently shifts every far-pointer read by 16 bytes.
   The BDA signature is unique in the whole address space (verified live).
 * DGROUP:0xNNNN citations from the repo specs are then readable at DG+0xNNNN,
   exactly as tools/runtime_snapshot.py does it headlessly.

Registered symbols (usable in any address field once located):
  DG          DGROUP linear base
  MB          emulated physical 0 (MemBase)
  CURPOWER    active PowerRecord      = DG + [DG+0x84FC]
  CURCOLONY   active ColonyRecord     = DG + [DG+0x8542]
  CURTRIBE    active TribeData record = DG + [DG+0x8D4E]
  MAPTERRAIN / MAPLAYER1 / MAPLAYER2 / MAPFOG
              linear addresses of the four map byte-planes (far ptrs at
              DGROUP:0x15C/0x160/0x164/0x168)

Console quick start:
  VICEROY.locate()      -- attach + find everything (the table auto-runs this)
  VICEROY.status()      -- one-screen game-state summary
  VICEROY.powers()      -- the four PowerRecords
  VICEROY.colonies()    -- every colony slot in use
  VICEROY.units(20)     -- first 20 unit records
  VICEROY.settlements() -- native settlements
  VICEROY.calibrate()   -- diagnostic: verify plane indexing (expect shift (0,0))
  VICEROY.tile(x, y)    -- decode the terrain under record/HUD coords
  VICEROY.revealMap(0)  -- CHEAT: reveal the map for power 0 (England)
]]

VICEROY = VICEROY or {}
local V = VICEROY

V.ANCHOR_AOB  = "@@ANCHOR_AOB@@"
V.ANCHOR_OFF  = @@ANCHOR_OFF@@
V.ANCHOR2_OFF = @@ANCHOR2_OFF@@
V.ANCHOR2_STR = "@@ANCHOR2_STR@@"
V.PROCS = {"dosbox.exe", "DOSBox.exe", "dosbox-x.exe", "dosbox_x.exe",
           "dosbox-staging.exe", "dosbox staging.exe", "dosbox"}

-- DGROUP offsets used by the bridge itself (all byte-cited; addresses.json)
local OFF = {
  layer      = {0x15C, 0x160, 0x164, 0x168},
  mapw       = 0x853A, maph = 0x853C,
  curpower   = 0x84FC, curcolony = 0x8542, curtribe = 0x8D4E,
  unitcount  = 0x539C, colonycount = 0x539E,
  year = 0x538A, season = 0x538C, turn = 0x538E,
  difficulty = 0x53A6, curplayer = 0x5394,
  ref        = 0x53DA,
  power_base = 0x8808, power_stride = 0x13C,
  colony_base = 0x5D46, colony_stride = 0xCA,
  unit_base  = 0x3144, unit_stride = 0x1C,
  settle_base = 0x54EC, settle_stride = 0x12,
  aip_base   = 0x540E, aip_stride = 0x34,
  ustat_base = 0x5230, ustat_stride = 14,
  terr_base  = 0x2F76, terr_stride = 16,
  recruit    = 0x978C,
}

V.DG, V.MB = nil, nil
V.shift = {dx = 0, dy = 0, calibrated = false}

local GOODS = {"Food","Sugar","Tobacco","Cotton","Furs","Lumber","Ore","Silver",
  "Horses","Rum","Cigars","Cloth","Coats","Trade Goods","Tools","Muskets"}
local UNITS = {"Colonists","Soldiers","Pioneers","Missionaries","Dragoons",
  "Scouts","Regulars","Cont. Cav.","Cavalry","Cont. Army","Treasure","Artillery",
  "Wagon Train","Caravel","Merchantman","Galleon","Privateer","Frigate",
  "Man-O-War","Braves","Armed Braves","Mtd. Braves","Mtd. Warriors"}
local ORDERS = {"No Orders","Sentry","Trade Route","Go To","Live In Village",
  "Fortify","Fortified","Build Colony","Clear/Plow","Build Road"}
local POWERS = {"England","France","Spain","Netherlands","Inca","Aztec","Arawak",
  "Iroquois","Cherokee","Apache","Sioux","Tupi"}
local TERRAIN = {[0]="Tundra","Desert","Plains","Prairie","Grassland","Savannah",
  "Marsh","Swamp","Boreal","Scrub","Mixed","Broadleaf","Conifer","Tropical",
  "Wetland","Rain",[24]="Arctic",[25]="Ocean",[26]="Sea Lane",[27]="Mountains",
  [28]="Hills"}

local function r8(a)  return readBytes(a, 1) end
local function r16(a) return readSmallInteger(a) end
local function r32(a) return readInteger(a) end
local function s16(v) if v and v >= 0x8000 then return v - 0x10000 end return v end
local function s32(v) if v and v >= 0x80000000 then return v - 0x100000000 end return v end

-- ---------------------------------------------------------------- attach
function V.attach()
  if getOpenedProcessID() ~= 0 and getOpenedProcessID() ~= nil then return true end
  for _, n in ipairs(V.PROCS) do
    local pid = getProcessIDFromProcessName(n)
    if pid then openProcess(pid); print(('VICEROY: attached to %s (pid %d)'):format(n, pid)); return true end
  end
  print('VICEROY: no DOSBox process found — start the game, then File>Open Process, then VICEROY.locate()')
  return false
end

-- ---------------------------------------------------------------- locate
local function validMemBase(mb)
  if mb < 0 then return false end
  if r16(mb + 0x413) ~= 640 then return false end   -- BIOS Data Area: base memory KB
  local int21 = r32(mb + 0x84)                      -- IVT: INT 21h vector populated
  local int08 = r32(mb + 0x20)                      -- IVT: INT 08h (timer) populated
  return int21 ~= nil and int21 ~= 0 and int08 ~= nil and int08 ~= 0
end

function V.findMemBase(dg)
  -- Walk DGROUP-segment candidates high->low: candidates ascend from below,
  -- so the FIRST readable+valid one is the lowest = true phys 0. The host
  -- allocation base is deliberately NOT trusted (DOSBox 0.74-3 Linux places
  -- phys 0 at allocation+0x10); the BDA+IVT signature was verified unique
  -- across the whole space in the live session (README §Verification).
  for seg = 0xA000, 0, -1 do
    local mb = dg - seg * 16
    if mb >= 0 and validMemBase(mb) then return mb end
  end
  return nil
end

function V.locate()
  if not V.attach() then return false end
  local res = AOBScan(V.ANCHOR_AOB, '+W')
  if res == nil or res.Count == 0 then
    if res then res.destroy() end
    res = AOBScan(V.ANCHOR_AOB)
  end
  if res == nil or res.Count == 0 then
    print('VICEROY: DGROUP anchor not found — is VICEROY.EXE actually running inside DOSBox?')
    if res then res.destroy() end
    return false
  end
  local best, bestSec = nil, false
  for i = 0, res.Count - 1 do
    local dg = tonumber(res[i], 16) - V.ANCHOR_OFF
    local sec = readString(dg + V.ANCHOR2_OFF, 13, false) == V.ANCHOR2_STR
    if sec then best, bestSec = dg, true break end
    if best == nil then best = dg end
  end
  res.destroy()
  V.DG = best
  V.MB = V.findMemBase(V.DG)
  if V.MB == nil then
    print('VICEROY: WARNING — MemBase (phys 0) not validated; far pointers (map planes) unavailable.')
  end
  pcall(unregisterSymbol, 'DG'); registerSymbol('DG', V.DG, true)
  if V.MB then pcall(unregisterSymbol, 'MB'); registerSymbol('MB', V.MB, true) end
  V.refresh()
  if V.timer == nil then
    V.timer = createTimer(getMainForm())
    V.timer.Interval = 400
    V.timer.OnTimer = function() if V.DG then pcall(V.refresh) end end
  end
  V.timer.Enabled = true
  print(('VICEROY: DGROUP = %X (seg %04X)%s'):format(V.DG,
    V.MB and math.floor((V.DG - V.MB) / 16) or 0,
    V.MB and (' , MemBase = %X'):format(V.MB) or ''))
  print(('VICEROY: secondary anchor (@ORDERS letters at DG+54DE): %s'):format(
    bestSec and 'OK' or 'not present (pre-boot state?) — proceeding on primary anchor'))
  V.status()
  return true
end

function V.stop()
  if V.timer then V.timer.Enabled = false end
end

-- dynamic symbols: near pointers + far map-plane pointers
local LAYERSYM = {'MAPTERRAIN', 'MAPLAYER1', 'MAPLAYER2', 'MAPFOG'}
function V.refresh()
  local dg = V.DG
  if not dg then return end
  local function nreg(sym, off)
    local p = r16(dg + off)
    pcall(unregisterSymbol, sym)
    registerSymbol(sym, dg + (p or 0), true)
  end
  nreg('CURPOWER', OFF.curpower)
  nreg('CURCOLONY', OFF.curcolony)
  nreg('CURTRIBE', OFF.curtribe)
  if V.MB then
    for i, sym in ipairs(LAYERSYM) do
      local base = OFF.layer[i]
      local o, s = r16(dg + base), r16(dg + base + 2)
      pcall(unregisterSymbol, sym)
      registerSymbol(sym, V.MB + (s or 0) * 16 + (o or 0), true)
    end
  end
end

-- ---------------------------------------------------------------- map access
function V.mapDims()
  return r16(V.DG + OFF.mapw) or 0, r16(V.DG + OFF.maph) or 0
end

function V.planeAddr(n) -- n = 0..3
  local base = OFF.layer[n + 1]
  local o, s = r16(V.DG + base), r16(V.DG + base + 2)
  if not o or not s or not V.MB then return nil end
  return V.MB + s * 16 + o
end

function V.readPlane(n)
  local w, h = V.mapDims()
  local a = V.planeAddr(n)
  if not a or w == 0 then return nil end
  return readBytes(a, w * h, true), w, h
end

-- record/HUD coords -> plane index. Direct indexing is correct (live-verified);
-- V.shift stays (0,0) unless V.calibrate() finds otherwise (diagnostic only —
-- a nonzero result usually means MemBase went wrong, not the map).
function V.tileIndex(x, y)
  local w, h = V.mapDims()
  return ((y + V.shift.dy) % h) * w + ((x + V.shift.dx) % w)
end

function V.tile(x, y)
  local a = V.planeAddr(0)
  if not a then print('map planes unavailable') return end
  local raw = r8(a + V.tileIndex(x, y))
  if not raw then return end
  local id = raw % 32
  local fold = id
  if id >= 8 and id <= 23 then fold = (id % 8) + 8 end   -- auto-forest fold (hard rule 3)
  local name = TERRAIN[fold] or ('id ' .. fold)
  local special = (math.floor(raw / 32) % 2) == 1
  local bit6 = (math.floor(raw / 64) % 2) == 1
  local bit7 = (math.floor(raw / 128) % 2) == 1
  -- per-terrain stats from the runtime table (NAMES-loaded)
  local t = V.DG + OFF.terr_base + fold * OFF.terr_stride
  print(('tile(%d,%d): raw=0x%02X id=%d %s%s%s%s | move=%s def=%s improve=%s value=%s'):format(
    x, y, raw, fold, name,
    special and ' +special(0x20)' or '', bit6 and ' +bit6' or '', bit7 and ' +bit7' or '',
    tostring(r8(t)), tostring(r8(t + 1)), tostring(r8(t + 2)), tostring(r8(t + 3))))
  return raw
end

-- Diagnostic: best-fit a (dx,dy) plane shift from live colonies/settlements/
-- ships. Expected result is (0,0); anything else indicates a broken MemBase
-- (see README §MemBase pitfall) or an unknown DOSBox memory layout.
function V.calibrate()
  local plane, w, h = V.readPlane(0)
  if not plane then print('calibrate: map planes unavailable') return end
  local anchors = {}   -- {x, y, wantWater}
  local dg = V.DG
  local nc = r16(dg + OFF.colonycount) or 0
  for i = 0, math.min(nc, 50) - 1 do
    local b = dg + OFF.colony_base + i * OFF.colony_stride
    local x, y = r8(b), r8(b + 1)
    if x and x < w and y < h and (r8(b + 2) or 0) ~= 0 then anchors[#anchors + 1] = {x, y, false} end
  end
  for i = 0, 59 do
    local b = dg + OFF.settle_base + i * OFF.settle_stride
    local x, y = r8(b), r8(b + 1)
    if not x or (x == 0 and y == 0) then break end
    if x < w and y < h then anchors[#anchors + 1] = {x, y, false} end
  end
  local nu = r16(dg + OFF.unitcount) or 0
  for i = 0, math.min(nu, 300) - 1 do
    local b = dg + OFF.unit_base + i * OFF.unit_stride
    local x, y, t = r8(b), r8(b + 1), r8(b + 2)
    if x and x < w and y < h and t and t >= 0x0D and t <= 0x12 then
      anchors[#anchors + 1] = {x, y, true}     -- naval unit -> water tile
    end
  end
  if #anchors < 5 then print('calibrate: too few anchors (' .. #anchors .. ')') return end
  local best, bx, by = -1, 0, 0
  for dy = 0, h - 1 do
    for dx = 0, w - 1 do
      local score = 0
      for _, an in ipairs(anchors) do
        local id = plane[((an[2] + dy) % h) * w + ((an[1] + dx) % w) + 1] % 32
        local water = (id == 25 or id == 26 or id == 27)
        if water == an[3] then score = score + 1 end
      end
      if score > best then best, bx, by = score, dx, dy end
    end
  end
  local pct = math.floor(100 * best / #anchors)
  V.shift.dx, V.shift.dy, V.shift.calibrated = bx, by, pct >= 85
  print(('calibrate: shift=(%d,%d) fits %d/%d anchors (%d%%)%s'):format(
    bx, by, best, #anchors, pct,
    pct >= 85 and '' or ' — LOW CONFIDENCE, shift left as best guess'))
  return bx, by, pct
end

-- ---------------------------------------------------------------- dumps
function V.status()
  local dg = V.DG
  if not dg then print('not located — run VICEROY.locate()') return end
  local w, h = V.mapDims()
  print(('year %s (turn %s, season %s) | difficulty %s | player %s | units %s | colonies %s | map %dx%d'):
    format(r16(dg + OFF.year), r16(dg + OFF.turn), r16(dg + OFF.season),
           r8(dg + OFF.difficulty), POWERS[(r16(dg + OFF.curplayer) or 0) + 1],
           r16(dg + OFF.unitcount), r16(dg + OFF.colonycount), w, h))
  print(('REF: %s regulars, %s cavalry, %s man-o-war, %s artillery | SoL meter %s'):
    format(r16(dg + OFF.ref), r16(dg + OFF.ref + 2), r16(dg + OFF.ref + 4),
           r16(dg + OFF.ref + 6), s16(r16(dg + 0x53D0))))
end

function V.powers()
  for i = 0, 3 do
    local b = V.DG + OFF.power_base + i * OFF.power_stride
    print(('%-11s tax=%s%% rebel=%s%% gold=%s bells=%s(+%s/t) crosses=%s/%s ff=%s royal=%s boycott=0x%04X'):
      format(POWERS[i + 1], r8(b + 1), r8(b + 2), r32(b + 0x2A), r16(b + 0x0C), r16(b + 0x0E),
             r16(b + 0x2E), r16(b + 0x30), r16(b + 0x14), s32(r32(b + 0x22)), r16(b + 0x20) or 0))
    print(('            prices: %s'):format(table.concat((function()
      local t = {} for g = 0, 15 do t[#t + 1] = GOODS[g + 1] .. '=' .. tostring(r8(b + 0x4C + g)) end return t
    end)(), ' ')))
  end
end

function V.colonies()
  local n = r16(V.DG + OFF.colonycount) or 0
  print(('%d colonies:'):format(n))
  for i = 0, 49 do
    local b = V.DG + OFF.colony_base + i * OFF.colony_stride
    local name = readString(b + 2, 24, false)
    if name and #name > 0 then
      print(('[%2d] %-16s (%2s,%2s) %-11s size=%s hammers=%s bank=%s target=%s SoL=%s/%s'):
        format(i, name, r8(b), r8(b + 1), POWERS[(r8(b + 0x1A) or 0) + 1], r8(b + 0x1F),
               r16(b + 0x92), r16(b + 0xB6), r8(b + 0x94), s32(r32(b + 0xC2)), s32(r32(b + 0xC6))))
      local t = {}
      for g = 0, 15 do local v = r16(b + 0x9A + g * 2) or 0
        if v > 0 then t[#t + 1] = GOODS[g + 1] .. '=' .. v end end
      if #t > 0 then print('      stock: ' .. table.concat(t, ' ')) end
    end
  end
end

function V.units(nmax)
  local n = math.min(r16(V.DG + OFF.unitcount) or 0, nmax or 40)
  for i = 0, n - 1 do
    local b = V.DG + OFF.unit_base + i * OFF.unit_stride
    local t, of = r8(b + 2) or 0, r8(b + 3) or 0
    print(('[%3d] %-13s (%2s,%2s) %-11s order=%-11s goto=(%s,%s) moves=%s tools=%s ai=%s'):
      format(i, UNITS[t + 1] or ('type ' .. t), r8(b), r8(b + 1),
             POWERS[(of % 16) + 1] or of, ORDERS[(r8(b + 8) or 0) + 1] or '?',
             r8(b + 9), r8(b + 10), r8(b + 5), r8(b + 0x15),
             string.char(math.max(32, math.min(126, r8(b + 7) or 32)))))
  end
end

function V.settlements()
  for i = 0, 59 do
    local b = V.DG + OFF.settle_base + i * OFF.settle_stride
    local x, y = r8(b), r8(b + 1)
    if not x or (x == 0 and y == 0) then break end
    local fl, mi = r8(b + 3) or 0, r8(b + 5) or 0
    print(('[%2d] (%2d,%2d) %-9s pop=%-2s %s%s'):format(i, x, y,
      POWERS[(r8(b + 2) or 0) + 1] or '?', r8(b + 4),
      (fl % 8 >= 4) and 'CAPITAL ' or '',
      mi ~= 0xFF and ('mission=' .. (POWERS[(mi % 16) + 1] or mi)) or ''))
  end
end

function V.unitStats()
  for i = 0, 22 do
    local b = V.DG + OFF.ustat_base + i * OFF.ustat_stride
    print(('%-13s move(x3)=%s att=%s def=%s cargo=%s hull=%s guns=%s'):
      format(UNITS[i + 1], r8(b + 4), r8(b + 6), r8(b + 5), r8(b + 7), r8(b + 9), r8(b + 11)))
  end
end

function V.recruits()
  for i = 0, 2 do
    local b = V.DG + OFF.recruit + i * 6
    print(('dock slot %d: type=%s cost=%s'):format(i, r8(b), r16(b + 4)))
  end
end

-- ---------------------------------------------------------------- cheats
function V.setGold(amount, power)
  local b = V.DG + OFF.power_base + (power or (r16(V.DG + OFF.curplayer) or 0)) * OFF.power_stride
  writeInteger(b + 0x2A, amount)
  print(('gold[%s] = %d'):format(POWERS[((power or 0) % 12) + 1], amount))
end

function V.revealMap(power)
  power = power or (r16(V.DG + OFF.curplayer) or 0)
  local plane, w, h = V.readPlane(3)
  if not plane then print('fog plane unavailable') return end
  local bit = 2 ^ (4 + power)
  for i = 1, w * h do
    local v = plane[i]
    if math.floor(v / bit) % 2 == 0 then plane[i] = v + bit end
  end
  writeBytes(V.planeAddr(3), plane)
  print(('map revealed for %s (fog plane OR 0x%02X)'):format(POWERS[power + 1], bit))
end

-- auto-run when loaded from the table (harmless if already attached/located)
if not V._autoran then
  V._autoran = true
  pcall(V.locate)
end
'''

LUA = (LUA
       .replace('@@ANCHOR_AOB@@', ANCHOR_AOB)
       .replace('@@ANCHOR_OFF@@', hex(ANCHOR_OFF))
       .replace('@@ANCHOR2_OFF@@', hex(ANCHOR2_OFF))
       .replace('@@ANCHOR2_STR@@', ANCHOR2_STR))


# ---------------------------------------------------------------- CT builder
_next_id = [0]


def nid():
    _next_id[0] += 1
    return _next_id[0] - 1


CT_TYPES = {'u8': 'Byte', 's8': 'Byte', 'u16': '2 Bytes', 's16': '2 Bytes',
            'u32': '4 Bytes', 's32': '4 Bytes', 'nptr': '2 Bytes'}
ELEM = {'u8[16]': ('Byte', 1, False), 'u16[16]': ('2 Bytes', 2, False),
        's16[16]': ('2 Bytes', 2, True), 's32[16]': ('4 Bytes', 4, True),
        'u16[4]': ('2 Bytes', 2, False)}


def entry(desc, addr=None, vtype=None, extra='', children=None, hide=True):
    """Render one <CheatEntry>."""
    out = [f'<CheatEntry><ID>{nid()}</ID><Description>"{escape(desc)}"</Description>']
    if addr is None and vtype is None:
        out.append('<GroupHeader>1</GroupHeader>')
        if children and hide:
            out.append('<Options moHideChildren="1"/>')
    else:
        out.append(extra)
        out.append(f'<VariableType>{vtype}</VariableType>')
        if vtype == 'Array of byte':
            pass  # ByteLength lives in extra
        if addr is not None:
            out.append(f'<Address>{escape(addr)}</Address>')
    if children:
        out.append('<CheatEntries>' + ''.join(children) + '</CheatEntries>')
    out.append('</CheatEntry>')
    return ''.join(out)


def dd(options):
    lines = '\n'.join(f'{i}:{escape(name)}' for i, name in enumerate(options))
    return f'<DropDownList DescriptionOnly="0" DisplayValueAsItem="1">{lines}\n</DropDownList>'


def scalar_entry(desc, addr, ftype, hexs=False, signed=False, dropdown=None):
    extra = ''
    if hexs:
        extra += '<ShowAsHex>1</ShowAsHex>'
    if signed or ftype in ('s8', 's16', 's32'):
        extra += '<ShowAsSigned>1</ShowAsSigned>'
    if dropdown:
        extra += dd(INV['dropdowns'][dropdown])
    return entry(desc, addr, CT_TYPES[ftype], extra)


def string_entry(desc, addr, length):
    extra = f'<Length>{length}</Length><Unicode>0</Unicode><CodePage>0</CodePage><ZeroTerminate>1</ZeroTerminate>'
    return entry(desc, addr, 'String', extra)


def aob_entry(desc, addr, length):
    return entry(desc, addr, 'Array of byte', f'<ByteLength>{length}</ByteLength>')


def field_entries(prefix, fields, filt=None):
    """Render a record's field list anchored at `prefix` (e.g. 'DG+8808' or 'CURPOWER')."""
    out = []
    for f in fields:
        if filt and f['name'] not in filt:
            continue
        addr = f'{prefix}+{f["off"]:X}' if f['off'] else prefix
        t = f['type']
        tier = f.get('tier', '')
        desc = f'{f["name"]} [{tier}]'
        if t in CT_TYPES:
            out.append(scalar_entry(desc, addr, t, f.get('hex', False), dropdown=f.get('dropdown')))
        elif t.startswith('str:'):
            out.append(string_entry(desc, addr, int(t[4:])))
        elif t.startswith('aob:'):
            out.append(aob_entry(desc, addr, int(t[4:])))
        elif t in ELEM:
            vt, esz, sgn = ELEM[t]
            labels = INV['dropdowns'].get(f.get('dropdown_index', ''), None)
            kids = []
            for i in range(int(t.split('[')[1][:-1])):
                lab = labels[i] if labels and i < len(labels) else str(i)
                kids.append(entry(f'[{i:2d}] {lab}', f'{addr}+{i * esz:X}', vt,
                                  '<ShowAsSigned>1</ShowAsSigned>' if sgn else ''))
            out.append(entry(f'{f["name"]} [{tier}]', children=kids))
        else:
            raise ValueError(f'unhandled type {t} for {f["name"]}')
    return out


def build_ct():
    R = INV['records']
    G = {g['name']: g for g in INV['globals']}

    def g_entry(name, desc=None):
        g = G[name]
        t = g['type']
        addr = f'DG+{int(g["off"], 16):X}'
        d = desc or f'{name} [{g.get("tier", "")}]'
        if t in CT_TYPES:
            return scalar_entry(d, addr, t, g.get('hex', False), dropdown=g.get('dropdown'))
        if t.startswith('str:'):
            return string_entry(d, addr, int(t[4:]))
        if t.startswith('aob:'):
            return aob_entry(d, addr, int(t[4:]))
        if t in ELEM:
            return field_entries('DG', [dict(g, off=int(g['off'], 16))])[0]
        if t == 'fptr':
            off = int(g['off'], 16)
            kids = [scalar_entry('offset', f'DG+{off:X}', 'u16', True),
                    scalar_entry('segment', f'DG+{off + 2:X}', 'u16', True)]
            return entry(d, children=kids)
        raise ValueError(f'unhandled global type {t} ({name})')

    roots = []

    # 0) locate script
    aa = ('[ENABLE]\n{$lua}\nif syntaxcheck then return end\n'
          "if VICEROY == nil then error('table Lua not loaded — answer Yes to the table-script prompt') end\n"
          'VICEROY.locate()\n{$asm}\n[DISABLE]\n{$lua}\nif syntaxcheck then return end\n'
          'if VICEROY then VICEROY.stop() end\n{$asm}\n')
    roots.append('<CheatEntry>'
                 f'<ID>{nid()}</ID>'
                 '<Description>"── LOCATE VICEROY (activate after loading a game; auto-runs on table load) ──"</Description>'
                 '<VariableType>Auto Assembler Script</VariableType>'
                 f'<AssemblerScript>{escape(aa)}</AssemblerScript>'
                 '</CheatEntry>')

    # 1) game state
    gs = [g_entry(n) for n in ['year', 'season', 'turn', 'difficulty', 'current_power',
                               'active_power_idx', 'unit_count', 'colony_count', 'game_flags',
                               'sol_meter', 'revolting_power', 'self_power', 'endgame_forced_flag',
                               'mainloop_gate', 'year_div100', 'year_mod100', 'rng_seed',
                               'periodic_counter', 'save_scratch_372']]
    roots.append(entry('GAME STATE (globals)', children=gs, hide=False))

    # 2) King & REF
    kr = [g_entry(n) for n in ['ref_regulars', 'ref_cavalry', 'ref_manowar', 'ref_artillery']]
    kr.append(scalar_entry('royal_money (active power) [B]', 'CURPOWER+22', 's32'))
    kr.append(scalar_entry('tax_pct (active power) [B]', 'CURPOWER+1', 'u8'))
    roots.append(entry('KING & ROYAL EXPEDITIONARY FORCE', children=kr, hide=False))

    # 3) active power
    roots.append(entry('ACTIVE POWER (CURPOWER = DG+[DG+84FC])',
                       children=field_entries('CURPOWER', R['PowerRecord']['fields'])))

    # 4) four powers
    pcore = ['flags0', 'tax_pct', 'rebel_sentiment_pct', 'ff_bitmask', 'bells_pool',
             'bells_per_turn', 'crosses_per_turn', 'ff_pending', 'ff_count', 'artillery_bought',
             'boycott_mask', 'royal_money', 'sales_gross_accum', 'gold', 'crosses_pool',
             'crosses_target', 'home_x', 'home_y', 'war_matrix_row', 'treaty_matrix_row',
             'ref_bytes_conflicted', 'free_immigrant_queue', 'recruit_point_pool',
             'price_level', 'market_pool']
    base = int(R['PowerRecord']['base'], 16)
    stride = int(R['PowerRecord']['stride'], 16)
    pw = []
    for i, nm in enumerate(INV['dropdowns']['powers4']):
        pw.append(entry(f'PowerRecord[{i}] {nm} @DG+{base + i * stride:X}',
                        children=field_entries(f'DG+{base + i * stride:X}',
                                               R['PowerRecord']['fields'], filt=pcore)))
    roots.append(entry('EUROPEAN POWERS (PowerRecord 0x8808, stride 0x13C)', children=pw))

    # 5) active colony + colony slots
    roots.append(entry('ACTIVE COLONY (CURCOLONY = DG+[DG+8542])',
                       children=field_entries('CURCOLONY', R['ColonyRecord']['fields'])))
    cbase = int(R['ColonyRecord']['base'], 16)
    cstride = int(R['ColonyRecord']['stride'], 16)
    ccore = ['map_x', 'map_y', 'name', 'owner', 'size', 'status_flags', 'colonist_jobs',
             'buildings_constructed', 'tile_workers', 'hammers', 'build_target',
             'build_progress', 'warehouse_level', 'stockpile', 'sol_dividend', 'sol_divisor']
    cs = []
    for i in range(8):
        cs.append(entry(f'ColonyRecord[{i}] @DG+{cbase + i * cstride:X}',
                        children=field_entries(f'DG+{cbase + i * cstride:X}',
                                               R['ColonyRecord']['fields'], filt=ccore)))
    roots.append(entry('COLONIES (0x5D46, stride 0xCA; slots 0-7 — full list: VICEROY.colonies())',
                       children=cs))

    # 6) units
    ubase = int(R['UnitRecord']['base'], 16)
    ustride = int(R['UnitRecord']['stride'], 16)
    us = []
    for i in range(12):
        us.append(entry(f'UnitRecord[{i}] @DG+{ubase + i * ustride:X}',
                        children=field_entries(f'DG+{ubase + i * ustride:X}',
                                               R['UnitRecord']['fields'])))
    roots.append(entry('UNITS (0x3144, stride 0x1C; slots 0-11 — full list: VICEROY.units(n))',
                       children=us))

    # 7) native settlements
    sbase = int(R['NativeSettlement']['base'], 16)
    sstride = int(R['NativeSettlement']['stride'], 16)
    ss = []
    for i in range(12):
        ss.append(entry(f'NativeSettlement[{i}] @DG+{sbase + i * sstride:X}',
                        children=field_entries(f'DG+{sbase + i * sstride:X}',
                                               R['NativeSettlement']['fields'])))
    roots.append(entry('NATIVE SETTLEMENTS (0x54EC, stride 0x12 — full list: VICEROY.settlements())',
                       children=ss))

    # 8) AI personalities + tribes
    abase = int(R['AIPersonality']['base'], 16)
    astride = int(R['AIPersonality']['stride'], 16)
    ai = []
    for i, nm in enumerate(INV['dropdowns']['powers4']):
        ai.append(entry(f'AIPersonality[{i}] {nm} @DG+{abase + i * astride:X}',
                        children=field_entries(f'DG+{abase + i * astride:X}',
                                               R['AIPersonality']['fields'])))
    tbase = int(R['TribeData']['base'], 16)
    for i in range(8):
        ai.append(scalar_entry(f'TribeData[{i}] {INV["dropdowns"]["powers12"][4 + i]} settlement_size_factor [B]',
                               f'DG+{tbase + i * 0x4E + 2:X}', 'u8'))
    ai += [g_entry('cur_tribe_ptr'), g_entry('cur_tribe_power'), g_entry('cur_tribe_idx')]
    roots.append(entry('AI PERSONALITIES & TRIBES', children=ai))

    # 9) map & viewport
    mp = [g_entry(n) for n in ['map_width', 'map_height', 'selected_tile_x', 'selected_tile_y',
                               'viewport_x', 'viewport_y', 'span_w', 'span_h',
                               'viewport_px_w', 'viewport_px_h', 'tile_px', 'map_filename',
                               'terrain_display_mode', 'fog_test_mask',
                               'map_layer0_terrain', 'map_layer1_units', 'map_layer2', 'map_layer3_fog']]
    mp.append(entry('terrain plane byte @plane(0,0) (see VICEROY.tile(x,y) for shifted lookups)',
                    'MAPTERRAIN', 'Byte', '<ShowAsHex>1</ShowAsHex>'))
    roots.append(entry('MAP & VIEWPORT', children=mp, hide=False))

    # 10) markets & economy reference
    ec = [g_entry('price_seed')]
    rp = int('0x978C', 16)
    for i in range(3):
        ec.append(entry(f'recruit dock slot {i}', children=[
            scalar_entry('type [B]', f'DG+{rp + i * 6:X}', 'u8'),
            scalar_entry('cost [B]', f'DG+{rp + i * 6 + 4:X}', 'u16')]))
    ustat = INV['tables_static'][1]
    ub2 = int(ustat['base'], 16)
    rows = []
    for i, nm in enumerate(INV['dropdowns']['unit_type']):
        b2 = ub2 + i * 14
        rows.append(entry(f'{nm}', children=[
            scalar_entry('movement (x3) [B]', f'DG+{b2 + 4:X}', 'u8'),
            scalar_entry('defense [B]', f'DG+{b2 + 5:X}', 'u8'),
            scalar_entry('attack [B]', f'DG+{b2 + 6:X}', 'u8'),
            scalar_entry('cargo holds [B]', f'DG+{b2 + 7:X}', 'u8'),
            scalar_entry('hull [B]', f'DG+{b2 + 9:X}', 'u8'),
            scalar_entry('guns [B]', f'DG+{b2 + 11:X}', 'u8')]))
    ec.append(entry('@UNIT runtime stat table (0x5230, stride 14) — EDITABLE', children=rows))
    roots.append(entry('ECONOMY & STAT TABLES', children=ec))

    # 11) UI / debug globals
    ui = [g_entry(n) for n in ['ui_cursor_x', 'ui_cursor_y', 'dialog_state', 'font_cell_w',
                               'font_cell_h', 'capital_raze_gold', 'capital_raze_count',
                               'game_flags2', 'unit_job_map', 'country_flag_frame',
                               'leader_bias', 'per_power_unit_count', 'per_power_colony_stat',
                               'ai_attitude', 'smite_factor_w', 'smite_factor_b',
                               'ref_landed_record', 'ref_add_table',
                               'cur_power_ptr', 'cur_colony_ptr']]
    roots.append(entry('UI / DEBUG / MISC GLOBALS', children=ui))

    # 12) cheats
    ch = [scalar_entry('Gold (active power) — write 99999 here [B]', 'CURPOWER+2A', 'u32'),
          scalar_entry('Tax rate (active power) — write 0 [B]', 'CURPOWER+1', 'u8'),
          scalar_entry('Bells toward next Founding Father [B]', 'CURPOWER+C', 'u16'),
          scalar_entry('National SoL meter (>=50 enables Declaration) [B]', 'DG+53D0', 's16'),
          scalar_entry('Boycott mask — write 0 to lift all [B]', 'CURPOWER+20', 'u16', hexs=True),
          g_entry('ref_regulars', 'REF Regulars — 0 to disband [B]'),
          g_entry('ref_cavalry', 'REF Cavalry — 0 to disband [B]'),
          g_entry('ref_manowar', 'REF Man-O-War — 0 to disband [B]'),
          g_entry('ref_artillery', 'REF Artillery — 0 to disband [B]')]
    roots.append(entry('CHEATS (write-here shortcuts; Lua: VICEROY.setGold / VICEROY.revealMap)',
                       children=ch, hide=False))

    xml = ('<?xml version="1.0" encoding="utf-8"?>\n'
           '<CheatTable CheatEngineTableVersion="42">\n'
           '<CheatEntries>\n' + '\n'.join(roots) + '\n</CheatEntries>\n'
           '<UserdefinedSymbols/>\n'
           f'<LuaScript>{escape(LUA)}</LuaScript>\n'
           '</CheatTable>\n')
    return xml


def main():
    verify_anchor_against_exe()
    ct = build_ct()
    import xml.dom.minidom
    xml.dom.minidom.parseString(ct)  # well-formedness gate
    open(os.path.join(HERE, 'VICEROY_DOSBOX.CT'), 'w', encoding='utf-8').write(ct)
    open(os.path.join(HERE, 'viceroy_dosbox.lua'), 'w', encoding='utf-8').write(LUA)
    n = _next_id[0]
    print(f'wrote VICEROY_DOSBOX.CT ({n} entries) and viceroy_dosbox.lua')


if __name__ == '__main__':
    main()
