/* Generated by tools/gen_sd_pack.py — DO NOT hand-edit.
 * COLOPY.PAK layout (little-endian). Codec provenance and the
 * per-kind payload formats are documented in the generator's
 * docstring; the container is the microSD asset pack for the
 * Teensy build (C-port Phase 6). */
#ifndef COLOPY_PAK_H
#define COLOPY_PAK_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>

#define COLOPY_PAK_MAGIC   "CPAK"
#define COLOPY_PAK_COUNT   217
#define COLOPY_PAK_NAMELEN 12
#define COLOPY_PAK_HDRLEN  6           /* magic + u16 count */
#define COLOPY_PAK_TOCENT  26          /* name[12] u32 off u32 len u16 w,h,frames */
#define COLOPY_SS_TRANSPARENT 0xFD     /* rle_decode sentinel */

/* TOC entry, parsed field-wise (the on-disk record is unaligned):
 *   +0  char name[12]   NUL-padded (no NUL when the name is 12 chars)
 *   +12 u32  offset     from the start of the pak file
 *   +16 u32  len        payload length in bytes
 *   +20 u16  w, h       sheets: max frame dims; PIK: image dims;
 *                       FF: max glyph width / cell height H
 *   +24 u16  frames     sheets: frame count; FF: 128; PAL: 256
 *
 * Sheet payload:  u16 nframes, u16 flags (bit0 = 768-byte RGB888
 *   palette appended), nframes * { i16 x, i16 y, u16 w, u16 h,
 *   u32 off (payload-relative) }, 8-bit pixels (0xFD transparent).
 * PIK payload:    w*h 8-bit pixels [+ 768-byte RGB888 palette].
 * FF payload:     [H][maxw][128 width bytes][128 u16 offsets]
 *   [2bpp MSB-first bitmaps] — width(ch) = table[ch-1], per
 *   formats/FF.md and func_00E51C @0x00E5DA.
 * VICEROY.PAL:    768 bytes RGB888 ((v6<<2)|(v6>>4)).
 * CYCLE:          u16 start, u16 len, u16 delay (CYCLE.DAT band).
 * TEXT:           u32 n, n * { u32 key_off, u32 val_off },
 *   NUL-terminated UTF-8 pool (offsets payload-relative) — the
 *   colopy_text.c content, SD-served when flash drops that unit. */

static const char *const COLOPY_PAK_NAMES[COLOPY_PAK_COUNT] = {
    "BUILDING.SS", "CC-00.SS", "CC-01.SS", "CC-02.SS",
    "CC-03.SS", "CC-04.SS", "CC-05.SS", "CC-06.SS",
    "CC-07.SS", "CC-08.SS", "CC-09.SS", "CC-10.SS",
    "CC-11.SS", "CC-12.SS", "CC-13.SS", "CC-14.SS",
    "CC-15.SS", "CC-16.SS", "CC-17.SS", "CC-18.SS",
    "CC-19.SS", "CC-20.SS", "CC-21.SS", "CC-22.SS",
    "CC-23.SS", "CC-24.SS", "CURSOR.SS", "DEC-LOWA.SS",
    "DEC-LOWB.SS", "DEC-LOWC.SS", "DEC-LOWD.SS", "DEC-LOWE.SS",
    "DEC-LOWF.SS", "DEC-LOWG.SS", "DEC-LOWH.SS", "DEC-LOWI.SS",
    "DEC-LOWJ.SS", "DEC-LOWK.SS", "DEC-LOWL.SS", "DEC-LOWM.SS",
    "DEC-LOWN.SS", "DEC-LOWO.SS", "DEC-LOWP.SS", "DEC-LOWQ.SS",
    "DEC-LOWR.SS", "DEC-LOWS.SS", "DEC-LOWT.SS", "DEC-LOWU.SS",
    "DEC-LOWV.SS", "DEC-LOWW.SS", "DEC-LOWX.SS", "DEC-LOWY.SS",
    "DEC-LOWZ.SS", "DEC-SQIG.SS", "DEC-UPPA.SS", "DEC-UPPB.SS",
    "DEC-UPPC.SS", "DEC-UPPD.SS", "DEC-UPPE.SS", "DEC-UPPF.SS",
    "DEC-UPPG.SS", "DEC-UPPH.SS", "DEC-UPPI.SS", "DEC-UPPJ.SS",
    "DEC-UPPK.SS", "DEC-UPPL.SS", "DEC-UPPM.SS", "DEC-UPPN.SS",
    "DEC-UPPO.SS", "DEC-UPPP.SS", "DEC-UPPQ.SS", "DEC-UPPR.SS",
    "DEC-UPPS.SS", "DEC-UPPT.SS", "DEC-UPPU.SS", "DEC-UPPV.SS",
    "DEC-UPPW.SS", "DEC-UPPX.SS", "DEC-UPPY.SS", "DEC-UPPZ.SS",
    "DUTCH1.SS", "DUTCH2.SS", "ENGLND1.SS", "ENGLND2.SS",
    "FRANCE1.SS", "FRANCE2.SS", "ICONS.SS", "IND0A0.SS",
    "IND0A1.SS", "IND0A2.SS", "IND0A3.SS", "IND1A0.SS",
    "IND1A1.SS", "IND1A2.SS", "IND1A3.SS", "IND2A0.SS",
    "IND2A1.SS", "IND2A2.SS", "IND2A3.SS", "IND3A0.SS",
    "IND3A1.SS", "IND3A2.SS", "IND3A3.SS", "IND4A0.SS",
    "IND4A1.SS", "IND4A2.SS", "IND4A3.SS", "IND5A0.SS",
    "IND5A1.SS", "IND5A2.SS", "IND5A3.SS", "IND6A0.SS",
    "IND6A1.SS", "IND6A2.SS", "IND6A3.SS", "IND7A0.SS",
    "IND7A1.SS", "IND7A2.SS", "IND7A3.SS", "KING.SS",
    "KING1.SS", "KINGLOSE.SS", "KINGWIN.SS", "MPSLOGO.SS",
    "MPSNAME.SS", "MSS0.SS", "MSS1.SS", "MSS2.SS",
    "MSS3.SS", "MSS4.SS", "MSS5.SS", "MYR0.SS",
    "MYR1.SS", "MYR2.SS", "MYR3.SS", "NAMEPLAT.SS",
    "OPENTILE.SS", "PARCH.SS", "PHYS0.SS", "SCORE01.SS",
    "SCORE02.SS", "SCORE03.SS", "SCORE04.SS", "SCORE05.SS",
    "SCORE06.SS", "SCORE07.SS", "SCORE08.SS", "SCORE09.SS",
    "SCORE10.SS", "SCORE11.SS", "SCORE12.SS", "SCORE13.SS",
    "SCORE14.SS", "SCORE15.SS", "SCORE16.SS", "SCORE17.SS",
    "SCORE18.SS", "SCORE19.SS", "SCORE20.SS", "SCORE21.SS",
    "SCORE22.SS", "SCORE23.SS", "SCORE24.SS", "SPAIN1.SS",
    "SPAIN2.SS", "TERRAIN.SS", "WDCUT01.SS", "WDCUT02.SS",
    "WDCUT03.SS", "WDCUT04.SS", "WDCUT05.SS", "WDCUT07.SS",
    "WDCUT08.SS", "WDCUT09.SS", "WDCUT10.SS", "WDCUT11.SS",
    "WDCUT13.SS", "WOODFRAM.SS", "WOODTILE.SS", "CCBKGD.PIK",
    "COLONY.PIK", "DECOIND.PIK", "DIFFICUL.PIK", "EUROPE.PIK",
    "KINGLSS1.PIK", "KINGLSS2.PIK", "LEVN0001.PIK", "LEVN0002.PIK",
    "LEVN0003.PIK", "LEVN0004.PIK", "LEVN0005.PIK", "LEVN0006.PIK",
    "LEVN0007.PIK", "LEVN0008.PIK", "LEVN0009.PIK", "LEVN0010.PIK",
    "NATIONS.PIK", "OPENMENU.PIK", "REPORT1.PIK", "REPORT2.PIK",
    "REPORT3.PIK", "REPORT4.PIK", "REPORT5.PIK", "REPORT6.PIK",
    "REPORT7.PIK", "REPORT8.PIK", "REPORT9.PIK", "WOODPAN2.PIK",
    "WOODPANL.PIK", "FONT-NP.FF", "FONTINTR.FF", "FONTKING.FF",
    "FONTSMAL.FF", "FONTTINY.FF", "VICEROY.PAL", "CYCLE",
    "TEXT",
};

#ifdef __cplusplus
}
#endif
#endif /* COLOPY_PAK_H */
