#!/usr/bin/env python3
"""Build the unified sprite catalog: every sprite separated from its sheet, identified, labeled.

Unifies the per-sheet tileset manifests (units/buildings/terrain/phys0) + the Founding-Father
portraits (CC-##) + woodcuts (WDCUT##) + full-screen backgrounds (pik/*) into ONE data table,
data_extracted/engine/sprites.json. Everything else (screens, messages, map, units) references a
sprite by its stable id/label, resolved through this catalog -- no raw sheet+frame guesses.

Each record: {id, label, kind, sheet, frame|file, w, h}. Usage: python3 tools/build_sprites.py
"""
import json, os, re, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def rd(p): return json.load(open(os.path.join(ROOT, p)))
def slug(s): return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")

def main():
    sprites = []
    names = rd("data_extracted/tables/names_tables.json")

    # --- units (ICONS sheet): 24 labeled types -> frame indices ---
    u = rd("data_extracted/tileset/units.json")
    for i, label in enumerate(u["types"]):
        if label == "(unused)": continue
        sprites.append({"id": "unit." + slug(label), "label": label, "kind": "unit",
                        "sheet": "ICONS", "frame": u["frames"][i], "w": u["cell"], "h": u["cell"]})

    # --- buildings (BUILDING sheet): frame = @BUILDING def_id + 1 (buildings.json note) ---
    b = rd("data_extracted/tileset/buildings.json")
    brows = names["@BUILDING"]["rows"]
    for frame in range(1, b["drawn"] + 1):
        did = frame - 1
        label = brows[did]["name"] if did < len(brows) else f"building #{did}"
        sprites.append({"id": "building." + slug(label) + (f".{frame}" if did >= len(brows) else ""),
                        "label": label, "kind": "building", "sheet": "BUILDING",
                        "frame": frame, "w": b["cell_w"], "h": b["cell_h"]})

    # --- terrain (TERRAIN sheet): 12 named base grounds ---
    tr = rd("data_extracted/tileset/terrain16.json")
    for i, label in enumerate(tr["names"]):
        sprites.append({"id": "terrain." + slug(label), "label": label, "kind": "terrain",
                        "sheet": "TERRAIN", "frame": i, "w": 16, "h": 16})

    # --- phys0 overlays: 154 frames (rivers/forest/features) ---
    p0 = rd("data_extracted/tileset/phys0.json")
    for i in range(p0["count"]):
        sprites.append({"id": f"overlay.phys0_{i}", "label": f"PHYS0 frame {i}", "kind": "overlay",
                        "sheet": "PHYS0", "frame": i, "w": 16, "h": 16})

    # --- Founding-Father portraits: CC-00..24 <-> @FATHERS names ---
    fa = names.get("@FATHERS") or names.get("@FOUNDING")
    if fa:
        for i, r in enumerate(fa["rows"]):
            f = f"atlas_CC-{i:02d}.png"
            if os.path.exists(os.path.join(ROOT, "docs/atlas/sprites", f)):
                sprites.append({"id": "father." + slug(r["name"]), "label": r["name"], "kind": "portrait",
                                "sheet": f"CC-{i:02d}", "file": "sprites/" + f, "w": 0, "h": 0})

    # --- woodcuts (scene illustrations) WDCUT## ---
    for f in sorted(glob.glob(os.path.join(ROOT, "docs/atlas/sprites/atlas_WDCUT*.png"))):
        n = os.path.basename(f)[6:-4]  # strip atlas_ / .png
        sprites.append({"id": "woodcut." + slug(n), "label": n, "kind": "woodcut",
                        "sheet": n, "file": "sprites/" + os.path.basename(f), "w": 0, "h": 0})

    # --- full-screen backgrounds (pik/*) ---
    for f in sorted(glob.glob(os.path.join(ROOT, "docs/atlas/pik/*.png"))):
        n = os.path.basename(f)[:-4]
        sprites.append({"id": "bg." + slug(n), "label": n, "kind": "background",
                        "sheet": n, "file": "pik/" + os.path.basename(f), "w": 0, "h": 0})

    kinds = {}
    for s in sprites: kinds[s["kind"]] = kinds.get(s["kind"], 0) + 1
    out = {"_note": ("The sprite catalog: every sprite separated from its sheet, identified, and "
                     "labeled. Reference a sprite anywhere by its `id` (e.g. unit.soldiers, "
                     "building.fort, father.adam_smith, woodcut.wdcut04, bg.colony). `sheet`+`frame` "
                     "for atlas grids (ICONS/BUILDING/TERRAIN/PHYS0), `file` for standalone PNGs. "
                     "Generated by tools/build_sprites.py."),
           "kind_counts": kinds, "count": len(sprites), "sprites": sprites}
    json.dump(out, open(os.path.join(ROOT, "data_extracted/engine/sprites.json"), "w"), indent=1)
    print(f"sprites.json: {len(sprites)} sprites {kinds}")

if __name__ == "__main__":
    main()
