#!/usr/bin/env python3
"""
build_catalogs.py — Build SPRITE_CATALOG.md, BACKGROUND_CATALOG.md,
FONT_CATALOG.md from the extracted assets.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPRITES = ROOT / "assets" / "sprites"
BACKGROUNDS = ROOT / "assets" / "backgrounds"
FONTS = ROOT / "assets" / "fonts"

# Sprite category mapping per the plan's tile naming rules.
SPRITE_CATEGORIES = [
    ("PHYS0",        "Main terrain tiles"),
    ("TERRAIN",      "Per-terrain textured ground"),
    ("ICONS",        "UI icons + map units"),
    ("BUILDING",     "Colony building sprites"),
    ("CC-",          "Founding Father portraits"),
    ("IND",          "Native tribe sprites (8 tribes × 4 dirs × 4 frames)"),
    ("MSS",          "Settlement variants"),
    ("MYR",          "Settlement variants"),
    ("KING",         "King portraits + variants"),
    ("DUTCH",        "Dutch nation art"),
    ("ENGLND",       "English nation art"),
    ("FRANCE",       "French nation art"),
    ("SPAIN",        "Spanish nation art"),
    ("DEC-LOW",      "Lowercase decorative letters (Declaration display)"),
    ("DEC-UPP",      "Uppercase decorative letters (Declaration display)"),
    ("DEC-SQIG",     "Decorative squiggle"),
    ("SCORE",        "Score-screen plates (24 plates)"),
    ("OPEN",         "Opening cinematic frames"),
    ("CLOS-",        "Closing cinematic frames"),
    ("WDCUT",        "Woodcut-style art"),
    ("MPSLOGO",      "MicroProse logo"),
    ("MPSNAME",      "MicroProse name"),
    ("WIN",          "Endgame screens"),
    ("CURSOR",       "Mouse cursor"),
    ("NAMEPLAT",     "Name plate UI"),
    ("PARCH",        "Parchment background"),
    ("WOODFRAM",     "UI wood frame"),
    ("WOODTILE",     "UI wood-panel tile"),
    ("BDARK",        "ORPHAN — do not load (per CLAUDE.md hard rule)"),
]


def categorize(name: str) -> str:
    for prefix, desc in SPRITE_CATEGORIES:
        if name.upper().startswith(prefix):
            return desc
    return "(uncategorized)"


def build_sprite_catalog():
    """Walk assets/sprites/ and produce SPRITE_CATALOG.md."""
    out = ["# Sprite Catalog\n",
           "Generated by `tools/build_catalogs.py`. Each entry shows the .SS sheet's frame count and inferred role.\n",
           "Sprite frames are at `assets/sprites/<NAME>/<NAME>.SS.NNN.png`.\n",
           "",
           "| Sheet | Frames | Category | Notes |",
           "|-------|------:|----------|-------|"]

    if not SPRITES.exists():
        print(f"  no sprites directory; skipping")
        return

    sheets = sorted(SPRITES.iterdir())
    total_frames = 0
    for sheet in sheets:
        if not sheet.is_dir():
            continue
        loader_path = sheet / "loader.json"
        if loader_path.exists():
            loader = json.loads(loader_path.read_text())
            frames = loader.get("frames_or_glyphs_count", 0)
        else:
            pngs = list(sheet.glob("*.png"))
            frames = len([p for p in pngs if "pal" not in p.name.lower()])
        category = categorize(sheet.name)
        out.append(f"| `{sheet.name}` | {frames} | {category} | |")
        total_frames += frames

    out.insert(2, f"\n**Total**: {len(sheets)} sheets, {total_frames} frames extracted.\n")
    catalog = SPRITES / "SPRITE_CATALOG.md"
    catalog.write_text("\n".join(out))
    print(f"  wrote {catalog} ({len(sheets)} sheets, {total_frames} total frames)")


def build_background_catalog():
    """Walk assets/backgrounds/ and produce BACKGROUND_CATALOG.md."""
    if not BACKGROUNDS.exists():
        print("  no backgrounds directory; skipping")
        return

    role_map = {
        "OPENING":   "Title screen background",
        "OPENBORD":  "Opening border decoration",
        "OPENMENU":  "Opening menu screen",
        "COLONY":    "Colony management screen background",
        "EUROPE":    "Europe screen background",
        "CCBKGD":    "Continental Congress background",
        "CUSTOMIZ":  "Game customization screen",
        "DECLARAT":  "Declaration of Independence document image",
        "DECOIND":   "Declaration deco-image",
        "DIFFICUL":  "Difficulty selection",
        "KINGLSS1":  "King-loses screen 1",
        "KINGLSS2":  "King-loses screen 2",
        "NATIONS":   "Nation selection",
        "WOODPAN2":  "UI wood-panel background",
        "WOODPANL":  "UI wood-panel background",
        "CLOS-BKG":  "Closing cinematic background",
    }

    out = ["# Background Catalog\n",
           "Generated by `tools/build_catalogs.py`. Each .PIK is a 320×200 background.",
           "",
           "| File | Role | PNG location |",
           "|------|------|---------------|"]

    sheets = sorted(BACKGROUNDS.iterdir())
    for sheet in sheets:
        if not sheet.is_dir():
            continue
        role = role_map.get(sheet.name, None)
        if role is None and sheet.name.startswith("REPORT"):
            role = f"Report screen {sheet.name[6:].lstrip('0') or '0'}"
        if role is None and sheet.name.startswith("LEVN"):
            role = f"Scenario thumbnail {sheet.name[4:].lstrip('0') or '0'}"
        if role is None:
            role = "(uncategorized)"
        pngs = list(sheet.glob("*.png"))
        png = pngs[0].relative_to(BACKGROUNDS) if pngs else "(no png)"
        out.append(f"| `{sheet.name}` | {role} | `{png}` |")

    catalog = BACKGROUNDS / "BACKGROUND_CATALOG.md"
    catalog.write_text("\n".join(out))
    print(f"  wrote {catalog} ({len(sheets)} backgrounds)")


def build_font_catalog():
    """Walk assets/fonts/ and produce FONT_CATALOG.md."""
    if not FONTS.exists():
        print("  no fonts directory; skipping")
        return

    role_map = {
        "FONTINTR":  "Intro/title font (large stylized)",
        "FONTKING":  "King text font (large)",
        "FONT-NP":   "No-press font (disabled menu items)",
        "FONTSMAL":  "Standard small UI font",
        "FONTTINY":  "Smallest dialog text",
    }

    out = ["# Font Catalog\n",
           "Generated by `tools/build_catalogs.py`. Each .FF holds bitmap glyphs.",
           "",
           "| File | Role | Glyphs | PNG location |",
           "|------|------|------:|---------------|"]

    fonts = sorted(FONTS.iterdir())
    for font in fonts:
        if not font.is_dir():
            continue
        role = role_map.get(font.name, "(uncategorized)")
        loader_path = font / "loader.json"
        if loader_path.exists():
            glyphs = json.loads(loader_path.read_text()).get("frames_or_glyphs_count", 0)
        else:
            glyphs = len(list(font.glob("*.png")))
        out.append(f"| `{font.name}` | {role} | {glyphs} | `{font.name}/` |")

    catalog = FONTS / "FONT_CATALOG.md"
    catalog.write_text("\n".join(out))
    print(f"  wrote {catalog} ({len(fonts)} fonts)")


def main():
    print("Building visual asset catalogs...")
    build_sprite_catalog()
    build_background_catalog()
    build_font_catalog()
    print("Done.")


if __name__ == "__main__":
    main()
