#!/usr/bin/env python3
"""Build the message catalog: every GAME.TXT @KEY as a record {key, text, box_w, x, y, sprite}.

The message IS the data. A ShowPopup/Notify carries only the @KEY; the displayed text is the
verbatim GAME.TXT body (no authored title/body), sized to the box the original used, with its
associated sprite. Text + geometry come byte-accurately from GAME.full.json (the @width/@x/@y
directives); the woodcut/scene sprite comes from the spec/ui/popups.md associations.

box_h is not stored -- it's computed at render from the line count (popups.md content_h). box_w
is the @width floor (0 = auto-fit to the longest line). x/y = -1 means centered. sprite is a
sprite-catalog id (woodcut.*) or "" (unknown/none). Usage: python3 tools/build_messages.py
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Woodcut <-> key associations, grounded in spec/ui/popups.md (lines 268/305/333/383/400/463).
WOODCUT = {
    "woodcut.wdcut04": ["@CASHTREASURE", "@KINGGALLEON2", "@KINGGALLEON3", "@LOOT", "@LOOT2",
                        "@LOOTCAPTURE", "@LOOTCASH", "@LOOTFOREIGN", "@NOLOOT", "@BURIAL", "@BURIAL2",
                        "@BURIAL3", "@LOSTCITY", "@TREASURE"],
    "woodcut.wdcut10": ["@ARTILLERY", "@ARTILLERY2", "@CARGOCAPTURE", "@COLONISTCAPTURE",
                        "@COLONISTCAPTURE2", "@DEMOTE", "@SHIPDAMAGE", "@VALOR", "@VETERAN",
                        "@WAGONCAPTURE", "@WELLSEASONED"],
    "woodcut.wdcut11": ["@BURNED", "@BURNED2", "@BURNED3", "@CAPTURED", "@CAPTURED2", "@CAPTURED3",
                        "@EUROPELOSE", "@EUROPEWIN", "@INDIANBURNCOLONY", "@INDIANBURNCOLONY2",
                        "@INDIANWINCOLONY", "@INDIANWINCOLONY2"],
    "woodcut.wdcut12": ["@CHIEFKILL", "@INDIANBURN", "@INDIANGOLD"],
    "woodcut.wdcut13": ["@INDIAN", "@INDIANGRUDGE", "@INDIANSURPRISE", "@INDIANWAR", "@INDIANWARFARE",
                        "@INDIANWARPATH", "@INDIANWARPATH2"],
}
KEY2WOODCUT = {}
for wc, keys in WOODCUT.items():
    for k in keys: KEY2WOODCUT[k] = wc

def to_int(v, default):
    try: return int(v)
    except (ValueError, TypeError): return default

def main():
    full = json.load(open(os.path.join(ROOT, "data_extracted/text/GAME.full.json")))
    sections = full["sections"]
    rows = []
    for key, sec in sections.items():
        dv = sec.get("directives", {})
        rows.append({
            "key": key,
            "text": sec.get("body", ""),
            "box_w": to_int(dv.get("width"), 0),      # @width floor; 0 = auto-fit
            "x": to_int(dv.get("x"), -1),             # -1 = centered
            "y": to_int(dv.get("y"), -1),
            "sprite": KEY2WOODCUT.get(key, ""),       # woodcut/scene sprite id or ""
        })
    with_w = sum(1 for r in rows if r["box_w"])
    with_s = sum(1 for r in rows if r["sprite"])
    out = {"_note": ("The message catalog: each GAME.TXT @KEY -> its verbatim text + the box size / "
                     "placement the original used (@width/@x/@y from GAME.full.json) + associated "
                     "sprite (sprite-catalog id). ShowPopup/Notify reference only the key; the runtime "
                     "renders this record. Generated by tools/build_messages.py."),
           "count": len(rows), "with_box_w": with_w, "with_sprite": with_s, "messages": rows}
    json.dump(out, open(os.path.join(ROOT, "data_extracted/engine/messages.json"), "w"), indent=1)
    print(f"messages.json: {len(rows)} messages, {with_w} with @width, {with_s} with a sprite")

if __name__ == "__main__":
    main()
