#!/usr/bin/env python3
"""build_spec_data.py -- render the COMPLETE @-key bodies and data tables into
the existing spec/data/ docs, inside regenerable GENERATED blocks.

Per the user directive (2026-06-18): document EVERY @-key body across all 14
.TXT files and populate ALL data tables of all types, consolidated into the
existing spec/data files. Bodies/tables are machine-rendered VERBATIM from the
verified basis -- never hand-transcribed (transcription = fabrication risk) and
regenerated idempotently between markers, so hand-written prose outside the
markers is preserved.

Inputs (the verified basis):
  data_extracted/text/*.full.json        -- legend + directives + body per @key
  data_extracted/tables/names_tables.json -- typed NAMES tables (csv + list)
  data_extracted/tables/tribe_tables.json -- TRIBE dispersal coord tables
  data_extracted/tables/dgroup_tables.json -- DGROUP layout catalog

Targets (generated block spliced between BEGIN/END markers):
  spec/data/names_sections.md   :: names-bodies   (31 NAMES sections, full bodies)
  spec/data/text_resources.md   :: text-bodies    (11 text files, full bodies)
  spec/data/tables.md           :: data-tables    (every NAMES/TRIBE/DGROUP table)
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEXT = ROOT / "data_extracted" / "text"
TABLES = ROOT / "data_extracted" / "tables"
SPEC = ROOT / "spec" / "data"

GEN = "tools/build_spec_data.py"

# Text files whose full bodies go into text_resources.md (NAMES -> its own doc;
# TRIBE -> tables.md as coord data; README has 0 keys).
TEXT_FILES = ["GAME", "PEDIA", "LABELS", "MENU", "COLONY", "MAPEDIT",
              "MAPMENU", "DEBUG", "OPENING", "CLOSING", "WOODCUT"]


# ---------- helpers ----------

def fence_for(body: str) -> str:
    """Pick a backtick fence longer than any run inside the body."""
    longest = 0
    run = 0
    for ch in body:
        run = run + 1 if ch == "`" else 0
        longest = max(longest, run)
    return "`" * max(3, longest + 1)


def cell(s) -> str:
    """Escape a value for a markdown table cell."""
    if s is None:
        return ""
    return str(s).replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ¶ ").strip()


def splice(path: Path, block_id: str, content: str) -> None:
    """Replace (or append) the GENERATED:block_id region in `path`."""
    begin = f"<!-- BEGIN GENERATED:{block_id} ({GEN}) -->"
    end = f"<!-- END GENERATED:{block_id} -->"
    block = f"{begin}\n{content}\n{end}"
    text = path.read_text(encoding="utf-8")
    b = text.find(begin)
    if b != -1:
        e = text.find(end, b)
        e_full = e + len(end)
        text = text[:b] + block + text[e_full:]
    else:
        if not text.endswith("\n"):
            text += "\n"
        text += "\n" + block + "\n"
    path.write_text(text, encoding="utf-8")


# ---------- body rendering ----------

def render_section_body(key: str, sec: dict) -> list[str]:
    out = [f"#### `{key}`"]
    meta = []
    nb = [l for l in sec.get("body", "").split("\n") if l.strip()]
    meta.append(f"{len(nb)} line(s)")
    if sec.get("directives"):
        meta.append("directives: " + ", ".join(f"`{k}={v}`" for k, v in sec["directives"].items()))
    out.append("*" + " · ".join(meta) + "*")
    if sec.get("legend"):
        out.append("> legend: " + " ⏐ ".join(sec["legend"]))
    body = sec.get("body", "")
    if body.strip() == "":
        out.append("*(empty body — layout/config key)*")
    else:
        f = fence_for(body)
        out.append(f + "text")
        out.append(body)
        out.append(f)
    out.append("")
    return out


def ordered_sections(data: dict) -> list:
    """Order-preserving section list (keeps duplicate keys; some files repeat
    @smallfont/@options/@STOP). Falls back to the dict if an older basis lacks
    the ordered list."""
    if "sections_ordered" in data:
        return [(s["key"], s) for s in data["sections_ordered"]]
    return list(data["sections"].items())


def render_names_bodies() -> str:
    data = json.load(open(TEXT / "NAMES.full.json", encoding="utf-8"))
    secs = ordered_sections(data)
    out = [
        f"## Complete section bodies ({len(secs)} `@`-sections, verbatim)",
        "",
        f"_Generated by `{GEN}` from `data_extracted/text/NAMES.full.json` "
        "(the verified basis). Bodies are VERBATIM DOS cp437 text. Numeric/list "
        "tables are also rendered in [`tables.md`](tables.md); here the full raw "
        "bodies are preserved._",
        "",
    ]
    for key, sec in secs:
        out += render_section_body(key, sec)
    return "\n".join(out)


def render_text_bodies() -> str:
    out = [
        "## Complete section bodies — all text resources (verbatim)",
        "",
        f"_Generated by `{GEN}` from `data_extracted/text/*.full.json`. Every "
        "`@`-key across the non-NAMES text files, full body verbatim. "
        "NAMES.TXT → [`names_sections.md`](names_sections.md); TRIBE.TXT "
        "(coordinate data) → [`tables.md`](tables.md); README.TXT has 0 keys._",
        "",
    ]
    grand = 0
    for stem in TEXT_FILES:
        p = TEXT / f"{stem}.full.json"
        if not p.is_file():
            out.append(f"### {stem}.TXT — *(missing basis)*\n")
            continue
        data = json.load(open(p, encoding="utf-8"))
        secs = ordered_sections(data)
        grand += len(secs)
        out.append(f"### {data['file']} — {len(secs)} `@`-section(s)")
        out.append("")
        for key, sec in secs:
            out += render_section_body(key, sec)
    out.insert(3, f"**Total rendered: {grand} sections across {len(TEXT_FILES)} files.**\n")
    return "\n".join(out)


# ---------- table rendering ----------

def render_one_table(key: str, t: dict) -> list[str]:
    out = [f"#### `{key}` — {t['kind']} ({t['row_count']} row(s))"]
    if t.get("legend"):
        out.append("> legend: " + " ⏐ ".join(t["legend"]))
    out.append(f"> byte anchor: {t['byte_anchors']}")
    out.append("")
    rows = t["rows"]
    cols = t.get("columns")
    if t["kind"] == "list" or (cols and rows and isinstance(rows[0], dict)):
        header = cols
        out.append("| " + " | ".join(header) + " |")
        out.append("|" + "|".join("---" for _ in header) + "|")
        for r in rows:
            out.append("| " + " | ".join(cell(r.get(c)) for c in header) + " |")
    else:
        # raw rows (list of lists); use named columns as header if present
        width = max((len(r) for r in rows), default=0)
        if cols and len(cols) >= width:
            header = cols[:width]
        elif cols:
            header = cols + [f"col{i}" for i in range(len(cols), width)]
        else:
            header = [f"col{i}" for i in range(width)]
        out.append("| " + " | ".join(header) + " |")
        out.append("|" + "|".join("---" for _ in header) + "|")
        for r in rows:
            padded = list(r) + [""] * (len(header) - len(r))
            out.append("| " + " | ".join(cell(x) for x in padded) + " |")
    out.append("")
    return out


def render_tables() -> str:
    names = json.load(open(TABLES / "names_tables.json", encoding="utf-8"))
    tribe = json.load(open(TABLES / "tribe_tables.json", encoding="utf-8"))
    dgroup = json.load(open(TABLES / "dgroup_tables.json", encoding="utf-8"))

    out = [
        "## Complete data tables (every type, generated)",
        "",
        f"_Generated by `{GEN}` from `data_extracted/tables/*.json`. Values are "
        "VERBATIM game-data bytes; columns are the files' own `;` legends; "
        "`byte anchor` cites the EXE loader/use-site or `TBD`. `id` columns: the "
        "row index IS the runtime id (CLAUDE.md hard rule)._",
        "",
        f"### A. NAMES.TXT tables ({len(names)})",
        "",
    ]
    for key, t in names.items():
        out += render_one_table(key, t)

    out += [f"### B. TRIBE.TXT dispersal tables ({len(tribe)})", "",
            "_Each row is a settlement `(map_x, map_y)` from the tribe's historical "
            "dispersal template (loaded by `func_0749E0`, matched to NativeSettlement "
            "`DGROUP:0x54EC` at init)._", ""]
    for key, t in tribe.items():
        out += render_one_table(key, t)

    out += render_dgroup(dgroup)
    return "\n".join(out)


def render_dgroup(dgroup: dict) -> list[str]:
    out = [
        f"### C. DGROUP data-segment layout catalog "
        f"({dgroup['record_count']} records, {dgroup['scalar_count']} scalars)",
        "",
        "> " + dgroup["_note"],
        "",
        f"_Generated from `{dgroup['source']}` (byte-verified). These are the "
        "in-memory record/scalar tables; field **values** are runtime (reproduce "
        "via a memory dump), the **layout** is the byte-verified deliverable._",
        "",
    ]
    for r in dgroup["records"]:
        name = str(r["record"]).split("—")[0].strip() or r["record"]
        meta = []
        if r.get("dgroup_base"):
            meta.append(f"base `DGROUP:{r['dgroup_base']}`")
        if r.get("stride_hex"):
            sd = f" ({r['stride_dec']} B)" if r.get("stride_dec") else ""
            meta.append(f"stride `{r['stride_hex']}`{sd}")
        if r.get("count"):
            meta.append(f"count {r['count']}")
        out.append(f"#### {name} — " + ", ".join(meta) if meta else f"#### {name}")
        out.append(f"> source: {r['source']} · value_source: {r['value_source']}")
        out.append("")
        header = r["header"]
        out.append("| " + " | ".join(header) + " |")
        out.append("|" + "|".join("---" for _ in header) + "|")
        for f in r["fields"]:
            out.append("| " + " | ".join(cell(f.get(h)) for h in header) + " |")
        out.append("")

    out += ["#### Scalar globals (DGROUP)", "",
            "| Address | Type | Meaning | Group | Verified by |",
            "|---|---|---|---|---|"]
    for s in dgroup["scalars"]:
        row = s["row"]
        typ = row.get("Type", "")
        meaning = row.get("Meaning") or row.get("Purpose") or ""
        ver = row.get("Verified by") or row.get("Writer site (file offset)") or ""
        out.append("| " + " | ".join(cell(x) for x in
                   [s["address"], typ, meaning, s["group"], ver]) + " |")
    out.append("")
    return out


def main() -> int:
    splice(SPEC / "names_sections.md", "names-bodies", render_names_bodies())
    print("[spec] names_sections.md  names-bodies block written")
    splice(SPEC / "text_resources.md", "text-bodies", render_text_bodies())
    print("[spec] text_resources.md  text-bodies block written")
    splice(SPEC / "tables.md", "data-tables", render_tables())
    print("[spec] tables.md  data-tables block written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
