#!/usr/bin/env python3
"""Generate cport/PORT_LEDGER.md — every game.js function classified for the C port.

Classification is mechanical, from what each function's body touches:

  SIM      no rendering/DOM/browser surface at all -> port to C
  RENDER   draws (ctx./canvas/sheetFrame/plaque/...) and nothing else UI-ward
           -> excluded (future interface layer)
  UI       screen/input plumbing (event handlers, screen switching, dialog
           layout) -> excluded, but any embedded game DECISIONS must be
           hoisted into the core (flagged HOIST)
  BROWSER  asset loading / Image / fetch / localStorage -> n.a. on Teensy

A function that both draws and mutates game state is flagged MIXED:HOIST —
those are the dangerous ones, listed first, because the game-logic half must
move into the core before the render half can be dropped.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "port/src/game.js"
OUT = ROOT / "cport/PORT_LEDGER.md"

RENDER_PAT = re.compile(
    r"\bctx\.|\bcanvas\b|sheetFrame\(|plaque\(|hollowRect\(|countBadge\(|"
    r"drawCountRow\(|proportionalStrip\(|fillRect|drawImage|putImageData|"
    r"getImageData|fillText|drawText\(|drawStr\(|blitGlyph|createImageData")
BROWSER_PAT = re.compile(
    r"\bdocument\.|\bwindow\.|new Image\b|\bfetch\(|localStorage|"
    r"requestAnimationFrame|addEventListener|AudioContext|\bImage\(")
INPUT_PAT = re.compile(
    r"\bmouse|\bclick|\bkey[A-Z]|\be\.key\b|\bpointer|onKey|onMouse|hitTest")
STATE_PAT = re.compile(
    r"\bG\.[A-Za-z_]+\s*(=|\+=|-=|\+\+|--)|\bG\.units\.(push|splice)|"
    r"\bc\.stock\[|\bu\.(x|y|moves|orders)\s*=")

def parse_functions(text):
    lines = text.split("\n")
    heads = []
    for i, l in enumerate(lines):
        m = (re.match(r"^(?:async )?function ([A-Za-z_$][\w$]*)", l) or
             re.match(r"^const ([A-Za-z_$][\w$]*) = (?:async )?(?:\(|[A-Za-z_(])", l))
        if m:
            heads.append((i, m.group(1)))
    out = []
    for k, (i, name) in enumerate(heads):
        end = heads[k + 1][0] if k + 1 < len(heads) else len(lines)
        out.append((name, i + 1, end, "\n".join(lines[i:end])))
    return out

def classify(body):
    render = bool(RENDER_PAT.search(body))
    browser = bool(BROWSER_PAT.search(body))
    inputp = bool(INPUT_PAT.search(body))
    state = bool(STATE_PAT.search(body))
    if browser and not (render or state):
        return "BROWSER", ""
    if render and state:
        return "MIXED", "HOIST"
    if render:
        return "RENDER", ""
    if inputp and state:
        return "UI", "HOIST"
    if inputp:
        return "UI", ""
    return "SIM", ""

def main():
    text = SRC.read_text()
    funcs = parse_functions(text)
    rows = []
    for name, start, end, body in funcs:
        cat, flag = classify(body)
        rows.append({"name": name, "line": start, "size": end - start,
                     "cat": cat, "flag": flag})
    counts = {}
    for r in rows:
        counts[r["cat"]] = counts.get(r["cat"], 0) + 1

    md = ["# C-port function ledger — generated by tools/gen_port_ledger.py",
          "",
          "One row per game.js function. `SIM` rows are ported to C; `RENDER`/",
          "`BROWSER` rows are excluded (future interface layer); `MIXED`/`UI`",
          "rows flagged **HOIST** contain game decisions interleaved with",
          "presentation — the decision half moves into the core.",
          "",
          "Status column is maintained by hand as porting proceeds:",
          "`todo` / `ported` / `excluded` / `n.a.`",
          "",
          "| Category | Count |",
          "|---|---|"]
    for c in sorted(counts):
        md.append("| %s | %d |" % (c, counts[c]))
    md += ["", "## MIXED (game logic interleaved with drawing) — hoist first", "",
           "| Function | Line | Lines | Status |", "|---|---|---|---|"]
    for r in rows:
        if r["cat"] == "MIXED":
            md.append("| `%s` | %d | %d | todo |" % (r["name"], r["line"], r["size"]))
    for cat, title in (("SIM", "SIM — port to C"),
                       ("UI", "UI — input/screen plumbing (HOIST rows carry decisions)"),
                       ("RENDER", "RENDER — excluded"),
                       ("BROWSER", "BROWSER — n.a. on Teensy")):
        md += ["", "## " + title, "", "| Function | Line | Lines | Flag | Status |",
               "|---|---|---|---|---|"]
        for r in rows:
            if r["cat"] == cat:
                st = "todo" if cat == "SIM" or r["flag"] else \
                     ("excluded" if cat in ("RENDER", "UI") else "n.a.")
                md.append("| `%s` | %d | %d | %s | %s |"
                          % (r["name"], r["line"], r["size"], r["flag"], st))
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(md) + "\n")
    print("functions:", len(rows), " ", json.dumps(counts))
    print("->", OUT)

if __name__ == "__main__":
    main()
