#!/usr/bin/env python3
"""Generate the Arduino-IDE sketch folder for the Elecrow CrowPanel
Advance 7" ESP32-P4 (1024x600 MIPI-DSI + GT911 + microSD).

Same flattening as tools/gen_arduino_sketch.py (the Teensy build): the
Arduino IDE only compiles sources INSIDE the sketch folder and passes
no -I/-D flags, so this tool assembles cport/arduino_p4/colopy_p4/:

  * copies every needed .c/.h from core/, data/, render/, game/,
    rewriting the cross-directory includes ("../core/colopy_sim.h" ->
    "colopy_sim.h" -- unique basenames asserted);
  * copies the Elecrow reference configs (cport/p4/elecrow_ref/, see
    PROVENANCE.md) that ESP32_Display_Panel reads: board_config.h
    (with the Lesson08 SD pins appended), esp_panel_board_custom_conf.h,
    esp_panel_drivers_conf.h, esp_utils_conf.h;
  * emits colopy_p4.ino = a build-config banner + the verbatim
    cport/p4/colopy_p4.ino;
  * writes the sketch-local README.md with the IDE steps.

The pak is NOT compiled in on this board (the P4NRW32 has 32 MB PSRAM;
COLOPY.PAK loads from the SD card).  Re-run after pulling engine
changes; the copies are generated output.  Run from the repo root:

    python3 tools/gen_arduino_p4_sketch.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "cport" / "arduino_p4" / "colopy_p4"
REF = ROOT / "cport" / "p4" / "elecrow_ref"

SOURCES = [
    "cport/core/*.c", "cport/core/*.h",
    "cport/data/colopy_data.c", "cport/data/colopy_data.h",
    "cport/data/colopy_text.c", "cport/data/colopy_text.h",
    "cport/data/colopy_ui.c", "cport/data/colopy_ui.h",
    "cport/data/colopy_pak.h",
    "cport/render/*.c", "cport/render/*.h",
    "cport/game/*.c", "cport/game/*.h",
]

INO_SRC = ROOT / "cport" / "p4" / "colopy_p4.ino"

# ESP32_Display_Panel configs, verbatim from Elecrow's working Lesson07
# (cport/p4/PROVENANCE.md).  board_config.h additionally gets the
# Lesson08 SD pin block appended below.
REF_CONFIGS = [
    "esp_panel_board_custom_conf.h",
    "esp_panel_drivers_conf.h",
    "esp_utils_conf.h",
]

CONFIG = """\
/* ==== Arduino IDE build config (generated: tools/gen_arduino_p4_sketch.py)
 *
 * Target: Elecrow CrowPanel Advance 7" ESP32-P4 (P4NRW32: 16 MB flash,
 * 32 MB PSRAM, 1024x600 MIPI-DSI, GT911 touch, microSD).  Everything
 * below this banner is the verbatim cport/p4/colopy_p4.ino; the
 * .c/.h files beside it are flattened copies of
 * cport/{core,data,render,game} plus Elecrow's panel configs
 * (cport/p4/elecrow_ref/, see PROVENANCE.md) -- regenerate with the
 * tool after pulling engine changes, do not edit them here.
 *
 * REQUIRED LIBRARIES: Elecrow's bundled, PRE-CONFIGURED copies from
 * their repo (example/V1.2/Arduino_Code/libraries/) -- see README.md.
 * The Library Manager copy of ESP32_Display_Panel is NOT pre-configured
 * for this panel.
 *
 * COLOPY_AUTOBOOT: at power-on, load this .SAV from the SD card root
 * and enter the game loop -- no PC needed (touch answers dialogs).
 * Comment it out for the bare serial shell. */
#define COLOPY_AUTOBOOT "COLONY00.SAV"

"""

README = """\
# Colopy — Arduino IDE sketch (CrowPanel Advance 7" ESP32-P4)

GENERATED by `tools/gen_arduino_p4_sketch.py` — do not edit the copied
`.c`/`.h` files here; change the originals under `cport/` and re-run
the tool.  Build config (autoboot save name) is the banner at the top
of `colopy_p4.ino`.

The 320x200 game screen shows at an exact 3x scale (960x600) with a
32-px black pillarbox each side.  Play is TOUCH-COMPLETE — no
keyboard exists for this board (its USB port is device-mode only):

  tap             click (menus / colony / Europe / dialog rows); on
                  the map, tapping a tile next to the active unit
                  MOVES it there (attack / enter colony included)
  long-press      Space -- skip the active unit
  two-finger tap  Escape -- close a menu or dismiss a dialog

Unit orders (fortify, plow, road, build colony...) are rows in the
tappable ORDERS pulldown; the reports are in the menu bar.  The
serial shell (`k <name>` keys, digests) is optional -- for bench
tests and typing free-text names.

## Steps

1. Arduino IDE 2.x: Preferences -> Additional boards manager URLs, add
   `https://espressif.github.io/arduino-esp32/package_esp32_index.json`
   then Boards Manager -> install **esp32 by Espressif** (3.1.0 or
   newer — the ESP32-P4 needs the 3.x core).
2. Libraries: copy the three folders from this repo's
   `cport/p4/arduino_libraries/` (`ESP32_Display_Panel`,
   `ESP32_IO_Expander`, `esp-lib-utils`) into your Arduino
   `libraries/` folder, REPLACING any existing copies with those
   names.  They are Elecrow's own pre-configured bundle, vendored
   here (see the README beside them) — the Library Manager versions
   ship unconfigured and will NOT build.  Prefer a sketchbook
   location OUTSIDE OneDrive (File -> Preferences): OneDrive
   placeholder files break the compiler with "Invalid argument"
   errors.
3. Open `colopy_p4.ino`.  Tools menu: Board **ESP32P4 Dev Module**,
   PSRAM **Enabled**, Flash Size **16MB**, Partition Scheme a
   large-app layout (e.g. "Huge APP"), USB CDC On Boot **Enabled**
   (the serial shell talks over the USB-C port).  If a setting is
   missing on your core version, the defaults of Elecrow's own lessons
   apply — see their wiki for the board.
4. microSD (FAT32, files in the card ROOT): copy `cport/pak/COLOPY.PAK`
   (build it with `python3 bin/reconstitute.py` then
   `python3 tools/gen_sd_pack.py`) and a save file, e.g.
   `raw/COLONIZE/COLONY00.SAV`.
5. Flash.  With the default `COLOPY_AUTOBOOT` config the board loads
   `COLONY00.SAV` and enters the game by itself — play by touch.  Or
   open Serial Monitor at 115200 baud:

       l COLONY00.SAV      load
       v                   draw the map view once
       g                   game loop (touch + `k <name>` over serial:
                           `k Space`, `k ArrowUp`, `k !g` = Alt+G)
       t 100               run 100 turns, one digest line per turn
       d / i / s OUT.SAV   digest / overview / save back to SD

The digests from `t 100` must match a host run
(`cport/host/smoke --saveout <fixture> 100 out.sav`) turn for turn —
that is the hardware acceptance test, identical to the Teensy build's.
Hardware provenance for every pin/timing: `cport/p4/PROVENANCE.md`.
"""

INCLUDE_RE = re.compile(r'(#include\s+")(?:\.\./)+[a-z]+/(colopy_\w+\.h)(")')


def compose_board_config():
    """Lesson07's board_config.h + the Lesson08 SD pin block (both
    byte-exact Elecrow files; PROVENANCE.md)."""
    base = (REF / "board_config.h").read_text()
    sd = (REF / "lesson08_board_config.h").read_text()
    m = re.search(r"// SD card GPIO with SD_MMC.*?(?=/\*{10,})", sd, re.S)
    if not m:
        sys.exit("SD pin block not found in lesson08_board_config.h")
    return (base.rstrip() + "\n\n"
            "/* SD pins appended from Elecrow Lesson08 board_config.h\n"
            " * (cport/p4/elecrow_ref/lesson08_board_config.h) */\n" +
            m.group(0).rstrip() + "\n")


def main():
    files = []
    for pat in SOURCES:
        got = sorted(ROOT.glob(pat))
        if not got:
            sys.exit(f"no sources match {pat} (run from a full checkout)")
        files += [p for p in got if p.suffix in (".c", ".h")]
    names = [p.name for p in files]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        sys.exit(f"basename collision across dirs: {sorted(dupes)} — "
                 "the flat-include rewrite would be ambiguous")

    DEST.mkdir(parents=True, exist_ok=True)
    for stale in list(DEST.glob("*.c")) + list(DEST.glob("*.h")) + \
                 list(DEST.glob("*.ino")):
        stale.unlink()

    for p in files:
        text = p.read_text()
        text, n = INCLUDE_RE.subn(r"\1\2\3", text)
        (DEST / p.name).write_text(text)

    for name in REF_CONFIGS:
        (DEST / name).write_text((REF / name).read_text())
    (DEST / "board_config.h").write_text(compose_board_config())

    (DEST / "colopy_p4.ino").write_text(CONFIG + INO_SRC.read_text())
    (DEST / "README.md").write_text(README)
    print(f"wrote {len(files) + len(REF_CONFIGS) + 2} sources + README to "
          f"{DEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
