#!/usr/bin/env python3
# hot_globals.py
#
# For each function in the EXE, list the unique memory-operand displacements
# (i.e. global variable addresses) referenced by its instructions. The
# globals with the most references across distinct functions are the
# game-state hotspots — current player, turn counter, map pointers, the
# unit/colony arrays, etc.
#
# Output: code/<EXE>/hot_globals.md, plus per-function global lists in
# code/<EXE>/per_func_globals.json.

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

try:
    from capstone import Cs, CS_ARCH_X86, CS_MODE_16, CS_OP_MEM, CS_OP_IMM
except ImportError:
    import sys
    print("ERROR: capstone not installed.", file=sys.stderr)
    sys.exit(1)

import disasm_mz


def collect_per_func(file_bytes: bytes, hdr: disasm_mz.MzHeader, funcs: list[dict]) -> dict:
    md = Cs(CS_ARCH_X86, CS_MODE_16)
    md.detail = True

    # Per-function set of {memdisp_value: [example_mnemonics]}.
    per_func: dict[str, dict[int, list[str]]] = {}
    # Global counters: how many distinct functions ref each address.
    addr_to_funcs: dict[int, set[str]] = defaultdict(set)
    addr_to_count: Counter = Counter()

    for f in funcs:
        host_off = f["file_offset"]
        host_off_int = int(host_off, 16)
        size = f["size"]
        func_bytes = file_bytes[host_off_int : host_off_int + size]
        per_func[host_off] = {}
        for ins in md.disasm(func_bytes, host_off_int):
            for op in ins.operands:
                if op.type == CS_OP_MEM:
                    disp = op.mem.disp & 0xFFFF
                    # Only consider displacements that look like global-variable
                    # addresses: must be > 0 (not a `[bp+X]` local) AND must
                    # not have base/index registers (those are pointer-deref
                    # patterns, not direct globals).
                    if disp == 0:
                        continue
                    if op.mem.base != 0 or op.mem.index != 0:
                        continue
                    per_func[host_off].setdefault(disp, [])
                    if len(per_func[host_off][disp]) < 3:
                        per_func[host_off][disp].append(ins.mnemonic)
                    addr_to_funcs[disp].add(host_off)
                    addr_to_count[disp] += 1

    return {
        "per_func": {
            k: {f"0x{addr:04X}": mnems for addr, mnems in v.items()}
            for k, v in per_func.items()
        },
        "addr_to_funcs": {
            f"0x{addr:04X}": sorted(funcs)
            for addr, funcs in addr_to_funcs.items()
        },
        "addr_total_refs": dict(addr_to_count),
    }


def write_md(out_dir: Path, exe_name: str, funcs: list[dict], data: dict, top_n: int = 60) -> None:
    addr_to_funcs = data["addr_to_funcs"]
    addr_total = data["addr_total_refs"]

    # Sort by (distinct functions, total refs).
    addrs_sorted = sorted(
        addr_to_funcs.items(),
        key=lambda kv: (-len(kv[1]), -addr_total[int(kv[0], 16)]),
    )

    fns_by_off = {f["file_offset"]: f for f in funcs}

    lines: list[str] = []
    lines.append(f"# {exe_name} — Hot global addresses")
    lines.append("")
    lines.append(
        "Memory-operand displacements (direct global variables, not "
        "[bp+N] locals or [reg+disp] pointer-deref) ranked by how many "
        "distinct functions reference each. Generated by "
        "`tools/hot_globals.py`."
    )
    lines.append("")
    lines.append(f"_Top {top_n} hottest globals (by distinct-function count):_")
    lines.append("")
    lines.append("| Addr | Distinct fns | Total refs | Function offsets touching it |")
    lines.append("|------|-------------:|-----------:|------------------------------|")
    for addr, fnlist in addrs_sorted[:top_n]:
        total = addr_total[int(addr, 16)]
        fnstr = ", ".join(
            (
                f"{o} `{fns_by_off.get(o, {}).get('name', '?')}`"
                if fns_by_off.get(o, {}).get("name") not in (None, "unknown")
                else o
            )
            for o in fnlist[:8]
        )
        if len(fnlist) > 8:
            fnstr += f", … (+{len(fnlist) - 8})"
        lines.append(f"| `{addr}` | {len(fnlist)} | {total} | {fnstr} |")
    lines.append("")
    (out_dir / "hot_globals.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(Path(__file__).resolve().parent.parent))
    ap.add_argument("--exe", default="VICEROY.EXE")
    args = ap.parse_args()

    root = Path(args.root)
    raw = root / "raw" / "COLONIZE"
    code = root / "code"
    exe_path = raw / args.exe
    exe_dir = code / Path(args.exe).stem

    file_bytes = exe_path.read_bytes()
    hdr = disasm_mz.parse_mz(file_bytes)
    funcs = json.loads((exe_dir / "functions.json").read_text(encoding="utf-8"))["functions"]

    print(f"[hot_globals] {args.exe}: {len(funcs)} functions…")
    data = collect_per_func(file_bytes, hdr, funcs)
    print(f"              found {len(data['addr_to_funcs'])} distinct global addresses referenced")
    write_md(exe_dir, args.exe, funcs, data)

    (exe_dir / "per_func_globals.json").write_text(
        json.dumps(data, indent=2),
        encoding="utf-8",
    )
    print(f"              wrote hot_globals.md, per_func_globals.json")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
