"""
overlay_segment_inferrer.py -- group overlay functions by RTLink segment.

Approach:
  1. Sort all overlay functions by file_offset.
  2. Detect "segment boundaries" by looking for:
     - Gaps > 256 bytes between consecutive functions (likely segment break).
     - Long padding sequences (90 90 90 ... NOP runs).
  3. Cross-reference with the RTLink thunk table at file 0x01A5F0:
     - Each thunk's ljmp_off is the entry point of a function within
       its target segment. If we sort thunks by their target segment +
       offset, we get the load-order of each segment.
  4. Emit per-segment listings for the manifest.

Output:
  - code/VICEROY/overlay_segments.json  (segment id -> list of function offsets)
  - viceroy_source/src/overlay/SEGMENTS.md  (human-readable per-segment listing)
"""

import json
import os
from collections import defaultdict, Counter

PROJECT = str(__import__("pathlib").Path(__file__).resolve().parents[1])
FUNCTIONS_JSON = os.path.join(PROJECT, "code", "VICEROY", "functions.json")
THUNKS_JSON = os.path.join(PROJECT, "code", "VICEROY", "overlay_thunks.json")
OUT_JSON = os.path.join(PROJECT, "code", "VICEROY", "overlay_segments.json")
OUT_MD = os.path.join(PROJECT, "viceroy_source", "src", "overlay", "SEGMENTS.md")

# Gap threshold: consecutive functions whose gap exceeds this are likely segment breaks
GAP_THRESHOLD = 256


def main():
    with open(FUNCTIONS_JSON) as f:
        funcs_data = json.load(f)
    with open(THUNKS_JSON) as f:
        thunks_data = json.load(f)

    overlay_funcs = sorted(
        [f for f in funcs_data['functions'] if f['region'] == 'overlay'],
        key=lambda f: int(f['file_offset'], 16))

    # ---- Detect segment boundaries by gap ----
    print(f"[seg_infer] {len(overlay_funcs)} overlay functions; detecting segment boundaries...")
    segments = []  # list of [list-of-functions]
    current = []
    last_end = None
    for f in overlay_funcs:
        start = int(f['file_offset'], 16)
        if last_end is not None and (start - last_end) >= GAP_THRESHOLD:
            # New segment boundary
            if current:
                segments.append(current)
            current = []
        current.append(f)
        last_end = start + f['size']
    if current:
        segments.append(current)

    print(f"[seg_infer] detected {len(segments)} segments")
    print(f"[seg_infer] segment sizes (functions): {[len(s) for s in segments]}")
    print(f"[seg_infer] segment sizes (bytes):")
    for i, seg in enumerate(segments):
        first = int(seg[0]['file_offset'], 16)
        last = int(seg[-1]['file_offset'], 16) + seg[-1]['size']
        size_b = last - first
        size_func_b = sum(f['size'] for f in seg)
        print(f"  seg #{i:2d}  0x{first:06X}..0x{last:06X}  ({size_b:6d} bytes total, {size_func_b:6d} bytes in functions, {len(seg)} fns)")

    # ---- Try to map RTLink thunk segments to detected ranges ----
    # Each thunk's ljmp_off tells us where in the segment we'd jump.
    # If we know the load-time segment base, we could compute the file offset.
    # We don't have that directly, but we can group thunks by trailer_word_1 (seg id)
    # and see which range of ljmp_offs each segment covers.
    thunks = thunks_data['thunks']
    seg_ljmps = defaultdict(list)
    for t in thunks:
        sid = t.get('trailer_word_1')
        if sid is not None:
            seg_ljmps[sid].append(t.get('ljmp_off', 0))

    print(f"\n[seg_infer] RTLink segment-id ljmp_off ranges:")
    for sid in sorted(seg_ljmps.keys()):
        offs = seg_ljmps[sid]
        print(f"  seg-id 0x{sid:04X}: {len(offs):3d} thunks, ljmp_off range = 0x{min(offs):04X}..0x{max(offs):04X}")

    # Save data
    out = {
        'detected_segments': [
            {
                'index': i,
                'first_offset': hex(int(seg[0]['file_offset'], 16)),
                'last_offset': hex(int(seg[-1]['file_offset'], 16) + seg[-1]['size']),
                'function_count': len(seg),
                'function_offsets': [f['file_offset'] for f in seg],
                'total_bytes': int(seg[-1]['file_offset'], 16) + seg[-1]['size'] - int(seg[0]['file_offset'], 16),
            }
            for i, seg in enumerate(segments)
        ],
        'rtlink_segment_ljmp_ranges': {
            f"0x{sid:04X}": {
                'thunk_count': len(offs),
                'min_ljmp_off': hex(min(offs)),
                'max_ljmp_off': hex(max(offs)),
            }
            for sid, offs in seg_ljmps.items()
        }
    }
    with open(OUT_JSON, 'w') as f:
        json.dump(out, f, indent=2)
    print(f"\n[seg_infer] wrote {OUT_JSON}")

    # Markdown summary
    with open(OUT_MD, 'w', encoding='utf-8') as f:
        f.write(f"# VICEROY Overlay Segments\n\n")
        f.write(f"Auto-generated by `tools/overlay_segment_inferrer.py`.\n\n")
        f.write(f"Total: **{len(segments)} detected segments** containing {len(overlay_funcs)} functions.\n")
        f.write(f"Segments are detected by gap-> 256-byte gap between consecutive function ends.\n\n")
        f.write(f"| # | First .. Last | Total bytes | In-function bytes | Functions |\n")
        f.write(f"|---|---|--:|--:|--:|\n")
        for i, seg in enumerate(segments):
            first = int(seg[0]['file_offset'], 16)
            last = int(seg[-1]['file_offset'], 16) + seg[-1]['size']
            total = last - first
            func_b = sum(f['size'] for f in seg)
            f.write(f"| {i} | 0x{first:06X}..0x{last:06X} | {total} | {func_b} | {len(seg)} |\n")

        f.write(f"\n## RTLink thunk-segment ljmp_off ranges\n\n")
        f.write(f"From `code/VICEROY/overlay_thunks.json`, the thunk table groups by\n")
        f.write(f"`trailer_word_1` (segment id). Each segment id covers a range of\n")
        f.write(f"`ljmp_off` values:\n\n")
        f.write(f"| Segment id | Thunk count | ljmp_off range |\n")
        f.write(f"|---|--:|---|\n")
        for sid in sorted(seg_ljmps.keys()):
            offs = seg_ljmps[sid]
            f.write(f"| 0x{sid:04X} | {len(offs)} | 0x{min(offs):04X}..0x{max(offs):04X} |\n")
    print(f"[seg_infer] wrote {OUT_MD}")


if __name__ == '__main__':
    main()
