// drydock-gen -- the host-side codegen tool (spec §7 consumer #1):
//
//   drydock-gen <data-dir>/schema <out-dir>
//
// Reads the SCHM records and emits <out-dir>/dd_gen.hpp containing, per record
// type: a plain C++ struct (value members + has_<field> presence bools), the
// field-offset reflection table (DDFieldInfo[]), the DDTypeInfo, and thin
// generated load/serialize wrappers over the generic reflection runtime
// (core/reflect.hpp). The reflection tables are the foundation every generic
// editor view drives through -- no per-type UI or I/O code anywhere.
//
// Emission is deterministic (types sorted by code, fields in schema order), so
// the generated header is stable across runs and safe to diff.
#include "schema.hpp"
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <algorithm>
#include <dirent.h>
#include <sys/stat.h>

using namespace drydock;

static std::string slurp(const std::string& p) {
    std::ifstream f(p);
    std::stringstream ss; ss << f.rdbuf();
    return ss.str();
}

// int/str only for the migrated P0 types; the emitter refuses anything it
// cannot yet represent rather than guessing (grow with the migration).
static const char* cpp_type(const FieldDef& fd) {
    switch (fd.type) {
        case FType::Int: return "int32_t";
        case FType::Str: return "std::string";
        case FType::Ref: return "std::string";      // ref id as string
        default: return nullptr;
    }
}
static const char* rtype_name(const FieldDef& fd) {
    switch (fd.type) {
        case FType::Int: return "RType::I32";
        case FType::Str: return "RType::Str";
        case FType::Ref: return "RType::RefId";
        default: return nullptr;
    }
}

static std::string type_struct(const std::string& code) {
    std::string s = "DD";
    s += (char)std::toupper((unsigned char)code[0]);
    s += code.substr(1);
    return s;                                        // "good" -> "DDGood"
}

int main(int argc, char** argv) {
    if (argc != 3) {
        std::fprintf(stderr, "usage: drydock-gen <schema-dir> <out-dir>\n");
        return 1;
    }
    const std::string schema_dir = argv[1], out_dir = argv[2];

    std::vector<std::string> files;
    if (DIR* d = opendir(schema_dir.c_str())) {
        while (dirent* e = readdir(d)) {
            std::string n = e->d_name;
            if (n.size() > 4 && n.substr(n.size() - 4) == ".rec")
                files.push_back(schema_dir + "/" + n);
        }
        closedir(d);
    }
    std::sort(files.begin(), files.end());
    if (files.empty()) { std::fprintf(stderr, "no schema .rec in %s\n", schema_dir.c_str()); return 1; }

    std::vector<Record> schm;
    std::string err;
    for (const auto& p : files)
        if (!parse_records(slurp(p), schm, err)) {
            std::fprintf(stderr, "%s: %s\n", p.c_str(), err.c_str());
            return 1;
        }
    Schema sc;
    if (!schema_load(schm, sc, err)) { std::fprintf(stderr, "%s\n", err.c_str()); return 1; }

    std::string o;
    o += "// GENERATED by drydock-gen -- do not edit. Source: data/schema/*.rec\n";
    o += "// Per record type: struct + field-offset reflection table + load/serialize\n";
    o += "// wrappers over the generic reflection runtime (core/reflect.hpp).\n";
    o += "#pragma once\n#include \"reflect.hpp\"\n\nnamespace drydock {\n";

    for (const auto& [code, td] : sc.types) {        // std::map: sorted by code
        const std::string S = type_struct(code);
        o += "\n// ---- " + code + " (schema v" + std::to_string(td.version) + ") ----\n";
        // fields the P1 struct emitter can represent; the rest stay accessible
        // through the generic Record path (noted in the header, never silent)
        std::vector<const FieldDef*> rep, skipped;
        for (const FieldDef& fd : td.fields)
            (cpp_type(fd) ? rep : skipped).push_back(&fd);
        for (const FieldDef* fd : skipped)
            o += "// NOTE: field '" + fd->name + "' (" + code +
                 ") not struct-represented yet -- use the generic Record path\n";
        o += "struct " + S + " {\n";
        for (const FieldDef* fd : rep) {
            o += "    " + std::string(cpp_type(*fd)) + " " + fd->name +
                 (fd->type == FType::Int ? " = 0;" : ";");
            if (!fd->doc.empty()) o += "   // " + fd->doc;
            o += "\n";
        }
        for (const FieldDef* fd : rep)
            o += "    bool has_" + fd->name + " = false;\n";
        o += "};\n";
        o += "inline const DDFieldInfo " + code + "_fields[] = {\n";
        for (const FieldDef* fd : rep)
            o += "    {\"" + fd->name + "\", " + rtype_name(*fd) + ", offsetof(" + S + ", " +
                 fd->name + "), offsetof(" + S + ", has_" + fd->name + ")},\n";
        o += "};\n";
        o += "inline const DDTypeInfo " + code + "_type = {\"" + code + "\", " + code +
             "_fields, " + std::to_string(rep.size()) + ", sizeof(" + S + ")};\n";
        o += "inline bool load_" + code + "(const Record& r, " + S + "& out) "
             "{ return reflect_load(" + code + "_type, r, &out); }\n";
        o += "inline Record serialize_" + code + "(const std::string& id, const " + S +
             "& v) { return reflect_serialize(" + code + "_type, id, &v); }\n";
    }
    o += "\n// registry of all generated types (Object Window walks this)\n";
    o += "inline const DDTypeInfo* dd_all_types[] = {\n";
    for (const auto& [code, td] : sc.types) o += "    &" + code + "_type,\n";
    o += "};\n";
    o += "inline const size_t dd_all_types_count = " + std::to_string(sc.types.size()) + ";\n";
    o += "\n} // namespace drydock\n";

    mkdir(out_dir.c_str(), 0755);
    const std::string out_path = out_dir + "/dd_gen.hpp";
    std::string old = slurp(out_path);
    if (old == o) { std::printf("drydock-gen: %s up to date\n", out_path.c_str()); return 0; }
    std::ofstream f(out_path);
    f << o;
    std::printf("drydock-gen: wrote %s (%zu types)\n", out_path.c_str(), sc.types.size());
    return 0;
}
